// =============================================================================
// Abandoned Cyber City - leaderboard backend (Cloudflare Worker + D1)
//
// Two endpoints the game hits via curl (the ONLY outbound channel BO3 has -
// docs/40 "✅ THE WORKING RECIPE"):
//   POST /games      - record one finished game (dedup by session id)
//   GET  /top10.txt  - the top 10, as PLAIN TEXT (one row per line) so the Lua
//                      side needs no JSON parser: "round|name1,name2,name3,name4"
//   GET  /top10.json - same data as JSON (for web/debug)
//   GET  /health     - liveness
//
// Anti-abuse note: the game is shipped to the public and the request key is
// EXTRACTABLE from the fastfile, so this can never be fully cheat-proof (docs/40).
// This Worker does the cheap, high-value server-side gates: a shared key check,
// strict field validation/clamping, per-IP rate limiting, and dedup-by-session.
// Serious records stay video-verified (zwr.gg). Tune to taste.
//
// Deploy: see README.md (wrangler or dashboard). Bindings expected:
//   env.DB       - D1 database (see schema.sql)
//   env.ACC_KEY  - shared secret; the game sends it as the `x-acc-key` header.
//                  Set via `wrangler secret put ACC_KEY` (or dashboard Variables).
//                  If unset, the key check is skipped (open board).
// =============================================================================

// id -> display name for /stats/guns labels. INLINED (not imported) so the dashboard
// "paste worker.js only" deploy path keeps working - a JSON import would fail to resolve
// there and take down every endpoint. Regenerated by tools/gen_gun_ids.js from
// tools/gun_ids.json; DO NOT hand-edit between the markers.
// <<< BEGIN GENERATED gun-id labels (tools/gen_gun_ids.js) - DO NOT hand-edit >>>
const GUN_IDS = { ids: {
  "0": "Other",
  "1": "Five-Seven",
  "2": "Peacekeeper",
  "3": "Havoc",
  "4": "Alternator",
  "5": "Prowler",
  "6": "Triple Take",
  "7": "Tac-19",
  "8": "AK-47",
  "9": "XM4",
  "10": "Streetsweeper",
  "11": "CEL-3 Cauterizer",
  "12": "AE4",
  "13": "PPSH-41",
  "14": "AK-74u",
  "15": "Olympia",
  "16": "Grav",
  "17": "M60",
  "18": "RPD",
  "19": "HAMR",
  "20": "MK14",
  "21": "MORS",
  "22": "RW1",
  "23": "Mahem",
  "24": "War Machine",
  "25": "Thundergun",
  "26": "Blast-O-Matic",
  "27": "Fire Bow",
  "28": "Leviathan Axe",
  "29": "Winter's Howl",
  "30": "Action Figure",
  "31": "Ballistic Knife"
} };
// <<< END GENERATED gun-id labels >>>

// id -> box draw weight + the set of free/starting guns, for the availability-adjusted
// "preference index" in /stats/guns (docs/41 §3.6). Held-time alone measures EXPOSURE:
// a gun offered often by the box racks up seconds without being preferred. pref_index =
// held-share / box-offer-share divides that out. Regenerated by tools/gen_gun_ids.js
// from _acc_map_randomizer.gsc::acc_box_weight; DO NOT hand-edit between the markers.
// <<< BEGIN GENERATED gun-box-weight (tools/gen_gun_ids.js from _acc_map_randomizer.gsc acc_box_weight) - DO NOT hand-edit >>>
// Nominal full-pool box draw weight per gun id (docs/41 pref-index). Missing id = no box
// offer path (e.g. id 0 "other"); pref_index is then null. Auto-synced from GSC.
const GUN_BOX_WEIGHT = {
  "1": 312,
  "2": 71,
  "3": 60,
  "4": 230,
  "5": 264,
  "6": 249,
  "7": 259,
  "8": 79,
  "9": 64,
  "10": 271,
  "11": 244,
  "12": 234,
  "13": 97,
  "14": 256,
  "15": 297,
  "16": 306,
  "17": 87,
  "18": 288,
  "19": 280,
  "20": 253,
  "21": 133,
  "22": 239,
  "23": 108,
  "24": 120,
  "25": 12,
  "26": 12,
  "27": 12,
  "28": 12,
  "29": 12,
  "30": 40,
  "31": 92
};
// Gun ids that are ALSO a free/starting weapon (never drawn from the box to be acquired) ->
// pref_index is confounded upward for them; the endpoint flags is_starting so a reader discounts it.
const GUN_STARTING = new Set([1]);
// <<< END GENERATED gun-box-weight >>>

const MAX_ROUND = 2000;      // sanity clamp - no legit ACC game exceeds this
const NAME_MAX = 24;          // gamertag cap
const BOARD_LIMIT_MAX = 5000; // /top10.* ?limit cap: default 10 (in-game board), up to this for the analytics summary's FULL round history
const RATE_MAX = 20;          // max POSTs per IP per RATE_WINDOW
const RATE_WINDOW = 60;       // seconds

// --- weapon-usage telemetry clamps (docs/41) ---
const MAX_GUNS = 64;          // max gun rows per POST (slice extras)
const GUN_ID_MAX = 200;       // valid gun_id range [0, GUN_ID_MAX] (0 = other); generous headroom above the ~31 live guns so future guns aren't clamped (matches ACC_WPN_ID_MAX in _acc_weapon_usage.gsc)
const GUN_SECS_MAX = 200000;  // per-gun secs cap (a marathon game is < ~60000s)
const PICK_THRESHOLD = 3;     // secs a gun must be held in a game to count toward its pick rate
const BOX_OFFERS_MAX = 2000;  // Tier-B clamp: per-gun AND total offers cap per game (a marathon barely breaks 3 digits)
const DROP_ACQ_MAX   = 2000;  // Tier-C clamp: per-gun AND total acquires cap per game (mirrors BOX_OFFERS_MAX)

// --- per-player stats clamps (docs/40, named kills/downs/revives) ---
const STAT_KILLS_MAX = 1000000; // a marathon can rack huge kill counts; generous sanity ceiling
const STAT_DR_MAX    = 100000;  // downs/revives per game are far smaller; clamp well above any real game
const MAX_STAT_ROWS  = 4;       // at most 4 players per game

// Anonymous per-game dedup token for gun_time. Deterministic per session -> re-POSTs
// (co-op / marathon) upsert, never double-count.
// ANONYMITY (docs/41 decision 4, corrected after review): with GUN_KEY_SECRET set
// (recommended: `wrangler secret put GUN_KEY_SECRET`, a value NOT shipped in the game
// and NOT stored in D1), game_key = HMAC-SHA256(secret, session) - a D1 reader CANNOT
// recompute it from games.session_id, so gun_time is genuinely unjoinable to the
// gamertags in games. WITHOUT the secret it falls back to a plain digest that a DB
// operator COULD recompute from games.session_id; the payload is still aggregate-only
// (no per-player gun vector -> no individual attribution in co-op), but a SOLO game
// would then be operator-joinable to its player (low-sensitivity gun data). Do NOT
// use env.ACC_KEY here - it ships extractable in the fastfile.
async function hashGameKey(session, env) {
  const enc = new TextEncoder();
  let buf;
  if (env && env.GUN_KEY_SECRET) {
    const k = await crypto.subtle.importKey("raw", enc.encode(env.GUN_KEY_SECRET), { name: "HMAC", hash: "SHA-256" }, false, ["sign"]);
    buf = await crypto.subtle.sign("HMAC", k, enc.encode(session));
  } else {
    buf = await crypto.subtle.digest("SHA-256", enc.encode("acclb:" + session));
  }
  return [...new Uint8Array(buf)].map(b => b.toString(16).padStart(2, "0")).join("").slice(0, 32);
}

function txt(body, status = 200) {
  return new Response(body, { status, headers: { "content-type": "text/plain; charset=utf-8", "cache-control": "no-store" } });
}
function jsonResp(obj, status = 200) {
  return new Response(JSON.stringify(obj), { status, headers: { "content-type": "application/json; charset=utf-8", "cache-control": "no-store" } });
}

// Keep only printable, delimiter-safe chars in a gamertag (we use | and , as
// delimiters in the text format, so strip those + control chars).
// Server-side guard for the LUI name-capture glitch (2026-07-14): if the client sent a raw
// userdata handle ("userdata: 0000...") instead of a resolved gamertag, drop it to "?" so it
// is filtered out by the caller rather than stored as a name. The recording chunk now
// resolves names via Engine.Localize, but this backstops any game client still on an old .ff.
function cleanName(s) {
  const t = String(s == null ? "" : s)
    .replace(/[\x00-\x1f|,\\"]/g, " ")
    .trim();
  if (/^userdata:/i.test(t)) return "?";
  return t.slice(0, NAME_MAX) || "?";
}

export default {
  async fetch(request, env) {
    const url = new URL(request.url);
    const path = url.pathname;

    if (path === "/health") return txt("ok");

    // ---- read: top 10 ------------------------------------------------------
    if (request.method === "GET" && (path === "/top10.txt" || path === "/top10.json")) {
      // v2 board format (per-player stats UI, 2026-07-15): ?v2=N marks a v2-aware client
      // AND carries the player-count filter (N=1..4, 0=global) in ONE param - the in-game
      // agent .bat appends the query suffix under cmd delayed expansion, so we keep '&'
      // out of the suffix entirely rather than trust its metachar handling. v2 text rows
      // gain a third field: "round|names|name:kills:downs:revives,..." (per-game stats
      // from the player_stats table). Old clients never send v2 and get the old 2-field
      // rows; extra fields are also backward-safe (the GSC parser takes parts[0..1]).
      const v2Raw = url.searchParams.get("v2");
      const v2 = v2Raw != null;
      // Optional PER-PLAYER-COUNT board (?players=1..4, user request 2026-07-13):
      // separate solo/duo/trio/quad ladders. NO schema change - the player count is
      // derived from the existing `players` CSV: cleanName() strips commas from every
      // gamertag, so (commas + 1) is exactly the roster size. That invariant REQUIRES the
      // write path to never drop a roster entry (an unresolvable tag is stored as "?" so the
      // count survives - see the /games roster comment); the client counts the very same slots
      // to pick which ladder to ASK for. Absent/out-of-range param = the global all-counts
      // board (backward compatible with old clients + web).
      const pcRaw = parseInt(v2 ? v2Raw : url.searchParams.get("players"), 10);
      const pc = (pcRaw >= 1 && pcRaw <= 4) ? pcRaw : null;
      const whereCount = pc ? " WHERE (LENGTH(players) - LENGTH(REPLACE(players, ',', '')) + 1) = ?" : "";
      const bindCount = pc ? [pc] : [];
      // Row cap (user 2026-07-13 "get all the round-based data, not just top 10"): DEFAULT 10 so
      // the in-game Lua board + web stay the classic top-10 (the endpoint name is kept for
      // backward compat), but ?limit=N (1..BOARD_LIMIT_MAX) returns more - the analytics summary
      // passes a big limit to pull the FULL round history. Bound as a `?` param (clamped int).
      const limRaw = parseInt(url.searchParams.get("limit"), 10);
      const lim = Math.min(Math.max(limRaw >= 1 ? limRaw : 10, 1), BOARD_LIMIT_MAX);
      let rows;
      // Try the paradise_winner column; if it isn't migrated yet, fall back to the base
      // columns so the board never breaks on an un-migrated DB (deploy is order-independent).
      let hasWinnerCol = true;
      try {
        const res = await env.DB.prepare(
          `SELECT session_id, round, players, client_ts, paradise_winner FROM games${whereCount} ORDER BY round DESC, received_at ASC LIMIT ?`
        ).bind(...bindCount, lim).all();
        rows = res.results || [];
      } catch (e) {
        hasWinnerCol = false;
        try {
          const res = await env.DB.prepare(
            `SELECT session_id, round, players, client_ts FROM games${whereCount} ORDER BY round DESC, received_at ASC LIMIT ?`
          ).bind(...bindCount, lim).all();
          rows = res.results || [];
        } catch (e2) {
          return path.endsWith(".json") ? jsonResp({ error: "db" }, 500) : txt("", 500);
        }
      }
      const won = r => hasWinnerCol && !!r.paradise_winner;

      // Per-game player stats for the board rows (kills/downs/revives UI, 2026-07-15).
      // OWN try/catch (an un-migrated player_stats table just means no stats field, same
      // graceful posture as the winner column). Skipped for big analytics pulls
      // (?limit>100): the IN(...) placeholder list would approach SQLite's bind limit and
      // summary.js reads player_stats directly anyway. Rows within a game sort by kills
      // DESC so the board's player order is the interesting one.
      const statsBySession = new Map();
      if (rows.length && rows.length <= 100) {
        try {
          const ph = rows.map(() => "?").join(",");
          const sres = await env.DB.prepare(
            `SELECT session_id, name, kills, downs, revives FROM player_stats WHERE session_id IN (${ph})`
          ).bind(...rows.map(r => r.session_id)).all();
          for (const s of (sres.results || [])) {
            if (!statsBySession.has(s.session_id)) statsBySession.set(s.session_id, []);
            statsBySession.get(s.session_id).push({ name: s.name, kills: s.kills || 0, downs: s.downs || 0, revives: s.revives || 0 });
          }
          for (const arr of statsBySession.values()) arr.sort((a, b) => b.kills - a.kills);
        } catch (e) { /* table not migrated yet - board rows just carry no stats */ }
      }
      const statsOf = r => statsBySession.get(r.session_id) || [];

      // Cumulative map-wide totals for the board footer (user 2026-07-15: "0/465 games
      // have made it to the bottom of the trench"). Deliberately GLOBAL - NOT filtered by
      // the ?v2=N lobby-size ladder above: the line is a fact about the MAP (every run ever
      // recorded, every lobby size), not about the ladder on screen. OWN try/catch, same
      // graceful posture as the winner column + player_stats: a totals failure just means
      // the panel renders with no footer, never a broken board.
      let totals = null;
      try {
        const t = await env.DB.prepare(
          hasWinnerCol
            ? "SELECT COUNT(*) AS n, SUM(CASE WHEN paradise_winner = 1 THEN 1 ELSE 0 END) AS w FROM games"
            : "SELECT COUNT(*) AS n FROM games"
        ).first();
        if (t) totals = { games: t.n || 0, wins: t.w || 0 };
      } catch (e) { /* footer is best-effort */ }

      if (path === "/top10.json") {
        return jsonResp(rows.map(r => ({ round: r.round, players: r.players.split(","), paradise_winner: won(r), ts: r.client_ts, stats: statsOf(r) })));
      }
      // plain text: one row per line "round|csv-of-names" (Lua-friendly). A Paradise-winner
      // run is marked with a leading "* " on the name field (user 2026-07-13; a PREFIX so it
      // survives the in-game card's 30-char name truncation) - zero Lua/GSC board changes, the
      // row is still "round|text". (No schema change: the paradise_winner column + the whole
      // record->store->tag pipeline already shipped 2026-07-12.)
      // v2 clients get a third field: comma-joined "name:kills:downs:revives" records - the
      // exact shape of the game's acc_lb_stats dvar, so the Lua side parses both with ONE
      // gmatch. Names are belt-and-braces scrubbed of ':' here (cleanName leaves colons; the
      // GSC StrTok scrub already drops them, so stored rows should never have any).
      const statsField = r => statsOf(r)
        .map(s => `${String(s.name).replace(/[:,|]/g, " ").trim()}:${s.kills}:${s.downs}:${s.revives}`)
        .join(",");
      const lines = rows.map(r =>
        `${r.round}|${won(r) ? "* " : ""}${r.players}${v2 ? "|" + statsField(r) : ""}`
      );
      // v2 FOOTER (board totals line, 2026-07-15): "T|<games-played>|<paradise-wins>",
      // always LAST. The leading "T" can never collide with a data row (those start with
      // the round DIGITS), so every existing parser - the Lua chunk's "^(%d+)|" gmatch and
      // the GSC fallback - simply skips it; v2-only anyway, so old clients never see it.
      // It must stay the last line: the agent .bat's `echo ACCEOF_OK>>` glues the marker
      // onto whatever line is last, and the chunk strips the marker before parsing.
      if (v2 && totals) lines.push(`T|${totals.games}|${totals.wins}`);
      return txt(lines.join("\n"));
    }

    // ---- write: record a game ----------------------------------------------
    if (request.method === "POST" && path === "/games") {
      // shared-key gate (skipped if ACC_KEY not configured)
      if (env.ACC_KEY && request.headers.get("x-acc-key") !== env.ACC_KEY) {
        return jsonResp({ error: "unauthorized" }, 401);
      }

      // per-IP rate limit (best-effort; uses D1 so no extra binding needed)
      const ip = request.headers.get("cf-connecting-ip") || "0";
      try {
        const since = Math.floor(Date.now() / 1000) - RATE_WINDOW;
        const c = await env.DB.prepare(
          "SELECT COUNT(*) AS n FROM games WHERE ip = ? AND received_at > ?"
        ).bind(ip, since).first();
        if (c && c.n >= RATE_MAX) return jsonResp({ error: "rate" }, 429);
      } catch (e) { /* rate check is best-effort; never blocks on error */ }

      let body;
      try { body = await request.json(); } catch (e) { return jsonResp({ error: "bad json" }, 400); }
      // `null`, a number, a string, an array etc. are all valid JSON but not a game record;
      // guard before dereferencing so a body of literal `null` returns a clean 400 instead of a
      // TypeError -> bare 500 (the fetch handler has no outer try/catch). (review 2026-07-15)
      if (!body || typeof body !== "object" || Array.isArray(body)) {
        return jsonResp({ error: "invalid" }, 400);
      }

      const round = parseInt(body.round, 10);
      const session = String(body.session == null ? "" : body.session).replace(/[^\w.\-]/g, "").slice(0, 64);
      const ts = parseInt(body.ts, 10) || 0;
      const mapv = String(body.map_version == null ? "" : body.map_version).replace(/[^\w.\-]/g, "").slice(0, 24);
      let players = Array.isArray(body.players) ? body.players : [];
      // The roster ENTRY COUNT is load-bearing: the per-lobby-size ladder recovers the lobby size
      // from this CSV as (commas + 1) (see the /top10 whereCount comment), while the board ASKS for
      // its ladder with a client-side PlayerList SLOT count. Dropping an entry desyncs the two -
      // a quad with one unresolvable tag files under the TRIO ladder, where its own lobby (?v2=4)
      // never sees it. A present-but-unresolvable entry is a REAL player whose gamertag didn't
      // resolve, NOT an empty slot (empty slots are skipped client-side and never reach this
      // array), so cleanName()'s "?" is KEPT, never filtered: scrub the garbage NAME, never change
      // the COUNT (the 2026-07-14 data-repair lesson - those repaired rows carry "?" too). Only a
      // blank entry, which no shipped client emits, is dropped as marking no player at all.
      players = players.slice(0, 4).filter(p => String(p == null ? "" : p).trim() !== "").map(cleanName);

      if (!session || !(round >= 1 && round <= MAX_ROUND) || players.length === 0) {
        return jsonResp({ error: "invalid" }, 400);
      }
      const playersCsv = players.join(",");

      try {
        // dedup by session: multiple clients (co-op) may POST the same game;
        // keep the highest round seen for that session.
        await env.DB.prepare(
          `INSERT INTO games (session_id, round, players, client_ts, map_version, ip, received_at)
           VALUES (?, ?, ?, ?, ?, ?, unixepoch())
           ON CONFLICT(session_id) DO UPDATE SET
             round = MAX(games.round, excluded.round),
             players = excluded.players`
        ).bind(session, round, playersCsv, ts, mapv, ip).run();
      } catch (e) {
        return jsonResp({ error: "db" }, 500);
      }

      // ---- PARADISE WINNER tag (docs/40) -----------------------------------
      // Best-effort, OWN try/catch, AFTER the committed games row. Kept OUT of the
      // INSERT above so a not-yet-migrated column can never 500 the game record: if
      // the paradise_winner column is missing the UPDATE just throws and is swallowed
      // (worker deploy is order-independent from the ALTER - schema.sql migration note).
      // Set-once semantics: any co-op client reporting the win latches it to 1; a later
      // non-win re-POST for the same session never runs this branch, so it can't clear it.
      if (body.paradise_winner === true || body.paradise_winner === 1 || body.paradise_winner === "1") {
        try {
          await env.DB.prepare("UPDATE games SET paradise_winner = 1 WHERE session_id = ?").bind(session).run();
        } catch (e) { /* column not migrated yet - best effort, game row already committed */ }
      }

      // ---- anonymous gun-time telemetry (docs/41) --------------------------
      // OWN try/catch so a gun-insert failure (e.g. table not migrated) NEVER
      // rolls back / 500s the already-committed game row above.
      try {
        if (Array.isArray(body.guns) && body.guns.length) {
          const durationSecs = parseInt(body.duration_secs, 10) || 0;
          // budget uses the RAW roster size (1..4), not the name-sanitized players.length -
          // a junk-name player still contributes held-seconds, so the sanitized count could
          // wrongly reject a valid payload (low finding #1).
          const playerCount = Math.max(1, Math.min(4, Array.isArray(body.players) ? body.players.length : 1));
          const budget = durationSecs > 0 ? Math.ceil(durationSecs * playerCount * 1.1) : Infinity;

          // validate/clamp + fold-sum duplicate ids in the payload
          const byId = new Map();
          let total = 0;
          for (const g of body.guns.slice(0, MAX_GUNS)) {
            const id = parseInt(g && g.id, 10);
            let secs = parseInt(g && g.secs, 10);
            if (!(id >= 0 && id <= GUN_ID_MAX)) continue;
            if (!(secs >= 1)) continue;
            if (secs > GUN_SECS_MAX) secs = GUN_SECS_MAX;
            byId.set(id, (byId.get(id) || 0) + secs);
            total += secs;
          }

          // sanity clamp: reject the whole gun payload if the total exceeds what the
          // game duration x players could plausibly produce (the game row stays).
          if (byId.size && total <= budget) {
            const gameKey = await hashGameKey(session, env);
            const stmts = [];
            for (const [id, secs] of byId) {
              stmts.push(env.DB.prepare(
                `INSERT INTO gun_time (game_key, gun_id, seconds, end_round, players, map_version, received_at)
                 VALUES (?, ?, ?, ?, ?, ?, unixepoch())
                 ON CONFLICT(game_key, gun_id) DO UPDATE SET
                   seconds = MAX(gun_time.seconds, excluded.seconds),
                   end_round = MAX(gun_time.end_round, excluded.end_round),
                   players = excluded.players, map_version = excluded.map_version`
              ).bind(gameKey, id, Math.min(secs, GUN_SECS_MAX), round, playerCount, mapv));
            }
            await env.DB.batch(stmts);
          }
        }
      } catch (e) { /* gun telemetry is best-effort; the game row already committed */ }

      // ---- Tier-B box telemetry (docs/41 §3.7): per-gun offers/takes -----------
      // OWN try/catch (same isolation contract as gun_time). take_rate = takes/offers
      // is conditioned on the offer, so box availability cancels out - the
      // availability-FREE preference metric.
      try {
        if (Array.isArray(body.box) && body.box.length) {
          const playerCount = Math.max(1, Math.min(4, Array.isArray(body.players) ? body.players.length : 1));
          const byId = new Map();   // id -> {offers, takes}, fold-summed
          let totalOffers = 0;
          for (const b of body.box.slice(0, MAX_GUNS)) {
            const id = parseInt(b && b.id, 10);
            let offers = parseInt(b && b.offers, 10);
            let takes = parseInt(b && b.takes, 10);
            if (!(id >= 0 && id <= GUN_ID_MAX)) continue;
            if (!(offers >= 1)) continue;
            if (offers > BOX_OFFERS_MAX) offers = BOX_OFFERS_MAX;
            if (!(takes >= 0)) takes = 0;
            if (takes > offers) takes = offers;   // a take implies an offer
            const cur = byId.get(id) || { offers: 0, takes: 0 };
            cur.offers += offers; cur.takes += takes;
            byId.set(id, cur);
            totalOffers += offers;
          }
          // sanity clamp: a game can't plausibly roll the box more than this
          if (byId.size && totalOffers <= BOX_OFFERS_MAX) {
            const gameKey = await hashGameKey(session, env);
            const stmts = [];
            for (const [id, c] of byId) {
              stmts.push(env.DB.prepare(
                `INSERT INTO gun_box (game_key, gun_id, offers, takes, end_round, players, map_version, received_at)
                 VALUES (?, ?, ?, ?, ?, ?, ?, unixepoch())
                 ON CONFLICT(game_key, gun_id) DO UPDATE SET
                   offers = MAX(gun_box.offers, excluded.offers),
                   takes = MAX(gun_box.takes, excluded.takes),
                   end_round = MAX(gun_box.end_round, excluded.end_round),
                   players = excluded.players, map_version = excluded.map_version`
              ).bind(gameKey, id, c.offers, Math.min(c.takes, c.offers), round, playerCount, mapv));
            }
            await env.DB.batch(stmts);
          }
        }
      } catch (e) { /* box telemetry is best-effort; the game row already committed */ }

      // ---- Tier-C retention telemetry (docs/41 §3.9): per-gun acquires/replaced --------
      // OWN try/catch (same isolation contract as gun_time/gun_box). replace_rate =
      // replaced/acquires is conditioned on the acquisition, so availability cancels out -
      // the availability-FREE RETENTION metric (do players KEEP the gun once they have it,
      // or swap it away). The GSC sampler only counts a replace for a clean swap while the
      // player is alive + standing, so death/down/Mule losses never inflate it.
      try {
        if (Array.isArray(body.drop) && body.drop.length) {
          const playerCount = Math.max(1, Math.min(4, Array.isArray(body.players) ? body.players.length : 1));
          const byId = new Map();   // id -> {acquires, replaced}, fold-summed
          let totalAcq = 0;
          for (const d of body.drop.slice(0, MAX_GUNS)) {
            const id = parseInt(d && d.id, 10);
            let acq = parseInt(d && d.acq, 10);
            let rep = parseInt(d && d.rep, 10);
            if (!(id >= 0 && id <= GUN_ID_MAX)) continue;
            if (!(acq >= 1)) continue;
            if (acq > DROP_ACQ_MAX) acq = DROP_ACQ_MAX;
            if (!(rep >= 0)) rep = 0;
            if (rep > acq) rep = acq;   // a replace implies a prior acquire
            const cur = byId.get(id) || { acquires: 0, replaced: 0 };
            cur.acquires += acq; cur.replaced += rep;
            byId.set(id, cur);
            totalAcq += acq;
          }
          // sanity clamp: a game can't plausibly acquire guns more than this
          if (byId.size && totalAcq <= DROP_ACQ_MAX) {
            const gameKey = await hashGameKey(session, env);
            const stmts = [];
            for (const [id, c] of byId) {
              stmts.push(env.DB.prepare(
                `INSERT INTO gun_drop (game_key, gun_id, acquires, replaced, end_round, players, map_version, received_at)
                 VALUES (?, ?, ?, ?, ?, ?, ?, unixepoch())
                 ON CONFLICT(game_key, gun_id) DO UPDATE SET
                   acquires = MAX(gun_drop.acquires, excluded.acquires),
                   replaced = MAX(gun_drop.replaced, excluded.replaced),
                   end_round = MAX(gun_drop.end_round, excluded.end_round),
                   players = excluded.players, map_version = excluded.map_version`
              ).bind(gameKey, id, c.acquires, Math.min(c.replaced, c.acquires), round, playerCount, mapv));
            }
            await env.DB.batch(stmts);
          }
        }
      } catch (e) { /* retention telemetry is best-effort; the game row already committed */ }

      // ---- per-player kills/downs/revives (docs/40, NAMED) ---------------------
      // OWN try/catch (same isolation contract as the gun tables): a not-yet-migrated
      // player_stats table must never 500 the already-committed game row. Unlike the gun
      // telemetry this is named (stores the gamertag) - same posture as the games row.
      try {
        if (Array.isArray(body.stats) && body.stats.length) {
          const playerCount = Math.max(1, Math.min(4, Array.isArray(body.players) ? body.players.length : 1));
          const byName = new Map();   // name -> {kills, downs, revives}; keep the MAX per name in-payload
          for (const s of body.stats.slice(0, MAX_STAT_ROWS)) {
            const name = cleanName(s && s.name);
            if (name === "?") continue;   // unresolved/scrubbed-empty name -> skip
            let kills   = parseInt(s && s.kills, 10);
            let downs   = parseInt(s && s.downs, 10);
            let revives = parseInt(s && s.revives, 10);
            if (!(kills   >= 0)) kills = 0;
            if (!(downs   >= 0)) downs = 0;
            if (!(revives >= 0)) revives = 0;
            if (kills   > STAT_KILLS_MAX) kills   = STAT_KILLS_MAX;
            if (downs   > STAT_DR_MAX)    downs   = STAT_DR_MAX;
            if (revives > STAT_DR_MAX)    revives = STAT_DR_MAX;
            // a duplicate cleaned name in one payload (two same-tag players) -> keep the max
            const cur = byName.get(name) || { kills: 0, downs: 0, revives: 0 };
            cur.kills = Math.max(cur.kills, kills);
            cur.downs = Math.max(cur.downs, downs);
            cur.revives = Math.max(cur.revives, revives);
            byName.set(name, cur);
          }
          if (byName.size) {
            const stmts = [];
            for (const [name, c] of byName) {
              stmts.push(env.DB.prepare(
                `INSERT INTO player_stats (session_id, name, kills, downs, revives, end_round, players, map_version, received_at)
                 VALUES (?, ?, ?, ?, ?, ?, ?, ?, unixepoch())
                 ON CONFLICT(session_id, name) DO UPDATE SET
                   kills = MAX(player_stats.kills, excluded.kills),
                   downs = MAX(player_stats.downs, excluded.downs),
                   revives = MAX(player_stats.revives, excluded.revives),
                   end_round = MAX(player_stats.end_round, excluded.end_round),
                   players = excluded.players, map_version = excluded.map_version`
              ).bind(session, name, c.kills, c.downs, c.revives, round, playerCount, mapv));
            }
            await env.DB.batch(stmts);
          }
        }
      } catch (e) { /* per-player stats are best-effort; the game row already committed */ }

      return jsonResp({ ok: true });
    }

    // ---- read: gun usage stats (share % + pick rate + preference index) ------
    // Anonymous. Beyond raw held-time (which measures EXPOSURE - a gun the box
    // offers often racks up seconds without being preferred), this returns the
    // availability-ADJUSTED metrics from docs/41 §3.6 so the data reads honestly:
    //   pref_index   = share_pct / box_offer_share_pct  (>1 kept more than offered,
    //                  <1 offered-but-dropped; null for guns with no box offer path)
    //   secs_per_pick= total_seconds / games_picked     (stickiness per acquisition)
    //   take_rate    = box takes / box offers (Tier B)  (availability-FREE preference:
    //                  conditioned on the offer, so box odds cancel; null pre-Tier-B)
    //   replace_rate = replaced / acquires (Tier C)      (availability-FREE RETENTION: once
    //                  a player HAS the gun, do they keep it (0) or ditch it (1)? death/
    //                  down/Mule losses are excluded in GSC, so this is voluntary-only;
    //                  null pre-Tier-C. take_rate = do they WANT it; replace_rate = do they
    //                  KEEP it - orthogonal preference axes.)
    //   verdict      = over-performs | as-offered | under-performs | n/a
    // ?sort=seconds|share|pick|pref|secs_per_pick|take|replace (default seconds), ?limit, ?map_version.
    if (request.method === "GET" && (path === "/stats/guns.txt" || path === "/stats/guns.json")) {
      const mapv = url.searchParams.get("map_version");
      // floor at 1 (mirrors /top10 and /stats/players): without it a negative ?limit reaches
      // out.slice(0, limit) and drops rows from the END instead of returning the set. (review 2026-07-15)
      const limit = Math.min(Math.max(parseInt(url.searchParams.get("limit"), 10) || 100, 1), 200);
      const sort = url.searchParams.get("sort") || "seconds";
      const where = mapv ? "WHERE map_version = ?" : "";
      const bind = mapv ? [mapv] : [];
      let rows, denom;
      try {
        // No SQL LIMIT here: <=200 gun ids, so we fetch all, derive metrics, then
        // sort+slice in JS (SQL can only sort by total_seconds; pref/secs_per_pick
        // are computed values). Cheap at this cardinality.
        const res = await env.DB.prepare(
          `SELECT gun_id,
                  SUM(seconds) AS total_seconds,
                  COUNT(*) AS games_seen,
                  SUM(CASE WHEN seconds >= ${PICK_THRESHOLD} THEN 1 ELSE 0 END) AS games_picked
             FROM gun_time ${where}
            GROUP BY gun_id`
        ).bind(...bind).all();
        rows = res.results || [];
        // denominators: total held-time and total games that reported gun data
        // (NOT all games - so pre-feature games don't deflate pick rate, docs/41).
        denom = await env.DB.prepare(
          `SELECT SUM(seconds) AS all_seconds, COUNT(DISTINCT game_key) AS total_games FROM gun_time ${where}`
        ).bind(...bind).first();
      } catch (e) {
        return path.endsWith(".json") ? jsonResp({ error: "db" }, 500) : txt("", 500);
      }
      const allSecs = (denom && denom.all_seconds) || 0;
      const totalGames = (denom && denom.total_games) || 0;

      // Tier-B box offers/takes (docs/41 §3.7). OWN try/catch: a not-yet-migrated
      // gun_box table must never take down the whole stats endpoint - take_rate
      // fields just stay null. A gun with box rows but NO held rows (offered, always
      // walked away from) still gets an output row - that's pure box dead-weight,
      // exactly the signal this metric exists to expose.
      const boxAgg = new Map();   // gun_id -> {offers, takes}
      try {
        const bres = await env.DB.prepare(
          `SELECT gun_id, SUM(offers) AS offers, SUM(takes) AS takes FROM gun_box ${where} GROUP BY gun_id`
        ).bind(...bind).all();
        for (const b of (bres.results || [])) boxAgg.set(b.gun_id, { offers: b.offers, takes: b.takes });
      } catch (e) { /* table not migrated yet - take_rate stays null */ }

      // Tier-C retention (docs/41 §3.9). OWN try/catch: a not-yet-migrated gun_drop
      // table must never take down the endpoint - replace_rate fields just stay null.
      // A gun with drop rows but no held rows still gets a row (acquired then always
      // ditched = the retention signal this metric exists to expose).
      const dropAgg = new Map();   // gun_id -> {acquires, replaced}
      try {
        const dres = await env.DB.prepare(
          `SELECT gun_id, SUM(acquires) AS acquires, SUM(replaced) AS replaced FROM gun_drop ${where} GROUP BY gun_id`
        ).bind(...bind).all();
        for (const d of (dres.results || [])) dropAgg.set(d.gun_id, { acquires: d.acquires, replaced: d.replaced });
      } catch (e) { /* table not migrated yet - replace_rate stays null */ }

      // total box weight = the offer-share denominator (nominal full-pool odds).
      let totalWeight = 0;
      for (const k in GUN_BOX_WEIGHT) totalWeight += GUN_BOX_WEIGHT[k];

      const seenIds = new Set(rows.map(r => r.gun_id));
      for (const [id] of boxAgg) {
        if (!seenIds.has(id)) { rows.push({ gun_id: id, total_seconds: 0, games_seen: 0, games_picked: 0 }); seenIds.add(id); }
      }
      for (const [id] of dropAgg) {
        if (!seenIds.has(id)) { rows.push({ gun_id: id, total_seconds: 0, games_seen: 0, games_picked: 0 }); seenIds.add(id); }
      }

      let out = rows.map(r => {
        const share = allSecs > 0 ? (r.total_seconds / allSecs) * 100 : 0;
        const pick = totalGames > 0 ? r.games_picked / totalGames : 0;
        const w = GUN_BOX_WEIGHT[r.gun_id];
        const boxShare = (w != null && totalWeight > 0) ? (w / totalWeight) * 100 : null;
        // pref_index only defined for guns with a box offer path AND some offer share.
        const prefIndex = (boxShare && boxShare > 0) ? share / boxShare : null;
        const secsPerPick = r.games_picked > 0 ? r.total_seconds / r.games_picked : 0;
        const isStarting = GUN_STARTING.has(r.gun_id);
        const box = boxAgg.get(r.gun_id);
        const takeRate = (box && box.offers > 0) ? box.takes / box.offers : null;
        // Tier-C retention: replace_rate = replaced/acquires (0 = always kept, 1 = always
        // ditched). replaced is re-clamped <= acquires here in case a MAX-merge upsert ever
        // stored them from different re-POSTs.
        const drop = dropAgg.get(r.gun_id);
        const dropRep = drop ? Math.min(drop.replaced, drop.acquires) : null;
        const replaceRate = (drop && drop.acquires > 0) ? dropRep / drop.acquires : null;
        let verdict;
        if (prefIndex == null) verdict = "n/a";
        else if (isStarting) verdict = "starting";   // pref_index confounded by the free grant
        else if (prefIndex >= 1.3) verdict = "over-performs";
        else if (prefIndex <= 0.6) verdict = "under-performs";
        else verdict = "as-offered";
        return {
          id: r.gun_id,
          name: (GUN_IDS.ids && GUN_IDS.ids[r.gun_id]) || String(r.gun_id),
          total_seconds: r.total_seconds,
          share_pct: +share.toFixed(2),
          pick_rate: +pick.toFixed(4),
          games_seen: r.games_seen,
          games_picked: r.games_picked,
          box_share_pct: boxShare == null ? null : +boxShare.toFixed(2),
          pref_index: prefIndex == null ? null : +prefIndex.toFixed(2),
          secs_per_pick: +secsPerPick.toFixed(1),
          box_offers: box ? box.offers : null,
          box_takes: box ? box.takes : null,
          take_rate: takeRate == null ? null : +takeRate.toFixed(4),
          acquires: drop ? drop.acquires : null,
          replaced: dropRep,
          replace_rate: replaceRate == null ? null : +replaceRate.toFixed(4),
          is_starting: isStarting,
          verdict,
        };
      });

      // sort: computed keys sort nulls last; default keeps the old total_seconds order.
      const KEYS = { seconds: "total_seconds", share: "share_pct", pick: "pick_rate",
                     pref: "pref_index", secs_per_pick: "secs_per_pick", take: "take_rate",
                     replace: "replace_rate" };
      const key = KEYS[sort] || "total_seconds";
      out.sort((a, b) => {
        const av = a[key], bv = b[key];
        if (av == null && bv == null) return b.total_seconds - a.total_seconds;
        if (av == null) return 1;
        if (bv == null) return -1;
        return bv - av;
      });
      out = out.slice(0, limit);

      if (path.endsWith(".json")) {
        return jsonResp({ total_games: totalGames, all_seconds: allSecs, sort, guns: out });
      }
      // plain text (Lua-friendly): id|total_seconds|share_pct|pick_rate|games_seen|pref_index|secs_per_pick|verdict|take_rate|replace_rate
      // (pref_index/take_rate/replace_rate empty when null). Appended columns are backward-
      // compatible - older parsers that split on the first N fields keep working.
      return txt(out.map(g =>
        `${g.id}|${g.total_seconds}|${g.share_pct}|${g.pick_rate}|${g.games_seen}|${g.pref_index == null ? "" : g.pref_index}|${g.secs_per_pick}|${g.verdict}|${g.take_rate == null ? "" : g.take_rate}|${g.replace_rate == null ? "" : g.replace_rate}`
      ).join("\n"));
    }

    // ---- read: per-player stats (kills/downs/revives) ------------------------
    // NAMED (not anonymous): aggregates the player_stats rows per gamertag across all
    // games. Returns per-player totals + best round + games played. ?sort=kills|downs|
    // revives|kpg|games|best_round (default kills), ?limit, ?map_version. Degrades to an
    // empty list if the table isn't migrated yet (endpoint never 500s on a fresh DB).
    if (request.method === "GET" && (path === "/stats/players.txt" || path === "/stats/players.json")) {
      const mapv = url.searchParams.get("map_version");
      const limit = Math.min(Math.max(parseInt(url.searchParams.get("limit"), 10) || 100, 1), 500);
      const sort = url.searchParams.get("sort") || "kills";
      const where = mapv ? "WHERE map_version = ?" : "";
      const bind = mapv ? [mapv] : [];
      let rows = [];
      try {
        const res = await env.DB.prepare(
          `SELECT name,
                  SUM(kills)   AS kills,
                  SUM(downs)   AS downs,
                  SUM(revives) AS revives,
                  COUNT(*)     AS games,
                  MAX(end_round) AS best_round
             FROM player_stats ${where}
            GROUP BY name`
        ).bind(...bind).all();
        rows = res.results || [];
      } catch (e) {
        // table not migrated yet -> empty result, not an error (mirrors the graceful
        // degradation of the paradise_winner column + gun tables).
        rows = [];
      }

      let out = rows.map(r => {
        const kills = r.kills || 0, games = r.games || 0;
        return {
          name: r.name,
          kills,
          downs: r.downs || 0,
          revives: r.revives || 0,
          games,
          best_round: r.best_round || 0,
          kills_per_game: games > 0 ? +(kills / games).toFixed(1) : 0,
        };
      });

      const KEYS = { kills: "kills", downs: "downs", revives: "revives",
                     kpg: "kills_per_game", games: "games", best_round: "best_round" };
      const key = KEYS[sort] || "kills";
      out.sort((a, b) => (b[key] - a[key]) || (b.kills - a.kills));
      out = out.slice(0, limit);

      if (path.endsWith(".json")) {
        return jsonResp({ sort, players: out });
      }
      // plain text (Lua-friendly): name|kills|downs|revives|games|best_round|kills_per_game
      return txt(out.map(p =>
        `${p.name}|${p.kills}|${p.downs}|${p.revives}|${p.games}|${p.best_round}|${p.kills_per_game}`
      ).join("\n"));
    }

    // ---- admin: dedupe split-session games (cleanup, 2026-07-18) -------------
    // session_id is the games PRIMARY KEY, so literal duplicates cannot exist - what CAN
    // exist is the SAME GAME under TWO ids: the rec chunk reuses the id parked on the
    // acc_lb_session dvar, and a transient dvar-read hiccup mid-match mints a fresh one,
    // splitting one run into two rows (per-round posting multiplies the chances; the GSC
    // now re-asserts the dvar each record, so this mainly cleans HISTORIC splits).
    //
    // Gated on env.ADMIN_KEY - a SEPARATE secret that never ships in the game (ACC_KEY is
    // extractable from the fastfile, so it must never authorize deletes). Unset -> 404,
    // the endpoint effectively does not exist. Set via `wrangler secret put ADMIN_KEY` or
    // the dashboard Variables page.
    //
    // POST /admin/dedupe  body: { apply?: bool, sessions?: string[], gap_hours?: number }
    //   default      - REPORT ONLY: candidate clusters + per-cluster verdict, no writes.
    //   apply: true  - merge only clusters verdict "mergeable" (see below): keeper = the
    //                  max-round row (tie: earliest received_at); losers' player_stats
    //                  MAX-merge into the keeper, paradise_winner ORs in, losers deleted.
    //   sessions:[…] - explicit manual override: delete exactly these session ids (+ their
    //                  player_stats), no heuristics. Use after reviewing a report.
    //
    // Detection is deliberately CONSERVATIVE - the same crew playing two real back-to-back
    // games looks a lot like a split. A cluster = same EXACT players CSV (fragments of one
    // match keep the same PlayerList order) with client_ts gaps <= gap_hours (default 3).
    // Verdict "mergeable" additionally requires every consecutive pair to look like a
    // CONTINUATION: round never decreases AND every shared player's kills/downs/revives is
    // component-wise >= (stock counters only grow within one match; a real new game resets
    // them to ~0). Anything else stays "suspect" - reported for a human, never auto-merged.
    // The anonymous gun_* tables are NOT touched: game_key is an HMAC of the session
    // (deliberately unjoinable), so a split's gun rows stay as small aggregate noise.
    if (request.method === "POST" && path === "/admin/dedupe") {
      if (!env.ADMIN_KEY) return jsonResp({ error: "not found" }, 404);
      if (request.headers.get("x-admin-key") !== env.ADMIN_KEY) {
        return jsonResp({ error: "unauthorized" }, 401);
      }

      let body;
      try { body = await request.json(); } catch (e) { body = {}; }
      if (!body || typeof body !== "object" || Array.isArray(body)) body = {};
      const apply = body.apply === true;
      const gapSecs = (parseFloat(body.gap_hours) > 0 ? parseFloat(body.gap_hours) : 3) * 3600;

      // Explicit manual delete list - no heuristics, exact ids only.
      if (Array.isArray(body.sessions) && body.sessions.length) {
        const ids = body.sessions.map(s => String(s == null ? "" : s).replace(/[^\w.\-]/g, "").slice(0, 64)).filter(s => s !== "");
        if (!ids.length) return jsonResp({ error: "invalid" }, 400);
        if (!apply) return jsonResp({ mode: "sessions-dry-run", would_delete: ids });
        try {
          const stmts = [];
          for (const id of ids) {
            stmts.push(env.DB.prepare("DELETE FROM player_stats WHERE session_id = ?").bind(id));
            stmts.push(env.DB.prepare("DELETE FROM games WHERE session_id = ?").bind(id));
          }
          await env.DB.batch(stmts);
        } catch (e) { return jsonResp({ error: "db" }, 500); }
        return jsonResp({ mode: "sessions", deleted: ids });
      }

      // Heuristic detection. The games table is small (hundreds of rows) - fetch it all.
      let games;
      try {
        const res = await env.DB.prepare(
          "SELECT session_id, round, players, client_ts, received_at, paradise_winner FROM games ORDER BY players, client_ts ASC"
        ).all();
        games = res.results || [];
      } catch (e) { return jsonResp({ error: "db" }, 500); }

      // cluster: same exact roster CSV, consecutive client_ts gaps <= gapSecs
      const clusters = [];
      let cur = null;
      for (const g of games) {
        if (cur && cur.players === g.players && (g.client_ts || 0) - cur.lastTs <= gapSecs) {
          cur.rows.push(g);
          cur.lastTs = g.client_ts || 0;
        } else {
          cur = { players: g.players, lastTs: g.client_ts || 0, rows: [g] };
          clusters.push(cur);
        }
      }
      const candidates = clusters.filter(c => c.rows.length >= 2);

      // stats for the continuation check (statsBySession: session -> {name: {k,d,r}})
      const statsBySession = new Map();
      try {
        const ids = candidates.flatMap(c => c.rows.map(r => r.session_id));
        for (let i = 0; i < ids.length; i += 50) {   // chunk the IN() well under D1's bind limit
          const slice = ids.slice(i, i + 50);
          const ph = slice.map(() => "?").join(",");
          const sres = await env.DB.prepare(
            `SELECT session_id, name, kills, downs, revives FROM player_stats WHERE session_id IN (${ph})`
          ).bind(...slice).all();
          for (const s of (sres.results || [])) {
            if (!statsBySession.has(s.session_id)) statsBySession.set(s.session_id, {});
            statsBySession.get(s.session_id)[s.name] = { k: s.kills || 0, d: s.downs || 0, r: s.revives || 0 };
          }
        }
      } catch (e) { /* stats table missing -> no cluster can verify continuation -> all stay "suspect" */ }

      // continuation: rounds never decrease AND all shared players' stats component-wise grow
      const looksLikeContinuation = (a, b) => {
        if ((b.round || 0) < (a.round || 0)) return false;
        const sa = statsBySession.get(a.session_id), sb = statsBySession.get(b.session_id);
        if (!sa || !sb) return false;   // can't verify -> not mergeable (conservative)
        let shared = 0;
        for (const name in sa) {
          if (!sb[name]) continue;
          shared++;
          if (sb[name].k < sa[name].k || sb[name].d < sa[name].d || sb[name].r < sa[name].r) return false;
        }
        return shared > 0;
      };

      const report = [];
      const actions = [];
      for (const c of candidates) {
        const rows = c.rows;
        let mergeable = true;
        for (let i = 1; i < rows.length; i++) {
          if (!looksLikeContinuation(rows[i - 1], rows[i])) { mergeable = false; break; }
        }
        // keeper = max round; tie -> earliest received_at
        const keeper = rows.slice().sort((a, b) => (b.round - a.round) || (a.received_at - b.received_at))[0];
        const losers = rows.filter(r => r.session_id !== keeper.session_id);
        report.push({
          verdict: mergeable ? "mergeable" : "suspect",
          players: c.players,
          keeper: keeper.session_id,
          rows: rows.map(r => ({ session: r.session_id, round: r.round, ts: r.client_ts, received: r.received_at, paradise: !!r.paradise_winner })),
        });
        if (mergeable && apply) actions.push({ keeper, losers });
      }

      if (!apply) return jsonResp({ mode: "report", gap_hours: gapSecs / 3600, clusters: report });

      let merged = 0, deleted = 0;
      try {
        for (const act of actions) {
          const stmts = [];
          for (const loser of act.losers) {
            // MAX-merge the loser's per-player stats into the keeper's rows, then delete
            stmts.push(env.DB.prepare(
              `INSERT INTO player_stats (session_id, name, kills, downs, revives, end_round, players, map_version, received_at)
               SELECT ?, name, kills, downs, revives, end_round, players, map_version, received_at
                 FROM player_stats WHERE session_id = ?
               ON CONFLICT(session_id, name) DO UPDATE SET
                 kills = MAX(player_stats.kills, excluded.kills),
                 downs = MAX(player_stats.downs, excluded.downs),
                 revives = MAX(player_stats.revives, excluded.revives),
                 end_round = MAX(player_stats.end_round, excluded.end_round)`
            ).bind(act.keeper.session_id, loser.session_id));
            stmts.push(env.DB.prepare("DELETE FROM player_stats WHERE session_id = ?").bind(loser.session_id));
            if (loser.paradise_winner) {
              stmts.push(env.DB.prepare("UPDATE games SET paradise_winner = 1 WHERE session_id = ?").bind(act.keeper.session_id));
            }
            stmts.push(env.DB.prepare("DELETE FROM games WHERE session_id = ?").bind(loser.session_id));
            deleted++;
          }
          if (stmts.length) { await env.DB.batch(stmts); merged++; }
        }
      } catch (e) { return jsonResp({ error: "db", merged, deleted }, 500); }
      return jsonResp({ mode: "apply", clusters_merged: merged, rows_deleted: deleted, clusters: report });
    }

    return jsonResp({ error: "not found" }, 404);
  }
};
