-- acc_lb_rec.lua - GENERATED by tools/build_lb_lui.js - DO NOT EDIT BY HAND.
-- Source of truth: tools/lui_chunks/acc_lb_rec_chunk.lua (the io/os logic, hksc-compiled
-- into the BC string below) + tools/lui_chunks/acc_lb_rec_outer.tpl.lua (this shell).
--
-- LEADERBOARD RECORDER (docs/40): _acc_leaderboard.gsc opens this menu ONCE, on the
-- recording client, at end_game - never in dev/god runs. createMenu undumps the
-- bytecode via load(reader) (THE WORKING RECIPE - HKS load is 5.1-strict + bytecode-
-- only) and runs it: roster + round from UI models, local record append, curl POST.
-- This OUTER file is normal L3akMod-compiled source and must stay whitelist-clean:
-- never name io/os/_G/getfenv/loadstring here (docs/19 L3akMod global whitelist).

local BC = "@@ACC_LUI_BYTECODE@@"

local function runChunk(mode, ctrl)
	local served = false
	local ok, f = pcall(load, function()
		if served then return nil end
		served = true
		return BC
	end)
	if ok ~= true or type(f) ~= "function" then return nil end
	local okR, res = pcall(f, mode, ctrl)
	if okR ~= true then return nil end
	return res
end

function LUI.createMenu.acc_lb_rec(InstanceRef)
	local Hud = CoD.Menu.NewForUIEditor("acc_lb_rec")
	Hud:setOwner(InstanceRef)
	Hud:setLeftRight(true, true, 0, 0)
	Hud:setTopBottom(true, true, 0, 0)

	-- Record + POST, blocking (we are on the game-over screen; the chunk caps curl at
	-- 6s). InstanceRef doubles as the controller for the UI-model reads (acc_hud.lua
	-- passes it to Engine.GetModelForController the same way).
	runChunk("rec", InstanceRef)

	return Hud
end
