-- acc_lb_boot.lua - GENERATED by tools/build_lb_lui.js - DO NOT EDIT BY HAND.
-- Source of truth: tools/lui_chunks/acc_lb_boot_chunk.lua (+ this shell).
--
-- LEADERBOARD AGENT BOOT (docs/40): _acc_leaderboard.gsc opens this ONCE per match
-- at initial_blackscreen_passed (proven-safe timing + client LUI ready). createMenu
-- SYNCHRONOUSLY writes + spawns the hidden curl agent - the ONLY process spawn in
-- the whole system. NO UITimer (a UITimer-driven spawn froze the engine, 2026-07-12).
-- This OUTER file must stay whitelist-clean: never name io/os/_G/getfenv/loadstring
-- here (docs/19 L3akMod global whitelist).

local BC = "@@ACC_LUI_BYTECODE@@"

local function runChunk(mode, ctrl)
	local served = false
	local ok, f = pcall(load, function()
		if served then return nil end
		served = true
		return BC
	end)
	if ok ~= true or type(f) ~= "function" then return nil end
	local okR, res = pcall(f, mode, ctrl)
	if okR ~= true then return nil end
	return res
end

function LUI.createMenu.acc_lb_boot(InstanceRef)
	local Hud = CoD.Menu.NewForUIEditor("acc_lb_boot")
	Hud:setOwner(InstanceRef)
	Hud:setLeftRight(true, true, 0, 0)
	Hud:setTopBottom(true, true, 0, 0)

	runChunk("boot", InstanceRef)

	return Hud
end
