-- acc_lb_board.lua - GENERATED by tools/build_lb_lui.js - DO NOT EDIT BY HAND.
-- Source of truth: tools/lui_chunks/acc_lb_board_chunk.lua (the io/os fetch logic,
-- hksc-compiled into the BC string below) + acc_lb_board_outer.tpl.lua (this shell).
--
-- LEADERBOARD FETCHER (docs/40): _acc_leaderboard.gsc opens this menu when a player
-- uses the Plaza station (and for the dev fetch probe). It draws NOTHING - it fires a
-- background curl GET ("go"), then a 400ms UITimer polls the result file ("read")
-- until the rows land in dvars acc_lb_r1..r10 + acc_lb_done, falling back to the
-- machine-local records ("local") if the net fetch errors or times out. GSC renders
-- the card and closes the menu. Timer hygiene per memory lui-uitimer-leaks-state-pool:
-- one handle, closed inside its own handler on every exit path.
-- This OUTER file must stay whitelist-clean: never name io/os/_G/getfenv/loadstring
-- here (docs/19 L3akMod global whitelist).

local BC = "@@ACC_LUI_BYTECODE@@"

local function runChunk(mode, ctrl)
	local served = false
	local ok, f = pcall(load, function()
		if served then return nil end
		served = true
		return BC
	end)
	if ok ~= true or type(f) ~= "function" then return nil end
	local okR, res = pcall(f, mode, ctrl)
	if okR ~= true then return nil end
	return res
end

function LUI.createMenu.acc_lb_board(InstanceRef)
	local Hud = CoD.Menu.NewForUIEditor("acc_lb_board")
	Hud:setOwner(InstanceRef)
	Hud:setLeftRight(true, true, 0, 0)
	Hud:setTopBottom(true, true, 0, 0)

	runChunk("go", InstanceRef)

	local ticks = 0
	if Hud.accLbTimer then Hud.accLbTimer:close() end
	Hud.accLbTimer = LUI.UITimer.new(400, "acc_lb_tick", false)
	Hud:addElement(Hud.accLbTimer)
	Hud:registerEventHandler("acc_lb_tick", function(element, event)
		ticks = ticks + 1
		local res = runChunk("read", InstanceRef)
		-- ~20 ticks x 400ms = 8s net budget (agent poll ~1s + curl -m 5)
		if res == "done" or res == "neterr" or ticks >= 20 then
			if res ~= "done" then runChunk("local", InstanceRef) end
			if element.accLbTimer then
				element.accLbTimer:close()
				element.accLbTimer = nil
			end
		end
	end)

	return Hud
end
