-- acc_lb_boot_chunk.lua - INNER bytecode chunk: spawn the LEADERBOARD AGENT (docs/40).
--
-- THE FULLSCREEN TAB-OUT FIX (user 2026-07-11): os.execute from LUI spawns a
-- console window that yanks exclusive fullscreen (the reported interact/game-end
-- tab-out). So the game execs ONCE per match at map load - here - and from then
-- on the rec/board chunks only WRITE TRIGGER FILES (pure io, no process) that this
-- agent serves off-process. The agent (players\acc_lb_agent_<tok>.bat) polls ~1s
-- for ~2h then self-deletes:
--   players\acc_lb_do_post.txt -> curl POST acc_lb_post.json -> acc_lb_post_result.txt
--   players\acc_lb_do_get.txt  -> curl GET top10 -> acc_lb_top10.txt + ACCEOF marker
--   players\acc_lb_ping.txt    -> del + echo pong>acc_lb_pong.txt  (liveness; the
--                                 launcher pre-spawn uses this so it can skip a
--                                 duplicate - see run_game.ps1)
--
-- KNOWN-SAFE SHAPE (do not "improve" without an in-game load test): all io/os work
-- happens SYNCHRONOUSLY in createMenu. A prior attempt polled a liveness handshake
-- from a LUI UITimer and FROZE THE ENGINE the frame it exec'd inside the timer
-- handler (2026-07-12, two clean loads hung) - never os.execute from a UITimer
-- callback. Duplicate agents (one per match) are benign: POSTs dedup by session,
-- agents self-expire. NEVER overwrite a RUNNING .bat (cmd re-reads it from disk) ->
-- per-boot token filename. `ping -n 2` = the ~1s batch sleep (timeout needs stdin).

local mode, ctrl = ...

local URL = "@@ACC_LB_URL@@"
local KEY = "@@ACC_LB_KEY@@"

local function X(cmd)
	pcall(function() Engine.Exec(Engine.GetLocalClientNum(), cmd) end)
end

pcall(EnableGlobals)

if URL == "" then
	X('set acc_lb_boot_trace "no_url"')
	pcall(DisableGlobals)
	return "no_url"
end

-- unique per-boot filename (table-address entropy; os.time is an e-notation float
-- on HKS - docs/40)
local tok = ""
pcall(function() tok = string.sub(string.gsub(tostring({}), "%W", ""), -6) end)
if tok == "" then tok = "A" end
local bat = "players/acc_lb_agent_" .. tok .. ".bat"

-- clear stale request triggers so a fresh agent doesn't re-fire old work
pcall(function() os.remove("players/acc_lb_do_post.txt") end)
pcall(function() os.remove("players/acc_lb_do_get.txt") end)

local lines = {
	"@echo off",
	"rem ACC leaderboard agent - generated by the game at boot (docs/40).",
	"rem Runs curl OFF the game process so play never spawns a console window.",
	'cd /d "%~dp0"',
	"for /l %%i in (1,1,7200) do (",
	"  if exist acc_lb_ping.txt (",
	"    del acc_lb_ping.txt >nul 2>&1",
	"    echo pong>acc_lb_pong.txt",
	"  )",
	"  if exist acc_lb_do_post.txt (",
	"    del acc_lb_do_post.txt >nul 2>&1",
	'    curl.exe -s -m 6 -X POST -H "content-type: application/json" -H "x-acc-key: ' .. KEY .. '" --data @acc_lb_post.json -o acc_lb_post_result.txt ' .. URL .. '/games',
	"  )",
	"  if exist acc_lb_do_get.txt (",
	"    del acc_lb_do_get.txt >nul 2>&1",
	"    curl.exe -s -m 5 -o acc_lb_top10.txt " .. URL .. "/top10.txt && echo ACCEOF_OK>>acc_lb_top10.txt || echo ACCEOF_ERR>>acc_lb_top10.txt",
	"  )",
	"  ping -n 2 127.0.0.1 >nul",
	")",
	'del "%~f0"',
}
local okW = pcall(function()
	local f = io.open(bat, "w")
	local s = ""
	for i = 1, #lines do s = s .. lines[i] .. "\r\n" end
	f:write(s)
	f:close()
end)
if not okW then
	X('set acc_lb_boot_trace "wfail"')
	pcall(DisableGlobals)
	return "spawnfail"
end

local batWin = string.gsub(bat, "/", "\\")
-- /min, NOT /b: with /b the agent SHARES the console os.execute creates, keeping a
-- terminal window on top of the game for the agent's whole life (the user-reported
-- "starts up my terminal every time"). /min gives the agent its own MINIMIZED
-- console (a taskbar item only). Launcher users never even get this - their play
-- scripts pre-spawn the agent fully hidden and set acc_lb_agent 1 so this whole
-- chunk never runs (tools/spawn_lb_agent.ps1).
local okX = pcall(function() os.execute('start "" /min "' .. batWin .. '"') end)
X('set acc_lb_boot_trace "spawn' .. (okX and "1" or "0") .. '"')

pcall(DisableGlobals)
return "spawned"
