// =============================================================================
// _acc_weapon_variants.gsc - perk/ability weapon-variant SWAP framework
//
// Design reference: docs/perk_abilities.md (Deadshot §7, Double Tap §4),
// docs/30_perk_gdt_radiant_spec.md, docs/31_ape_perk_gdt_walkthrough.md §4-5,
// docs/05_weapons.md (Stabilizer weapon ability).
//
// THE PROBLEM (verified 2026-06-14 audit): recoil and fire rate are baked
// weapon-GDT properties. The engine exposes NO per-player recoil or fire-rate
// setter on a live weapon (grep-proven: zero Set*FireRate / Set*Recoil builtins,
// zero fire-rate dvar; those fields are read-only). The only way to give a player
// reduced-recoil or faster-firing guns is to SWAP the weapon for a cloned twin
// whose GDT SCALES the recoil tables / lowers fireTime, then swap the base back
// when the perk/ability ends. This module is that swap engine.
//
// WHAT IT DELIVERS (the real perk magnitudes - docs/perk_abilities.md), as
// independent twin AXES (one weapon-stat effect each, cross-producted per gun):
//   - Deadshot (any owner):       -25% recoil -> "recoil25" twin (gunKick*/viewKick* x0.75 of 2.1x base)
//   - Deadshot Mega (Am. Sniper): -40% recoil -> "recoil40" twin (x0.60)
//   - Double Tap Mega (Gun Slinger): +40% RoF + -50% swap -> "fastfire" twin (fireTime x0.714, raise/drop x0.5)
//     (base Double Tap KEEPS the stock 2.0 extra-bullet ~2x dmg; the Mega only adds fire rate + swap)
//   - Speed Cola Mega (Sleight Expert): +75% reload -> "fastreload" twin (reloadTime x0.857, on top of engine +50%)
//   - Mule Kick Mega (The Armory): +25% reserve ammo -> "ammo" twin (maxAmmo/startAmmo x1.25)
//   (Deadshot base +1.5 / Mega +2 headshot and DT base +33% RoF are NOT here -
//    headshot is _acc_damage; the +33% is engine-granted free off the specialty.)
//
// BAKED + ACTIVE (2026-06-14): the full 230-twin matrix is generated by
// tools/apply_recoil_overhaul.js into source_data/acc_weapon_variants.gdt, listed in
// the zone (weaponfull,*) AND in build_available_twins(), with dvar default
// `acc_weapon_variants 1`. To ADD a new effect axis, see the EXTENSION POINT banner
// below. Safety net: the allow-list gates GetWeapon so an un-baked combo can never
// throw; on a gun/combo with no twin, the axis no-ops (gun stays on its base form).
//
// PERK-GATED (unlike a flat GDT cap bump): the twin is only ever given to a
// player while they hold the qualifying perk (or fire the timed ability), and is
// stripped the instant they lose it. State is derived LIVE from the perk each
// reconcile, so it survives the death/re-buy cycle (Mega flag is sticky).
// =============================================================================

#using scripts\shared\array_shared;
#using scripts\shared\util_shared;

#insert scripts\shared\shared.gsh;

#using scripts\zm\_zm_weapons;

#using scripts\zm\zm_abandoned_cyber_city\_acc_utility;

// Default ON (2026-06-14): the recoil twins are baked + the 2.1x-base skill theme
// is a core feature, so the system runs by default. Set dvar `acc_weapon_variants 0`
// to disable. `acc_variants_debug 1` prints each swap to the player (proof-of-life).
#define ACC_VARIANTS_DEFAULT 1

// NOTE: Pack-a-Punch now packs the held gun IN PLACE via _acc_pap_levels (instant swap to
// the packed form, twin or base alike) - there is NO machine animation and NO proximity
// suppression. The gun changes ONLY when you actually pack, so this module no longer has to
// revert twins to base near the machine. packed_form() (below) is the only PaP hook here.

#namespace acc_weapon_variants;

// ---------------------------------------------------------------------------
// Init
// ---------------------------------------------------------------------------

function init()
{
    acc_utility::log( "weapon_variants init (inert until twins baked + acc_weapon_variants 1)" );

    // Known twin suffixes, LONGEST FIRST (logical_stem_name strips a trailing one
    // to recover the player's logical weapon). Legal combos = {recoil25|recoil40}
    // x {optional fastfire} - recoil25/recoil40 never co-occur (one Deadshot tier
    // or none). recoil25 = base Deadshot -25%; recoil40 = Mega -40% (off the 2.1x
    // base). fastfire/combined arrive in Phase 2 (Gun Slinger); listed now so the
    // stem-stripper is forward-safe (harmless until those twins exist).
    // Trailing variant-suffix strip list for logical_stem_name() - every legal
    // token combination ("_acc_<tok>...", all axes), built from the dims so it stays
    // in sync. Forward-safe: listing a combo whose twin isn't baked yet is harmless.
    level.acc_variant_suffixes = build_variant_suffixes();

    // Variant AXES in CANONICAL ORDER (= the order tokens appear in a twin name) -
    // MUST match tools/apply_recoil_overhaul.js TWIN_DIMS order. Each is a
    // function(self=player) returning its active token or undefined.
    // >>> ADD A NEW PERK/ABILITY EFFECT by appending its axis here (and a matching
    // dim in variant_dims() + the built combos in build_available_twins). See the
    // "EXTENSION POINT" banner above the axis functions. <<<
    level.acc_variant_axes = array( &axis_recoil, &axis_fire, &axis_reload, &axis_ammo );

    // Allow-list of twin weapon names that ACTUALLY EXIST in the build. We only
    // ever GetWeapon() a name in here, so an un-baked twin cannot throw. POPULATE
    // this as you bake twins in APE (docs/31 §4-5). Empty = whole system inert.
    level.acc_variant_available = build_available_twins();

    // Make the PaP'd ("_up") twins first-class engine UPGRADES so the Pack-a-Punch
    // HUD / tier-up / re-pack all recognize a held twin (fixes "PaP indicator breaks").
    register_twin_upgrades();
}

// Register every PaP'd ("_up") twin in level.zombie_weapons_upgraded (twin OBJECT ->
// true-base OBJECT) - the exact table stock add_zombie_weapon writes (_zm_weapons.gsc:554).
// Result: is_weapon_upgraded(_up twin) = true and get_base_weapon(_up twin) = base
// NATIVELY, so _acc_pap_levels + the stock PaP machine read a held _up twin correctly.
//
// ONLY the _up twins are registered - the un-PaP'd base twins (recoil25/recoil40 with NO
// _up) must stay un-upgraded, or the FIRST pack would skip tier 1 + camo. We never add
// twins to level.zombie_weapons / zombie_include_weapons, so the Mystery Box can't roll them.
function register_twin_upgrades()
{
    if ( !isdefined( level.zombie_weapons_upgraded ) ) level.zombie_weapons_upgraded = [];

    keys = getarraykeys( level.acc_variant_available );
    n = 0;
    for ( i = 0; i < keys.size; i++ )
    {
        name = keys[ i ];
        tw = GetWeapon( name );
        if ( !isdefined( tw ) || tw == level.weaponNone ) continue;

        stem_w = GetWeapon( logical_stem_name( name ) );   // strip _acc -> base or _up form
        if ( !isdefined( stem_w ) || stem_w == level.weaponNone ) continue;

        // Only PaP'd twins are "upgrades": a base twin's stem is the un-upgraded base.
        if ( !( zm_weapons::is_weapon_upgraded( stem_w ) ) ) continue;

        level.zombie_weapons_upgraded[ tw ] = zm_weapons::get_base_weapon( stem_w );
        n++;
    }
    acc_utility::log( "weapon_variants: registered " + n + " _up twins as engine upgrades" );
}

// The guns that have twins (imported box guns only - stock guns have no editable
// GDT). On any other gun the perk no-ops (reconcile finds no twin -> stays on base).
// NOTE: s1_tac19 also carries an always-on baseline buff (small range x1.5 + FMJ penetrateType
// large + wider spread x1.25, traded for -15% damage) baked into its base/_up GDT
// (tools/apply_recoil_overhaul.js GUNS.baseline), so its base AND every twin have it. That's a
// GDT-only change; the swap engine here is unaffected (base <-> twin still differ only by
// recoil/fire/reload).
function variant_guns()
{
    // +3 twin guns REVERTED again 2026-06-15: 368 twins (8 guns) crash on boot - BO3
    // weapon-count limit. 230 (5 guns) boots. Need a twin budget to re-add the new guns.
    return array( "s1_tac19", "s1_asm1", "t6_fiveseven", "t6_ak47", "s1_ae4" );
}

// Variant DIMENSIONS = the token level(s) per axis, CANONICAL ORDER. ONE source of
// truth, shared by build_variant_suffixes (strip list) and the available-combo menu.
// MUST mirror tools/apply_recoil_overhaul.js TWIN_DIMS order. The "axis inactive"
// level (no token) is implied; list only the real tokens.
function variant_dims()
{
    dims = [];
    dims[ 0 ] = array( "recoil25", "recoil40" );   // axis_recoil  (Deadshot)
    dims[ 1 ] = array( "fastfire" );               // axis_fire    (Gun Slinger)
    dims[ 2 ] = array( "fastreload" );             // axis_reload  (Speed Cola Mega)
    dims[ 3 ] = array( "ammo" );                   // axis_ammo    (Mule Kick Mega - The Armory)
    return dims;
}

// Every legal "_acc_<tok>..." suffix (cross-product of the dims, minus the all-none
// combo) for logical_stem_name() to strip. Mixed-radix enumeration (no array copies);
// tokens always emit in canonical axis order. Forward-safe (a combo whose twin isn't
// baked is harmless here - it just never appears on a held weapon).
function build_variant_suffixes()
{
    dims = variant_dims();
    radix = [];
    total = 1;
    for ( d = 0; d < dims.size; d++ ) { radix[ d ] = dims[ d ].size + 1; total = total * radix[ d ]; }

    out = [];
    for ( n = 0; n < total; n++ )
    {
        rem = n;
        suffix = "_acc";
        any = false;
        for ( d = 0; d < dims.size; d++ )
        {
            choice = rem % radix[ d ];        // 0 = axis inactive; 1..size = token[choice-1]
            rem = int( rem / radix[ d ] );
            if ( choice > 0 ) { suffix = suffix + "_" + dims[ d ][ choice - 1 ]; any = true; }
        }
        if ( any ) out[ out.size ] = suffix;
    }
    return out;
}

// The twin weapon names that ACTUALLY EXIST in the build. We only ever GetWeapon() a
// name in here, so an un-built twin can never throw. This MUST match the GDT
// (source_data/acc_weapon_variants.gdt) + zone weaponfull lines.
//
// GENERATED from the SAME dims as the GDT + zone (build_variant_suffixes() mirrors
// tools/apply_recoil_overhaul.js TWIN_DIMS / allTwinNames()), so the three can never drift:
// every gun + its _up form crossed with every legal "_acc_<combo>" suffix. The generator bakes
// the FULL cross-product, so every name here exists; desired_weapon() still degrades gracefully
// if a combo is somehow absent. ADD AN AXIS: just add a variant_dims() row (+ matching TWIN_DIMS
// + axis fn + level.acc_variant_axes) - this list, the suffixes, and the zone all follow.
// Current matrix: 23 combos/form (recoil x fastfire x fastreload x ammo) x 5 guns x 2 forms = 230.
function build_available_twins()
{
    suffixes = build_variant_suffixes();   // every legal "_acc_<combo>" (incl. ammo combos)

    t = [];
    guns = variant_guns();
    for ( gi = 0; gi < guns.size; gi++ )
    {
        forms = array( guns[ gi ], guns[ gi ] + "_up" );
        for ( fi = 0; fi < forms.size; fi++ )
        {
            for ( si = 0; si < suffixes.size; si++ )
                t[ forms[ fi ] + suffixes[ si ] ] = true;   // suffix already "_acc_<combo>"
        }
    }
    return t;
}

function on_player_connect( player )
{
    // Timed ability overlay (Stabilizer): a struct {recoil, fast, expiry} or undef.
    // Perk-driven state is derived live in reconcile(), never stored.
    player.acc_variant_timed = undefined;
    player thread variant_manager();
}

// ---------------------------------------------------------------------------
// Per-player reconcile loop. Idempotent: each pass brings every carried primary
// into line with the player's desired state (base when nothing is active). Wakes
// on weapon switches / explicit pokes, otherwise ~1/s.
// ---------------------------------------------------------------------------

function variant_manager()
{
    self endon( "disconnect" );

    for ( ;; )
    {
        // weapon_change[_complete] are the stock switch notifies; acc_variant_dirty is
        // our own poke from the perk/ability hooks. The timeout is the SAFETY NET that
        // re-derives state from HasPerk() live, so any edge that doesn't poke us (going
        // DOWN and losing Deadshot, a bleed-out/revive) still converges. Swaps are
        // instant+invisible, so polling is cheap.
        //
        // No PaP proximity special-case anymore: the gun is NEVER force-swapped near the
        // machine (PaP packs in place via _acc_pap_levels, on a twin or base alike), so a
        // flat 3s safety-net poll plus the event wakes (perk pokes / weapon switches) suffice.
        self util::waittill_any_timeout( 3, "acc_variant_dirty", "weapon_change", "weapon_change_complete" );
        self reconcile();
    }
}

// self = player. Bring every carried primary into line with the desired (recoil,
// fast) state.  recoil is 0 / 25 / 40 (percent reduction off the 2.1x base); fast
// is bool.
function reconcile( force )
{
    // Don't re-enter on our own swap's weapon_change (swap_weapon sets this).
    if ( IS_TRUE( self.acc_swapping ) ) return;

    // Don't touch guns while DOWNED: primaries are removed/restored by the laststand
    // flow, and Deadshot may be getting stripped. Defer to after revive - the gun is
    // reconciled then (post-revive weapon_change / the 3s net) against live HasPerk,
    // so a down that loses Deadshot reverts the gun to base once you're back up.
    if ( IS_TRUE( self.laststand ) ) return;

    // Don't fight the stock perk-drink (THE "buying Deadshot ate my ammo" bug).
    // perk_give_bottle_begin (_zm_perks.gsc) captures your gun as `original_weapon`,
    // holsters it for the bottle, raises weapon_change (which wakes our async loop), and
    // perk_give_bottle_end switches BACK to that captured weapon. If we swap base->twin
    // mid-drink, the base it captured is gone -> the switch-back re-gives base with
    // default ammo and the next reconcile copies that (often 0 reserve) onto the twin.
    // So defer: once the drink ends, the switch-back's weapon_change_complete / the 3s
    // safety-net reconciles cleanly on the re-equipped real gun (ammo intact, <=3s).
    // The Mega path (_acc_mega_bottles::replay_perk_drink) IS mid-drink on purpose -
    // it drives its own holstered swap + re-raises the twin - so it passes force=true.
    if ( !IS_TRUE( force ) && isdefined( self.is_drinking ) && self.is_drinking > 0 ) return;

    // Active variant tokens (canonical axis order), derived LIVE from perks. Empty = hold
    // the plain base gun. No Pack-a-Punch proximity suppression: PaP packs the held gun IN
    // PLACE (twin or base alike, via _acc_pap_levels), so the gun never has to revert to
    // base near the machine - it changes ONLY when you actually pack.
    tokens = [];
    if ( variants_enabled() )
        tokens = compute_tokens( self );

    equipped = self GetCurrentWeapon();
    guns = self GetWeaponsListPrimaries();

    // Reconcile the EQUIPPED weapon too: in zombies the starting-pistol slot is not
    // always in GetWeaponsListPrimaries, so add it (deduped) - otherwise Deadshot
    // wouldn't touch the gun you're holding. Non-gun holds (knife/grenade/bottle)
    // have no twin and no-op safely.
    if ( isdefined( equipped ) && equipped != level.weaponNone )
    {
        b_have = false;
        for ( i = 0; i < guns.size; i++ ) { if ( guns[ i ] == equipped ) b_have = true; }
        if ( !b_have ) guns[ guns.size ] = equipped;
    }

    for ( i = 0; i < guns.size; i++ )
    {
        w = guns[ i ];
        if ( !isdefined( w ) || w == level.weaponNone ) continue;

        stem_name = logical_stem_name( w.name );

        if ( tokens.size == 0 )
        {
            // Base state -> the gun should be its plain base form.
            if ( stem_name == w.name ) continue;   // already base, no GetWeapon needed
            desired = GetWeapon( stem_name );        // strip a lingering twin back
        }
        else
        {
            desired = desired_weapon( stem_name, tokens );
        }

        if ( !isdefined( desired ) || desired == level.weaponNone ) continue;
        if ( desired.name == w.name ) continue;     // already correct

        self swap_weapon( w, desired, equipped );
    }
}

// self = player. Replace w_from with w_to, carrying clip + reserve across.
// Mirrors the stock PaP ammo-carry swap (_zm_pack_a_punch.gsc:688-696); a variant
// twin shares the stem's clipSize/maxAmmo (only recoil/fireTime differ), so the
// clip/stock copy across 1:1 with no cap-delta math.
function swap_weapon( w_from, w_to, equipped )
{
    self endon( "disconnect" );

    // Mute reconcile while we swap: GiveWeapon/SwitchToWeapon raise our OWN
    // weapon_change notify, which would otherwise re-wake the manager mid-swap and
    // fight us. reconcile() early-returns while this is set.
    self.acc_swapping = true;

    clip  = self GetWeaponAmmoClip( w_from );
    stock = self GetWeaponAmmoStock( w_from );
    was_equipped = ( w_from == equipped );

    self GiveWeapon( w_to );
    // IMMEDIATE switch = no raise/lower animation, so the swap is invisible AND
    // GetCurrentWeapon never returns a transitional value during a ~0.5s raise -
    // that transitional window was the flip-flop / "random swap out" source.
    // Verified stock builtin (_zm_weapons / _zm_laststand / player_shared).
    if ( was_equipped ) self SwitchToWeaponImmediate( w_to );

    // Carry ammo the stock-PaP way (_zm_pack_a_punch.gsc:693-696): add any clip/reserve
    // CAP delta between the forms so the copy never clamps. A variant twin shares the
    // stem's clipSize/maxAmmo today (delta 0 == straight copy), but the delta form stays
    // correct if a future twin ever changes a cap, and clamping at 0 guards a negative.
    // Set AFTER the switch, exactly as stock does.
    new_clip  = clip  + ( w_to.clipSize - w_from.clipSize );
    new_stock = stock + ( w_to.maxAmmo  - w_from.maxAmmo );
    if ( new_clip  < 0 ) new_clip  = 0;
    if ( new_stock < 0 ) new_stock = 0;
    self SetWeaponAmmoStock( w_to, new_stock );
    self SetWeaponAmmoClip( w_to, new_clip );
    self TakeWeapon( w_from );

    // Proof-of-life: `acc_variants_debug 1` shows each swap on-screen so you can
    // confirm Deadshot/Mega is actually changing the weapon (recoil is invisible
    // otherwise). Off by default.
    if ( getdvarint( "acc_variants_debug", 0 ) == 1 )
        self iprintln( "^3[variants]^7 " + w_from.name + " ^2->^7 " + w_to.name );

    self.acc_swapping = false;
}

// ===========================================================================
// Desired-state derivation -- THE EXTENSION POINT for new perk/ability twins.
//
// Each "axis" is a function(self=player) returning the active TOKEN for one
// independent weapon-stat effect (recoil, fire rate, reload, ...), or undefined.
// level.acc_variant_axes (set in init) lists them in CANONICAL ORDER - the order
// tokens appear in a twin's name. compute_tokens() collects the active tokens;
// desired_weapon() turns them into the gun the player should hold
// (`<stem>_acc_<tok1>_<tok2>...`), with graceful fallback. The swap engine and PaP
// integration (true_base / register_twin_upgrades / packed_form) are all effect-AGNOSTIC,
// so a new effect never touches them.
//
// >>> TO ADD A NEW EFFECT (e.g. Speed Cola reload) - an agent does ONLY this: <<<
//   1. Generate the twins (tools/apply_recoil_overhaul.js style, or
//      gen_weapon_variant_gdt.js) scaling the relevant GDT field(s), named
//      "<gun>[_up]_acc_<token>" for every gun + its _up PaP form.
//   2. Add those names to build_available_twins() + zone weaponfull lines, and the
//      token's suffix(es) to level.acc_variant_suffixes (init, LONGEST-FIRST,
//      including any combined "<a>_<b>" forms).
//   3. Write an axis function below returning the token while the perk/ability is
//      active (honor timed_has() for ability overlays), and add it to
//      level.acc_variant_axes in init() in canonical order.
// Full walkthrough: docs/30_perk_gdt_radiant_spec.md "Adding a weapon-variant effect".
// ===========================================================================

// Ordered list of active variant tokens for this player (canonical axis order).
function compute_tokens( player )
{
    tokens = [];
    for ( i = 0; i < level.acc_variant_axes.size; i++ )
    {
        t = player [[ level.acc_variant_axes[ i ] ]]();
        if ( isdefined( t ) ) tokens[ tokens.size ] = t;
    }
    return tokens;
}

// --- AXIS: Deadshot recoil (-25% base / -40% Mega "American Sniper") ---------
// self = player. Returns "recoil40" / "recoil25" / undefined. Honors a timed
// overlay (Stabilizer) taking the STRONGER reduction.
function axis_recoil()
{
    lvl = deadshot_recoil_level( self );
    if ( timed_has( self, "recoil40" ) && lvl < 40 ) lvl = 40;
    else if ( timed_has( self, "recoil25" ) && lvl < 25 ) lvl = 25;

    if ( lvl == 40 ) return "recoil40";
    if ( lvl == 25 ) return "recoil25";
    return undefined;
}

// --- AXIS: Gun Slinger fire rate (+40% RoF / -50% swap time) -----------------
// self = player. Returns "fastfire" / undefined. (Base Double Tap keeps the stock
// 2.0 extra-bullet; this Mega twin only adds fire rate + faster swap on top.)
function axis_fire()
{
    if ( gunslinger_fast( self ) ) return "fastfire";
    if ( timed_has( self, "fastfire" ) ) return "fastfire";
    return undefined;
}

// --- AXIS: Speed Cola reload (Sleight of Hand Expert, Mega only) -> fastreload -
// self = player. Mega-only: base Speed Cola keeps the free engine +50% (no twin);
// the Mega twin layers reload x0.857 on top for the +75% net (docs/perk_abilities §3).
function axis_reload()
{
    if ( self HasPerk( "specialty_fastreload" ) && has_mega( self, "specialty_fastreload" ) )
        return "fastreload";
    if ( timed_has( self, "fastreload" ) ) return "fastreload";
    return undefined;
}

// --- AXIS: Mule Kick Mega "The Armory" reserve ammo (+25% capacity) -> "ammo" --
// self = player. Mega-only: +25% reserve capacity is a baked GDT maxAmmo property (the
// engine clamps reserve to maxAmmo), so like recoil/fire/reload it can ONLY be granted by
// swapping to a twin whose GDT raises maxAmmo. _acc_mega_bottles::armory_apply then GiveMaxAmmo
// fills the reserve to the raised cap. Gated on the Mule Kick Mega flag (base Mule Kick = the
// stock 3rd weapon slot, no twin).
function axis_ammo()
{
    if ( self HasPerk( "specialty_additionalprimaryweapon" ) && has_mega( self, "specialty_additionalprimaryweapon" ) )
        return "ammo";
    if ( timed_has( self, "ammo" ) ) return "ammo";
    return undefined;
}

// Deadshot recoil tier: 40 (Mega), 25 (base owner), 0. Live -> survives re-buy.
function deadshot_recoil_level( player )
{
    if ( !( player HasPerk( "specialty_deadshot" ) ) ) return 0;
    if ( has_mega( player, "specialty_deadshot" ) ) return 40;
    return 25;
}

// Gun Slinger (Mega Double Tap) -> fast-fire twin.
function gunslinger_fast( player )
{
    return ( player HasPerk( "specialty_doubletap2" ) && has_mega( player, "specialty_doubletap2" ) );
}

// Local mirror of acc_mega_bottles::has_mega_perk - read the field directly to
// avoid a cyclic #using (mega_bottles #usings THIS module to poke reconcile).
function has_mega( player, specialty )
{
    if ( !isdefined( player ) ) return false;
    if ( !isdefined( player.acc_mega_perks ) ) return false;
    if ( !isdefined( player.acc_mega_perks[ specialty ] ) ) return false;
    return player.acc_mega_perks[ specialty ] == true;
}

// ---------------------------------------------------------------------------
// Twin-name resolution
// ---------------------------------------------------------------------------

// Resolve the gun the player should hold for `tokens` (canonical order). Tries the
// full combination, then drops the lowest-priority (trailing) tokens one at a time,
// so a missing COMBINED twin degrades to a partial effect, then to base. (Single-axis
// twins are always baked; combined twins are an optional pure upgrade.)
function desired_weapon( stem_name, tokens )
{
    for ( k = tokens.size; k >= 1; k-- )
    {
        suffix = "_acc";
        for ( j = 0; j < k; j++ ) suffix = suffix + "_" + tokens[ j ];
        w = try_resolve_twin( stem_name + suffix );
        if ( isdefined( w ) ) return w;
    }
    return GetWeapon( stem_name );   // nothing baked for this combo -> base
}

// Only ever GetWeapon() a twin we declared in the allow-list, so an un-baked name
// can never raise an "unknown weapon" runtime error.
function try_resolve_twin( name )
{
    if ( !isdefined( level.acc_variant_available[ name ] ) ) return undefined;
    w = GetWeapon( name );
    if ( isdefined( w ) && w != level.weaponNone ) return w;
    return undefined;
}

// Strip a trailing variant suffix to recover the player's logical weapon
// (handles base + PaP stems, e.g. "t6_fiveseven_up_acc_recoil40" -> "t6_fiveseven_up").
function logical_stem_name( name )
{
    for ( i = 0; i < level.acc_variant_suffixes.size; i++ )
    {
        suf = level.acc_variant_suffixes[ i ];
        if ( ends_with( name, suf ) ) return GetSubStr( name, 0, name.size - suf.size );
    }
    return name;
}

function ends_with( s, suffix )
{
    if ( suffix.size > s.size ) return false;
    return GetSubStr( s, s.size - suffix.size, s.size ) == suffix;
}

// ---------------------------------------------------------------------------
// Pack-a-Punch helper (called by _acc_pap_levels for the instant in-place pack)
// ---------------------------------------------------------------------------

// The UPGRADED ("packed") form of a (possibly twin) weapon, PRESERVING any active twin
// suffix so an in-place first pack hands over the packed TWIN in ONE swap (no
// base->_up->twin double swap). Non-twin -> the stock engine upgrade
// (zm_weapons::get_upgrade_weapon). Twin (always one of the 5 variant guns, "_up"-
// convention) -> the matching "<stem>_up_acc_<combo>" from the allow-list. Returns the
// weapon UNCHANGED when there is no upgrade (already packed / a non-upgradeable hold), so
// the caller can read packed==held as "nothing to first-pack".
function packed_form( weapon )
{
    if ( !isdefined( weapon ) || weapon == level.weaponNone ) return weapon;

    stem = logical_stem_name( weapon.name );
    if ( stem != weapon.name )
    {
        // A twin: "<stem>_acc_<combo>". Its packed form is "<stem>_up_acc_<combo>".
        suffix = GetSubStr( weapon.name, stem.size, weapon.name.size );   // "_acc_<combo>"
        up = try_resolve_twin( stem + "_up" + suffix );
        if ( isdefined( up ) ) return up;
        // un-baked combo: fall through to upgrade the base, reconcile re-twins after.
    }

    base = GetWeapon( stem );
    if ( !isdefined( base ) || base == level.weaponNone ) return weapon;
    if ( zm_weapons::is_weapon_upgraded( base ) ) return base;   // stem already packed
    return zm_weapons::get_upgrade_weapon( base );               // stock base -> upgrade
}

// ---------------------------------------------------------------------------
// Public hooks (called by _acc_mega_bottles + _acc_weapon_abilities + _acc_pap_levels)
// ---------------------------------------------------------------------------

// Resolve a (possibly variant-twin) weapon to its TRUE base weapon OBJECT: strip
// our `_acc_*` suffix, then map through the stock base-weapon table. So
// s1_tac19_up_acc_recoil40 -> s1_tac19_up -> s1_tac19. THIS is the key that lets
// the PaP tier (keyed by base) follow a gun across recoil/fast swaps - the PaP
// modules key player.acc_pap_tier by this instead of zm_weapons::get_base_weapon.
function true_base( weapon )
{
    if ( !isdefined( weapon ) || weapon == level.weaponNone ) return weapon;
    stem = logical_stem_name( weapon.name );
    w = GetWeapon( stem );
    if ( !isdefined( w ) || w == level.weaponNone ) w = weapon;
    return zm_weapons::get_base_weapon( w );
}

// Poke a player's reconcile loop after their perk / Mega / loadout state changes.
function request_reconcile( player )
{
    if ( !isdefined( player ) ) return;
    player notify( "acc_variant_dirty" );
}

// The weapon the player SHOULD hold for `held` given live perk/timed state - the twin,
// or the plain base if no axis is active / no twin is baked. RETURNS only (no inventory
// change), mirroring reconcile()'s desired computation. Used by the perk-drink
// (_acc_mega_bottles::replay_perk_drink) to re-raise the correct twin so a Mega's twin
// swap is hidden by the drink animation instead of showing afterwards.
function resolve_held( player, held )
{
    if ( !isdefined( held ) || held == level.weaponNone ) return held;
    stem_name = logical_stem_name( held.name );
    if ( !variants_enabled() ) return GetWeapon( stem_name );

    tokens = compute_tokens( player );
    if ( tokens.size == 0 ) return GetWeapon( stem_name );

    w = desired_weapon( stem_name, tokens );
    return ( isdefined( w ) ? w : GetWeapon( stem_name ) );
}

// self = player. Timed overlay for weapon ABILITIES (e.g. Stabilizer): force the
// given variant TOKENS active for duration_sec, then clear. Axes OR-merge these with
// perk state (axis_recoil takes the STRONGER reduction). `tokens` = array of token
// strings, e.g. array( "recoil40", "fastfire" ). Inert until those twins are baked.
function apply_timed_variant( tokens, duration_sec )
{
    if ( !variants_enabled() ) return;

    s = spawnstruct();
    s.tokens = [];
    for ( i = 0; i < tokens.size; i++ ) s.tokens[ tokens[ i ] ] = true;
    s.expiry = gettime() + int( duration_sec * 1000 );
    self.acc_variant_timed = s;

    self notify( "acc_variant_dirty" );
    self thread clear_timed_variant_after( duration_sec );
}

// True if `token` is in this player's UNEXPIRED timed overlay. Axes call this so an
// ability overlay stacks with perk-derived state.
function timed_has( player, token )
{
    if ( !isdefined( player.acc_variant_timed ) ) return false;
    if ( gettime() >= player.acc_variant_timed.expiry ) return false;
    return IS_TRUE( player.acc_variant_timed.tokens[ token ] );
}

function clear_timed_variant_after( duration_sec )
{
    self endon( "disconnect" );
    wait duration_sec;

    // Only clear if THIS overlay expired (a later re-arm pushes expiry forward).
    if ( isdefined( self.acc_variant_timed ) && gettime() >= self.acc_variant_timed.expiry )
        self.acc_variant_timed = undefined;
    self notify( "acc_variant_dirty" );
}

function variants_enabled()
{
    return getdvarint( "acc_weapon_variants", ACC_VARIANTS_DEFAULT ) == 1;
}
