// =============================================================================
// _acc_weapon_variants.gsc - perk/ability weapon-variant SWAP framework
//
// Design reference: docs/perk_abilities.md (Deadshot §7, Double Tap §4),
// docs/30_perk_gdt_radiant_spec.md, docs/31_ape_perk_gdt_walkthrough.md §4-5,
// docs/05_weapons.md (Stabilizer weapon ability).
//
// THE PROBLEM (verified 2026-06-14 audit): recoil and fire rate are baked
// weapon-GDT properties. The engine exposes NO per-player recoil or fire-rate
// setter on a live weapon (grep-proven: zero Set*FireRate / Set*Recoil builtins,
// zero fire-rate dvar; those fields are read-only). The only way to give a player
// reduced-recoil or faster-firing guns is to SWAP the weapon for a cloned twin
// whose GDT SCALES the recoil tables / lowers fireTime, then swap the base back
// when the perk/ability ends. This module is that swap engine.
//
// WHAT IT DELIVERS (the real perk magnitudes - docs/perk_abilities.md), as
// independent twin AXES (one weapon-stat effect each, cross-producted per gun):
//   - Deadshot (any owner):       -35% recoil -> "recoil35" twin (gunKick*/viewKick* x0.65 of 2.5x base)
//   - Deadshot Mega (Am. Sniper): -70% recoil -> "recoil70" twin (x0.30)
//   - Double Tap Mega (Gun Slinger): +50% RoF + -75% swap -> "fastfire" twin (fireTime x0.667, raise/drop x0.25)
//   - Speed Cola Mega (Sleight Expert): +70% reload -> "fastreload" twin (reloadTime x0.882, on top of engine +50%)
//   (Deadshot base +1.5 / Mega +2 headshot and DT base +33% RoF are NOT here -
//    headshot is _acc_damage; the +33% is engine-granted free off the specialty.)
//
// BAKED + ACTIVE (2026-06-14): the full 110-twin matrix is generated by
// tools/apply_recoil_overhaul.js into source_data/acc_weapon_variants.gdt, listed in
// the zone (weaponfull,*) AND in build_available_twins(), with dvar default
// `acc_weapon_variants 1`. To ADD a new effect axis, see the EXTENSION POINT banner
// below. Safety net: the allow-list gates GetWeapon so an un-baked combo can never
// throw; on a gun/combo with no twin, the axis no-ops (gun stays on its base form).
//
// PERK-GATED (unlike a flat GDT cap bump): the twin is only ever given to a
// player while they hold the qualifying perk (or fire the timed ability), and is
// stripped the instant they lose it. State is derived LIVE from the perk each
// reconcile, so it survives the death/re-buy cycle (Mega flag is sticky).
// =============================================================================

#using scripts\shared\array_shared;
#using scripts\shared\util_shared;

#insert scripts\shared\shared.gsh;

#using scripts\zm\_zm_weapons;

#using scripts\zm\zm_abandoned_cyber_city\_acc_utility;

// Default ON (2026-06-14): the recoil twins are baked + the 2.5x-base skill theme
// is a core feature, so the system runs by default. Set dvar `acc_weapon_variants 0`
// to disable. `acc_variants_debug 1` prints each swap to the player (proof-of-life).
#define ACC_VARIANTS_DEFAULT 1

// Within this radius of a Pack-a-Punch machine, twins are suppressed so the player
// holds the REAL base/PaP weapon - stock first-pack + custom tier-up operate on a
// recognized weapon (a twin is not in the engine upgrade table). 150u ENGAGE radius;
// suppression then HOLDS until you pass the larger EXIT radius (200u). The 50u dead zone
// is hysteresis: without it, micro-moving across the single edge flips suppressed<->not
// every poll, and the fast near-PaP poll swaps base<->twin several times a second
// ("gun keeps switching near PaP"). See near_pap().
#define ACC_PAP_SUPPRESS_RADIUS_SQ 22500
#define ACC_PAP_SUPPRESS_EXIT_SQ   40000

#namespace acc_weapon_variants;

// ---------------------------------------------------------------------------
// Init
// ---------------------------------------------------------------------------

function init()
{
    acc_utility::log( "weapon_variants init (inert until twins baked + acc_weapon_variants 1)" );

    // Known twin suffixes, LONGEST FIRST (logical_stem_name strips a trailing one
    // to recover the player's logical weapon). Legal combos = {recoil35|recoil70}
    // x {optional fastfire} - recoil35/recoil70 never co-occur (one Deadshot tier
    // or none). recoil35 = base Deadshot -35%; recoil70 = Mega -70% (off the 2.5x
    // base). fastfire/combined arrive in Phase 2 (Gun Slinger); listed now so the
    // stem-stripper is forward-safe (harmless until those twins exist).
    // Trailing variant-suffix strip list for logical_stem_name() - every legal
    // token combination ("_acc_<tok>...", all axes), built from the dims so it stays
    // in sync. Forward-safe: listing a combo whose twin isn't baked yet is harmless.
    level.acc_variant_suffixes = build_variant_suffixes();

    // Variant AXES in CANONICAL ORDER (= the order tokens appear in a twin name) -
    // MUST match tools/apply_recoil_overhaul.js TWIN_DIMS order. Each is a
    // function(self=player) returning its active token or undefined.
    // >>> ADD A NEW PERK/ABILITY EFFECT by appending its axis here (and a matching
    // dim in variant_dims() + the built combos in build_available_twins). See the
    // "EXTENSION POINT" banner above the axis functions. <<<
    level.acc_variant_axes = array( &axis_recoil, &axis_fire, &axis_reload );

    // Allow-list of twin weapon names that ACTUALLY EXIST in the build. We only
    // ever GetWeapon() a name in here, so an un-baked twin cannot throw. POPULATE
    // this as you bake twins in APE (docs/31 §4-5). Empty = whole system inert.
    level.acc_variant_available = build_available_twins();

    // Make the PaP'd ("_up") twins first-class engine UPGRADES so the Pack-a-Punch
    // HUD / tier-up / re-pack all recognize a held twin (fixes "PaP indicator breaks").
    register_twin_upgrades();
}

// Register every PaP'd ("_up") twin in level.zombie_weapons_upgraded (twin OBJECT ->
// true-base OBJECT) - the exact table stock add_zombie_weapon writes (_zm_weapons.gsc:554).
// Result: is_weapon_upgraded(_up twin) = true and get_base_weapon(_up twin) = base
// NATIVELY, so _acc_pap_levels + the stock PaP machine read a held _up twin correctly.
//
// ONLY the _up twins are registered - the un-PaP'd base twins (recoil35/recoil70 with NO
// _up) must stay un-upgraded, or the FIRST pack would skip tier 1 + camo. We never add
// twins to level.zombie_weapons / zombie_include_weapons, so the Mystery Box can't roll them.
function register_twin_upgrades()
{
    if ( !isdefined( level.zombie_weapons_upgraded ) ) level.zombie_weapons_upgraded = [];

    keys = getarraykeys( level.acc_variant_available );
    n = 0;
    for ( i = 0; i < keys.size; i++ )
    {
        name = keys[ i ];
        tw = GetWeapon( name );
        if ( !isdefined( tw ) || tw == level.weaponNone ) continue;

        stem_w = GetWeapon( logical_stem_name( name ) );   // strip _acc -> base or _up form
        if ( !isdefined( stem_w ) || stem_w == level.weaponNone ) continue;

        // Only PaP'd twins are "upgrades": a base twin's stem is the un-upgraded base.
        if ( !( zm_weapons::is_weapon_upgraded( stem_w ) ) ) continue;

        level.zombie_weapons_upgraded[ tw ] = zm_weapons::get_base_weapon( stem_w );
        n++;
    }
    acc_utility::log( "weapon_variants: registered " + n + " _up twins as engine upgrades" );
}

// The guns that have twins (imported box guns only - stock guns have no editable
// GDT). On any other gun the perk no-ops (reconcile finds no twin -> stays on base).
// NOTE: s1_tac19 also carries an always-on baseline buff (small range x1.5 + FMJ penetrateType
// large + wider spread x1.25, traded for -15% damage) baked into its base/_up GDT
// (tools/apply_recoil_overhaul.js GUNS.baseline), so its base AND every twin have it. That's a
// GDT-only change; the swap engine here is unaffected (base <-> twin still differ only by
// recoil/fire/reload).
function variant_guns()
{
    return array( "s1_tac19", "s1_asm1", "t6_fiveseven", "t6_ak47", "s1_ae4" );
}

// Variant DIMENSIONS = the token level(s) per axis, CANONICAL ORDER. ONE source of
// truth, shared by build_variant_suffixes (strip list) and the available-combo menu.
// MUST mirror tools/apply_recoil_overhaul.js TWIN_DIMS order. The "axis inactive"
// level (no token) is implied; list only the real tokens.
function variant_dims()
{
    dims = [];
    dims[ 0 ] = array( "recoil35", "recoil70" );   // axis_recoil  (Deadshot)
    dims[ 1 ] = array( "fastfire" );               // axis_fire    (Gun Slinger)
    dims[ 2 ] = array( "fastreload" );             // axis_reload  (Speed Cola Mega)
    return dims;
}

// Every legal "_acc_<tok>..." suffix (cross-product of the dims, minus the all-none
// combo) for logical_stem_name() to strip. Mixed-radix enumeration (no array copies);
// tokens always emit in canonical axis order. Forward-safe (a combo whose twin isn't
// baked is harmless here - it just never appears on a held weapon).
function build_variant_suffixes()
{
    dims = variant_dims();
    radix = [];
    total = 1;
    for ( d = 0; d < dims.size; d++ ) { radix[ d ] = dims[ d ].size + 1; total = total * radix[ d ]; }

    out = [];
    for ( n = 0; n < total; n++ )
    {
        rem = n;
        suffix = "_acc";
        any = false;
        for ( d = 0; d < dims.size; d++ )
        {
            choice = rem % radix[ d ];        // 0 = axis inactive; 1..size = token[choice-1]
            rem = int( rem / radix[ d ] );
            if ( choice > 0 ) { suffix = suffix + "_" + dims[ d ][ choice - 1 ]; any = true; }
        }
        if ( any ) out[ out.size ] = suffix;
    }
    return out;
}

// The twin weapon names that ACTUALLY EXIST in the build. We only ever GetWeapon() a
// name in here, so an un-built twin can never throw. This MUST match the GDT
// (source_data/acc_weapon_variants.gdt) + zone weaponfull lines.
//
// >>> EXTENDING: when agents bake a new combo (run apply_recoil_overhaul.js, add its
// zone weaponfull lines), add the combo's suffix TAIL to `built` below. The axes
// already drive it; this list is just the "what's compiled in" gate. Menu of combos:
// recoil35, recoil70, fastfire, fastreload, recoil35_fastfire, recoil70_fastfire,
// recoil35_fastreload, recoil70_fastreload, fastfire_fastreload,
// recoil35_fastfire_fastreload, recoil70_fastfire_fastreload. <<<
function build_available_twins()
{
    // Full twin matrix baked 2026-06-14 (tools/apply_recoil_overhaul.js): the
    // recoil x Gun-Slinger(fire+swap) x Speed-Cola(reload) cross-product, 11 combos
    // x 5 guns x (base + _up) = 110 twins. desired_weapon() degrades gracefully if a
    // combo is ever absent. Order here is cosmetic; canonical token order is enforced
    // by variant_dims()/compute_tokens().
    built = array(
        "recoil35", "recoil70", "fastfire", "fastreload",
        "recoil35_fastfire", "recoil70_fastfire",
        "recoil35_fastreload", "recoil70_fastreload",
        "fastfire_fastreload",
        "recoil35_fastfire_fastreload", "recoil70_fastfire_fastreload" );

    t = [];
    guns = variant_guns();
    for ( gi = 0; gi < guns.size; gi++ )
    {
        forms = array( guns[ gi ], guns[ gi ] + "_up" );
        for ( fi = 0; fi < forms.size; fi++ )
        {
            for ( ci = 0; ci < built.size; ci++ )
                t[ forms[ fi ] + "_acc_" + built[ ci ] ] = true;
        }
    }
    return t;
}

function on_player_connect( player )
{
    // Timed ability overlay (Stabilizer): a struct {recoil, fast, expiry} or undef.
    // Perk-driven state is derived live in reconcile(), never stored.
    player.acc_variant_timed = undefined;
    player thread variant_manager();
}

// ---------------------------------------------------------------------------
// Per-player reconcile loop. Idempotent: each pass brings every carried primary
// into line with the player's desired state (base when nothing is active). Wakes
// on weapon switches / explicit pokes, otherwise ~1/s.
// ---------------------------------------------------------------------------

function variant_manager()
{
    self endon( "disconnect" );

    for ( ;; )
    {
        // weapon_change[_complete] are the stock switch notifies; acc_variant_dirty is
        // our own poke from the perk/ability hooks. The timeout is the SAFETY NET that
        // re-derives state from HasPerk() live, so any edge that doesn't poke us (going
        // DOWN and losing Deadshot, a bleed-out/revive) still converges. Swaps are
        // instant+invisible, so polling is cheap.
        //
        // Adaptive poll: at the Pack-a-Punch machine the twin is SUPPRESSED (you hold the
        // real gun so the engine can pack it), so poll fast (0.25s) - the instant you step
        // out of range the next tick re-applies the recoil/fire/reload twin. Without this
        // you'd keep the un-reduced base gun until the next weapon event (your reload),
        // which read as "PaP wiped my recoil until I reload". Idle elsewhere = 3s.
        timeout = ( near_pap( self ) ? 0.25 : 3 );
        self util::waittill_any_timeout( timeout, "acc_variant_dirty", "weapon_change", "weapon_change_complete" );
        self reconcile();
    }
}

// self = player. Bring every carried primary into line with the desired (recoil,
// fast) state.  recoil is 0 / 35 / 70 (percent reduction off the 2.5x base); fast
// is bool.
function reconcile()
{
    // Don't re-enter on our own swap's weapon_change (swap_weapon sets this).
    if ( IS_TRUE( self.acc_swapping ) ) return;

    // Don't touch guns while DOWNED: primaries are removed/restored by the laststand
    // flow, and Deadshot may be getting stripped. Defer to after revive - the gun is
    // reconciled then (post-revive weapon_change / the 3s net) against live HasPerk,
    // so a down that loses Deadshot reverts the gun to base once you're back up.
    if ( IS_TRUE( self.laststand ) ) return;

    // Active variant tokens (canonical axis order). Empty = hold the plain base gun.
    // Near the Pack-a-Punch machine we force base so the player holds an engine-
    // recognized weapon for the FIRST pack (an un-packed base twin is not an upgrade);
    // the registered _up twins tier-up fine in-hand, so this only matters un-packed.
    tokens = [];
    if ( variants_enabled() && !near_pap( self ) )
        tokens = compute_tokens( self );

    equipped = self GetCurrentWeapon();
    guns = self GetWeaponsListPrimaries();

    // Reconcile the EQUIPPED weapon too: in zombies the starting-pistol slot is not
    // always in GetWeaponsListPrimaries, so add it (deduped) - otherwise Deadshot
    // wouldn't touch the gun you're holding. Non-gun holds (knife/grenade/bottle)
    // have no twin and no-op safely.
    if ( isdefined( equipped ) && equipped != level.weaponNone )
    {
        b_have = false;
        for ( i = 0; i < guns.size; i++ ) { if ( guns[ i ] == equipped ) b_have = true; }
        if ( !b_have ) guns[ guns.size ] = equipped;
    }

    for ( i = 0; i < guns.size; i++ )
    {
        w = guns[ i ];
        if ( !isdefined( w ) || w == level.weaponNone ) continue;

        stem_name = logical_stem_name( w.name );

        if ( tokens.size == 0 )
        {
            // Base state -> the gun should be its plain base form.
            if ( stem_name == w.name ) continue;   // already base, no GetWeapon needed
            desired = GetWeapon( stem_name );        // strip a lingering twin back
        }
        else
        {
            desired = desired_weapon( stem_name, tokens );
        }

        if ( !isdefined( desired ) || desired == level.weaponNone ) continue;
        if ( desired.name == w.name ) continue;     // already correct

        self swap_weapon( w, desired, equipped );
    }
}

// self = player. Replace w_from with w_to, carrying clip + reserve across.
// Mirrors the stock PaP ammo-carry swap (_zm_pack_a_punch.gsc:688-696); a variant
// twin shares the stem's clipSize/maxAmmo (only recoil/fireTime differ), so the
// clip/stock copy across 1:1 with no cap-delta math.
function swap_weapon( w_from, w_to, equipped )
{
    self endon( "disconnect" );

    // Mute reconcile while we swap: GiveWeapon/SwitchToWeapon raise our OWN
    // weapon_change notify, which would otherwise re-wake the manager mid-swap and
    // fight us. reconcile() early-returns while this is set.
    self.acc_swapping = true;

    clip  = self GetWeaponAmmoClip( w_from );
    stock = self GetWeaponAmmoStock( w_from );
    was_equipped = ( w_from == equipped );

    self GiveWeapon( w_to );
    // IMMEDIATE switch = no raise/lower animation, so the swap is invisible AND
    // GetCurrentWeapon never returns a transitional value during a ~0.5s raise -
    // that transitional window was the flip-flop / "random swap out" source.
    // Verified stock builtin (_zm_weapons / _zm_laststand / player_shared).
    if ( was_equipped ) self SwitchToWeaponImmediate( w_to );
    self SetWeaponAmmoStock( w_to, stock );
    self SetWeaponAmmoClip( w_to, clip );
    self TakeWeapon( w_from );

    // Proof-of-life: `acc_variants_debug 1` shows each swap on-screen so you can
    // confirm Deadshot/Mega is actually changing the weapon (recoil is invisible
    // otherwise). Off by default.
    if ( getdvarint( "acc_variants_debug", 0 ) == 1 )
        self iprintln( "^3[variants]^7 " + w_from.name + " ^2->^7 " + w_to.name );

    self.acc_swapping = false;
}

// ===========================================================================
// Desired-state derivation -- THE EXTENSION POINT for new perk/ability twins.
//
// Each "axis" is a function(self=player) returning the active TOKEN for one
// independent weapon-stat effect (recoil, fire rate, reload, ...), or undefined.
// level.acc_variant_axes (set in init) lists them in CANONICAL ORDER - the order
// tokens appear in a twin's name. compute_tokens() collects the active tokens;
// desired_weapon() turns them into the gun the player should hold
// (`<stem>_acc_<tok1>_<tok2>...`), with graceful fallback. The swap engine, PaP
// integration (true_base / register_twin_upgrades), and proximity suppression are
// all effect-AGNOSTIC, so a new effect never touches them.
//
// >>> TO ADD A NEW EFFECT (e.g. Speed Cola reload) - an agent does ONLY this: <<<
//   1. Generate the twins (tools/apply_recoil_overhaul.js style, or
//      gen_weapon_variant_gdt.js) scaling the relevant GDT field(s), named
//      "<gun>[_up]_acc_<token>" for every gun + its _up PaP form.
//   2. Add those names to build_available_twins() + zone weaponfull lines, and the
//      token's suffix(es) to level.acc_variant_suffixes (init, LONGEST-FIRST,
//      including any combined "<a>_<b>" forms).
//   3. Write an axis function below returning the token while the perk/ability is
//      active (honor timed_has() for ability overlays), and add it to
//      level.acc_variant_axes in init() in canonical order.
// Full walkthrough: docs/30_perk_gdt_radiant_spec.md "Adding a weapon-variant effect".
// ===========================================================================

// Ordered list of active variant tokens for this player (canonical axis order).
function compute_tokens( player )
{
    tokens = [];
    for ( i = 0; i < level.acc_variant_axes.size; i++ )
    {
        t = player [[ level.acc_variant_axes[ i ] ]]();
        if ( isdefined( t ) ) tokens[ tokens.size ] = t;
    }
    return tokens;
}

// --- AXIS: Deadshot recoil (-35% base / -70% Mega "American Sniper") ---------
// self = player. Returns "recoil70" / "recoil35" / undefined. Honors a timed
// overlay (Stabilizer) taking the STRONGER reduction.
function axis_recoil()
{
    lvl = deadshot_recoil_level( self );
    if ( timed_has( self, "recoil70" ) && lvl < 70 ) lvl = 70;
    else if ( timed_has( self, "recoil35" ) && lvl < 35 ) lvl = 35;

    if ( lvl == 70 ) return "recoil70";
    if ( lvl == 35 ) return "recoil35";
    return undefined;
}

// --- AXIS: Gun Slinger fire rate (+50% RoF / -75% swap time) -----------------
// self = player. Returns "fastfire" / undefined.
function axis_fire()
{
    if ( gunslinger_fast( self ) ) return "fastfire";
    if ( timed_has( self, "fastfire" ) ) return "fastfire";
    return undefined;
}

// --- AXIS: Speed Cola reload (Sleight of Hand Expert, Mega only) -> fastreload -
// self = player. Mega-only: base Speed Cola keeps the free engine +50% (no twin);
// the Mega twin layers reload x0.882 on top for the +70% net (docs/perk_abilities §3).
function axis_reload()
{
    if ( self HasPerk( "specialty_fastreload" ) && has_mega( self, "specialty_fastreload" ) )
        return "fastreload";
    if ( timed_has( self, "fastreload" ) ) return "fastreload";
    return undefined;
}

// Deadshot recoil tier: 70 (Mega), 35 (base owner), 0. Live -> survives re-buy.
function deadshot_recoil_level( player )
{
    if ( !( player HasPerk( "specialty_deadshot" ) ) ) return 0;
    if ( has_mega( player, "specialty_deadshot" ) ) return 70;
    return 35;
}

// Gun Slinger (Mega Double Tap) -> fast-fire twin.
function gunslinger_fast( player )
{
    return ( player HasPerk( "specialty_doubletap2" ) && has_mega( player, "specialty_doubletap2" ) );
}

// Local mirror of acc_mega_bottles::has_mega_perk - read the field directly to
// avoid a cyclic #using (mega_bottles #usings THIS module to poke reconcile).
function has_mega( player, specialty )
{
    if ( !isdefined( player ) ) return false;
    if ( !isdefined( player.acc_mega_perks ) ) return false;
    if ( !isdefined( player.acc_mega_perks[ specialty ] ) ) return false;
    return player.acc_mega_perks[ specialty ] == true;
}

// ---------------------------------------------------------------------------
// Twin-name resolution
// ---------------------------------------------------------------------------

// Resolve the gun the player should hold for `tokens` (canonical order). Tries the
// full combination, then drops the lowest-priority (trailing) tokens one at a time,
// so a missing COMBINED twin degrades to a partial effect, then to base. (Single-axis
// twins are always baked; combined twins are an optional pure upgrade.)
function desired_weapon( stem_name, tokens )
{
    for ( k = tokens.size; k >= 1; k-- )
    {
        suffix = "_acc";
        for ( j = 0; j < k; j++ ) suffix = suffix + "_" + tokens[ j ];
        w = try_resolve_twin( stem_name + suffix );
        if ( isdefined( w ) ) return w;
    }
    return GetWeapon( stem_name );   // nothing baked for this combo -> base
}

// Only ever GetWeapon() a twin we declared in the allow-list, so an un-baked name
// can never raise an "unknown weapon" runtime error.
function try_resolve_twin( name )
{
    if ( !isdefined( level.acc_variant_available[ name ] ) ) return undefined;
    w = GetWeapon( name );
    if ( isdefined( w ) && w != level.weaponNone ) return w;
    return undefined;
}

// Strip a trailing variant suffix to recover the player's logical weapon
// (handles base + PaP stems, e.g. "t6_fiveseven_up_acc_recoil70" -> "t6_fiveseven_up").
function logical_stem_name( name )
{
    for ( i = 0; i < level.acc_variant_suffixes.size; i++ )
    {
        suf = level.acc_variant_suffixes[ i ];
        if ( ends_with( name, suf ) ) return GetSubStr( name, 0, name.size - suf.size );
    }
    return name;
}

function ends_with( s, suffix )
{
    if ( suffix.size > s.size ) return false;
    return GetSubStr( s, s.size - suffix.size, s.size ) == suffix;
}

// ---------------------------------------------------------------------------
// Pack-a-Punch proximity (twins are suppressed at the machine, see reconcile)
// ---------------------------------------------------------------------------

// PaP machine origins, cached once the triggers exist (same query the stock PaP
// flow + _acc_pap_levels::pap_cost_display_keeper use). [] until they spawn.
function pap_origins()
{
    if ( isdefined( level.acc_pap_origins ) ) return level.acc_pap_origins;
    origins = [];
    trigs = GetEntArray( "pack_a_punch", "script_noteworthy" );
    for ( i = 0; i < trigs.size; i++ )
    {
        if ( isdefined( trigs[ i ] ) ) origins[ origins.size ] = trigs[ i ].origin;
    }
    if ( origins.size > 0 ) level.acc_pap_origins = origins;   // cache once found
    return origins;
}

// Sticky/hysteretic PaP proximity (self-state on player.acc_pap_suppress): engage
// suppression inside the 150u ENGAGE radius, and only RELEASE it once past the 200u EXIT
// radius. The 50u dead zone stops the boundary flip-flop that, with the fast near-PaP
// poll, made the gun swap base<->twin several times a second while lingering at the
// machine. Idempotent reconcile in the dead zone => no swap => no flicker.
function near_pap( player )
{
    origins = pap_origins();

    inside_engage = false;
    inside_exit = false;
    for ( i = 0; i < origins.size; i++ )
    {
        d2 = DistanceSquared( player.origin, origins[ i ] );
        if ( d2 < ACC_PAP_SUPPRESS_RADIUS_SQ ) inside_engage = true;
        if ( d2 < ACC_PAP_SUPPRESS_EXIT_SQ )   inside_exit = true;
    }

    if ( IS_TRUE( player.acc_pap_suppress ) )
        player.acc_pap_suppress = inside_exit;     // stay suppressed until clear of EXIT
    else
        player.acc_pap_suppress = inside_engage;   // engage only inside ENGAGE

    return player.acc_pap_suppress;
}

// ---------------------------------------------------------------------------
// Public hooks (called by _acc_mega_bottles + _acc_weapon_abilities + _acc_pap_levels)
// ---------------------------------------------------------------------------

// Resolve a (possibly variant-twin) weapon to its TRUE base weapon OBJECT: strip
// our `_acc_*` suffix, then map through the stock base-weapon table. So
// s1_tac19_up_acc_recoil70 -> s1_tac19_up -> s1_tac19. THIS is the key that lets
// the PaP tier (keyed by base) follow a gun across recoil/fast swaps - the PaP
// modules key player.acc_pap_tier by this instead of zm_weapons::get_base_weapon.
function true_base( weapon )
{
    if ( !isdefined( weapon ) || weapon == level.weaponNone ) return weapon;
    stem = logical_stem_name( weapon.name );
    w = GetWeapon( stem );
    if ( !isdefined( w ) || w == level.weaponNone ) w = weapon;
    return zm_weapons::get_base_weapon( w );
}

// Poke a player's reconcile loop after their perk / Mega / loadout state changes.
function request_reconcile( player )
{
    if ( !isdefined( player ) ) return;
    player notify( "acc_variant_dirty" );
}

// The weapon the player SHOULD hold for `held` given live perk/timed state - the twin,
// or the plain base if no axis is active / no twin is baked / suppressed at PaP. RETURNS
// only (no inventory change), mirroring reconcile()'s desired computation. Used by the
// perk-drink (_acc_mega_bottles::replay_perk_drink) to re-raise the correct twin so a
// Mega's twin swap is hidden by the drink animation instead of showing afterwards.
function resolve_held( player, held )
{
    if ( !isdefined( held ) || held == level.weaponNone ) return held;
    stem_name = logical_stem_name( held.name );
    if ( !variants_enabled() || near_pap( player ) ) return GetWeapon( stem_name );

    tokens = compute_tokens( player );
    if ( tokens.size == 0 ) return GetWeapon( stem_name );

    w = desired_weapon( stem_name, tokens );
    return ( isdefined( w ) ? w : GetWeapon( stem_name ) );
}

// self = player. Timed overlay for weapon ABILITIES (e.g. Stabilizer): force the
// given variant TOKENS active for duration_sec, then clear. Axes OR-merge these with
// perk state (axis_recoil takes the STRONGER reduction). `tokens` = array of token
// strings, e.g. array( "recoil70", "fastfire" ). Inert until those twins are baked.
function apply_timed_variant( tokens, duration_sec )
{
    if ( !variants_enabled() ) return;

    s = spawnstruct();
    s.tokens = [];
    for ( i = 0; i < tokens.size; i++ ) s.tokens[ tokens[ i ] ] = true;
    s.expiry = gettime() + int( duration_sec * 1000 );
    self.acc_variant_timed = s;

    self notify( "acc_variant_dirty" );
    self thread clear_timed_variant_after( duration_sec );
}

// True if `token` is in this player's UNEXPIRED timed overlay. Axes call this so an
// ability overlay stacks with perk-derived state.
function timed_has( player, token )
{
    if ( !isdefined( player.acc_variant_timed ) ) return false;
    if ( gettime() >= player.acc_variant_timed.expiry ) return false;
    return IS_TRUE( player.acc_variant_timed.tokens[ token ] );
}

function clear_timed_variant_after( duration_sec )
{
    self endon( "disconnect" );
    wait duration_sec;

    // Only clear if THIS overlay expired (a later re-arm pushes expiry forward).
    if ( isdefined( self.acc_variant_timed ) && gettime() >= self.acc_variant_timed.expiry )
        self.acc_variant_timed = undefined;
    self notify( "acc_variant_dirty" );
}

function variants_enabled()
{
    return getdvarint( "acc_weapon_variants", ACC_VARIANTS_DEFAULT ) == 1;
}
