// =============================================================================
// _acc_perk_lights.csc - perk machine + Pack-a-Punch GLOW (client half).
//
// The RENDER half. Stock perk-machine glow is server-side PlayFX (which does NOT
// render in this build); stock POWER-UP glow is CLIENT-side (scriptmover clientfield
// + client PlayFXOnTag, _zm_powerups.csc) and DOES render here. We copy the power-up
// path verbatim: register the SAME "accPerkGlow" clientfield the server sets, and a
// callback that PlayFX's the looped glow FX on the machine model (leak-safe: store the
// handle, StopFX before replacing, replay on a fresh-ent snapshot for late joiners).
//
// VALIDATE-FIRST palette (2026-06-18): to prove the client-FX path renders before
// authoring 10 custom recoloured .efx, every index points at a PRESENT, known-rendering
// stock .efx - Jugg red, everything else the green power-up glow, PaP teal. Once render
// is confirmed live, swap these level._effect entries to per-perk recoloured clones
// (one .efx per colour; PlayFX takes no tint arg). The server index<->perk map
// (acc_perk_lights::perk_color_index) does not change when the colours do.
//
// LOCKSTEP: scope/name/version/bits/type here MUST equal _acc_perk_lights.gsc.
// =============================================================================

#using scripts\shared\clientfield_shared;
#using scripts\shared\system_shared;
#using scripts\shared\util_shared;

#insert scripts\shared\shared.gsh;
#insert scripts\shared\version.gsh;

// Client-side precache of every glow FX (the half the 2026-06-17 attempt missed: it did
// server #precache("fx") only, so clients had no asset to draw). These are per-perk
// recoloured clones of the proven green power-up aura (the ONE FX confirmed to render here,
// validated in-game 2026-06-18). Generated by tools/gen_perk_glow_fx.js, packed via the
// `fx,acc/light/...` lines in zone_source.
#precache( "client_fx", "acc/light/fx_perk_glow_red" );
#precache( "client_fx", "acc/light/fx_perk_glow_green" );
#precache( "client_fx", "acc/light/fx_perk_glow_yellow" );
#precache( "client_fx", "acc/light/fx_perk_glow_orange" );
#precache( "client_fx", "acc/light/fx_perk_glow_amber" );
#precache( "client_fx", "acc/light/fx_perk_glow_blue" );
#precache( "client_fx", "acc/light/fx_perk_glow_blacklight" );
#precache( "client_fx", "acc/light/fx_perk_glow_white" );
#precache( "client_fx", "acc/light/fx_perk_glow_purple" );
#precache( "client_fx", "acc/light/fx_perk_glow_teal" );
// Extra indices beyond the 10 perk colours (user 2026-06-24): 11 = MAGENTA (lockdown "purge" room
// lights, was red index 1), 12 = DIM WHITE (trench shard-bank "has shards" indicator).
#precache( "client_fx", "acc/light/fx_perk_glow_magenta" );
#precache( "client_fx", "acc/light/fx_perk_glow_white_dim" );

#namespace acc_perk_lights;

REGISTER_SYSTEM( "acc_perk_lights", &__init__, undefined )

function __init__()
{
    // index -> recoloured glow FX (matches acc_perk_lights::perk_color_index). All are
    // recolours of the proven green power-up aura (confirmed to render in-game 2026-06-18).
    level._effect[ "acc_glow_1" ]  = "acc/light/fx_perk_glow_red";        // Jugg
    level._effect[ "acc_glow_2" ]  = "acc/light/fx_perk_glow_green";      // Speed Cola
    level._effect[ "acc_glow_3" ]  = "acc/light/fx_perk_glow_yellow";     // Double Tap
    level._effect[ "acc_glow_4" ]  = "acc/light/fx_perk_glow_orange";     // Stamin-Up
    level._effect[ "acc_glow_5" ]  = "acc/light/fx_perk_glow_amber";      // Mule Kick
    level._effect[ "acc_glow_6" ]  = "acc/light/fx_perk_glow_blue";       // Quick Revive
    level._effect[ "acc_glow_7" ]  = "acc/light/fx_perk_glow_blacklight"; // Deadshot - blacklight/UV
    level._effect[ "acc_glow_8" ]  = "acc/light/fx_perk_glow_white";      // Widow's Wine - white
    level._effect[ "acc_glow_9" ]  = "acc/light/fx_perk_glow_purple";     // PhD Flopper - purple
    level._effect[ "acc_glow_10" ] = "acc/light/fx_perk_glow_teal";       // Pack-a-Punch - teal
    level._effect[ "acc_glow_11" ] = "acc/light/fx_perk_glow_magenta";    // lockdown "purge" room lights (user 2026-06-24, was red)
    level._effect[ "acc_glow_12" ] = "acc/light/fx_perk_glow_white_dim";  // trench shard-bank "has shards" indicator (dim white)

    // MUST match _acc_perk_lights.gsc EXACTLY. !CF_CALLBACK_ZERO_ON_NEW_ENT so the
    // latched value replays for clients that join AFTER power-on (the callback fires on
    // their initial snapshot with the set value) - exactly like the stock power-up glow.
    clientfield::register( "scriptmover", "accPerkGlow", VERSION_SHIP, 4, "int", &glow_cb, !CF_HOST_ONLY, !CF_CALLBACK_ZERO_ON_NEW_ENT );
}

// self = the machine script_model (or the PaP host). newVal = colour index (0 = off).
// Mirrors stock _zm_powerups.csc::powerup_fx_callback for leak + re-entry safety.
function glow_cb( localClientNum, oldVal, newVal, bNewEnt, bInitialSnap, fieldName, bWasTimeJump )
{
    if ( !isdefined( newVal ) || newVal == 0 )
    {
        if ( isdefined( self.acc_glow_fx ) )
        {
            StopFX( localClientNum, self.acc_glow_fx );
            self.acc_glow_fx = undefined;
        }
        return;
    }

    fx = level._effect[ "acc_glow_" + newVal ];
    if ( !isdefined( fx ) ) return;

    // The model dobj must exist before PlayFXOnTag can resolve "tag_origin".
    self util::waittill_dobj( localClientNum );
    if ( !isdefined( self ) ) return;

    if ( isdefined( self.acc_glow_fx ) )
        StopFX( localClientNum, self.acc_glow_fx );

    self.acc_glow_fx = PlayFXOnTag( localClientNum, fx, self, "tag_origin" );
}
