// =============================================================================
// _acc_pap_levels.gsc - 3-tier money-track Pack-a-Punch
//
// 3 TIERS (revamp 2026-06-16, user): the damage ladder is LINEAR +33.33%/pack -> +33% / +67% / +100%
// over the gun's normalized base damage (T3 MAX = double dmg), and the ACTUAL PaP TRANSFORM (the "_up" asset - explosive
// M1911, akimbo PDW, gold-camo'd upgrade, etc.) is DEFERRED to tier 2. Tier 1 is a pure
// "camo + damage" pack that keeps the base gun's appearance/behavior.
//
// COSTS ARE PER-GUN (user 2026-06-23): every gun has a PRICE TIER (TOP/MID/BOT) from
// pap_price_bucket() - ranked by PaP-form power, split into thirds (docs/54). The three
// numbers below are TOP / MID / BOT for that step.
//   TIER 0->1 (cost 5000 / 4000 / 3000): acc_do_first_pack - apply the gold PaP camo to the
//     HELD gun IN PLACE (NO asset swap - still the base form / base perk-twin) and record tier 1. +33% dmg.
//     The "_up" transform does NOT happen yet.
//   TIER 1->2 (cost 7500 / 6000 / 4500): acc_do_tier_up - NOW swap to the packed "_up" form (the matching
//     packed TWIN when holding a perk twin) WITH the gold camo, carrying ammo. This is the
//     real PaP transform. +67% dmg.
//   TIER 2->3 (cost 10000 / 8000 / 6000): acc_do_tier_up - in place, no asset re-swap, bump damage. +100% (MAX, double dmg).
//
// ALL packs happen IN PLACE - no machine float / take-back animation, on any tier. Holding
// Use packs the held gun right there, and EVERY tier replays the first-pack in-hand "gun
// comes out" draw (user 2026-06-15; see replay_pack_draw / acc_pap_tier_anim). The stock
// machine's float pack is BLOCKED (acc_pap_validate returns false for EVERY gun).
//
//   player.acc_pap_tier[ base_weapon ] = 1..3   (keyed by acc_weapon_variants::true_base)
//   -> _acc_damage multiplies pap_tier_mult(tier) into every gun hit (1.3333 / 1.66666 / 1.999999).
//   -> HUD shows a roman-numeral cyber-shield icon (I/II/III) for the held weapon, centered
//      on the gadget circle (bottom-right) - acc_hud.lua CoD.AccPapTierIcon via accPapTier.
//   -> each pack/tier-up prints the new tier's benefit so the player can decide.
//
// BOX GUNS MUST COME OUT STOCK (user 2026-06-15). Tier 1 is now a BASE-FORM gun (camo only),
// so we can NO LONGER lean on is_weapon_upgraded() to keep a box copy stock (that was the old
// 5-tier invariant: tier rode the "_up" asset). Two mechanisms replace it, both keyed by
// true_base:
//   - box_grab_clear_watcher (per player, on the stock "user_grabbed_weapon" notify): the
//     weapon just handed over by the Mystery Box is reset to tier 0, so a re-boxed copy of a
//     gun you previously packed is stock again.
//   - tier_possession_prune (in pap_hud_loop): clears acc_pap_tier[ base ] for any base the
//     player no longer carries ANY form of (covers wallbuy-over / slot swaps). Gated on
//     !laststand && !is_drinking && !acc_pap_busy so it never fires mid-pack / mid-down.
//
// "Can't PaP gun X" with the prompt PRESENT but a re-pack no-op = MAX TIER (3/3). Re-packing
// a maxed gun correctly REFUSES ("already max tier 3").
// =============================================================================

#using scripts\shared\flag_shared;
#using scripts\shared\hud_util_shared;
#using scripts\shared\util_shared;

#insert scripts\shared\shared.gsh;

#using scripts\zm\_zm;
#using scripts\zm\_zm_score;
#using scripts\zm\_zm_utility;
#using scripts\zm\_zm_weapons;

#using scripts\zm\zm_abandoned_cyber_city\_acc_utility;
#using scripts\zm\zm_abandoned_cyber_city\_acc_weapon_variants;
#using scripts\zm\zm_abandoned_cyber_city\_acc_lui;

#define ACC_PAP_MAX_TIER 3
// Per-step PaP costs are now PER-GUN by PRICE TIER (TOP/MID/BOT) - see pap_price_bucket()
// + tier_cost() below (generated by tools/compute_gun_tiers.js, docs/54). The old flat
// ACC_PAP_TIER_COST_2/3 #defines were replaced by that table 2026-06-23.
#define ACC_PAP_STOCK_FIRST_COST 5000   // stock machine first-pack price; a Bonfire Sale would lower it (none in this map, but the T1 override is guarded against it)

// PaP has no machine float / weapon-lock on any tier - the pack/upgrade happens in hand the
// moment you finish the Use-hold (every tier replays the first-pack in-hand draw, 2026-06-15).
// This debounce just stops one completed Use-hold from re-firing the machine trigger and
// packing/tiering twice (double-charge); short, spans a single hold.
#define ACC_PAP_PACK_DEBOUNCE 1.0
#define ACC_PAP_FIRST_PACK_COST 5000   // fallback if a gun has no bucket entry / live self.cost is unset

#namespace acc_pap_levels;

function init()
{
    acc_utility::log( "pap_levels: init (max tier " + ACC_PAP_MAX_TIER + ")" );
    // The PaP tier damage multiplier is applied inside _acc_damage's single
    // multiplier chain (2026-06-14), NOT a separate actor-damage callback. Two
    // modifying callbacks can't coexist: stock dispatch takes the first non -1
    // and passes the original damage to each (_zm.gsc:5824), so a second callback
    // never stacked - PaP tier silently dropped on headshots/perk'd hits. get_tier
    // + pap_tier_mult below stay as the queryable source of truth for that chain.
    level thread player_setup_loop();
    level thread pap_tier_machine_watcher(); // multi-pack tiers 2-5, no AAT
    level thread pap_cost_display_keeper(); // show the real tier-up cost on the machine
}

// Keep the machine's advertised price equal to the player's ACTUAL next-pack charge. The
// stock hint reads the cost LIVE every frame: an UPGRADED ("_up") gun shows self.aat_cost,
// a base/upgradeable gun shows self.cost (verified vs _zm_pack_a_punch.gsc:430-442). We can't
// reword the stock string from a usermap, but we CAN drive the number. Per-player isn't
// possible on the shared trigger, so it tracks the nearest player (solo-exact). The 10% Armory
// discount is folded in. Reads the perk field directly (no #using cycle). self unused; level loop.
//
// 3-tier mapping (revamp 2026-06-16):
//   tier 0 (stock base)      -> self.cost stays the machine's own cost (5000, or 1000 on a
//                               bonfire sale) - DON'T touch it, so bonfire sales survive.
//   tier 1 (camo'd base)     -> the NEXT pack is the transform (tier 2). The gun is still
//                               un-upgraded, so the prompt reads self.cost -> OVERRIDE it to the
//                               tier-2 price (save/restore so a leftover override never clobbers
//                               the bonfire/stock cost once a tier-0 player returns).
//   tier 2 (_up)             -> self.aat_cost = tier-3 price.
//   tier 3 (_up, MAX)        -> self.aat_cost = 0 (no re-pack; holding Use no-ops, so zeroing
//                               stops the stale tier-3 price falsely advertising a re-pack).
function pap_cost_display_keeper()
{
    level endon( "end_game" );
    level flag::wait_till( "initial_blackscreen_passed" );

    triggers = [];
    for ( i = 0; i < 60; i++ )
    {
        triggers = GetEntArray( "pack_a_punch", "script_noteworthy" );
        if ( triggers.size > 0 ) break;
        wait 0.5;
    }
    if ( triggers.size == 0 ) return;

    for ( ;; )
    {
        for ( i = 0; i < triggers.size; i++ )
        {
            t = triggers[ i ];
            if ( !isdefined( t ) ) continue;

            np = nearest_pap_player( t.origin );
            tier = -1;
            w = undefined;
            if ( isdefined( np ) )
            {
                w = np GetCurrentWeapon();
                if ( isdefined( w ) && w != level.weaponNone )
                    tier = get_tier( np, w );
            }

            if ( is_actionfigure( w ) )
            {
                // Action Figure PaPs IN PLACE (no _up form, so is_upgraded_safe is always false) - drive the
                // price off its tier. A non-upgraded weapon's prompt reads self.cost. user 2026-06-24.
                if ( tier >= ACC_PAP_MAX_TIER )
                {
                    restore_machine_cost( t );   // maxed: show the machine's own cost (using it no-ops)
                }
                else
                {
                    if ( !IS_TRUE( t.acc_cost_overridden ) )
                    {
                        t.acc_saved_cost = t.cost;
                        t.acc_cost_overridden = true;
                    }
                    t.cost = np armory_discount( weapon_tier_cost( w, tier + 1 ) );
                }
            }
            else if ( is_upgraded_safe( w ) )
            {
                // tier 2/3 (_up form): stock prompt reads self.aat_cost. Clear any leftover
                // self.cost override first so a returning tier-0 player sees the real cost.
                restore_machine_cost( t );
                if ( tier < 2 ) tier = 2; // an _up gun is always >= tier 2
                if ( tier >= ACC_PAP_MAX_TIER )
                    t.aat_cost = 0; // maxed: no re-pack
                else
                    t.aat_cost = np armory_discount( weapon_tier_cost( w, tier + 1 ) );
            }
            else if ( tier == 1 )
            {
                // tier 1 (camo'd base, still un-upgraded): stock prompt reads self.cost, but the
                // NEXT pack is the tier-2 transform - override the displayed cost to its price.
                if ( !IS_TRUE( t.acc_cost_overridden ) )
                {
                    t.acc_saved_cost = t.cost;
                    t.acc_cost_overridden = true;
                }
                t.cost = np armory_discount( weapon_tier_cost( w, 2 ) );
            }
            else if ( tier == 0 && pap_weapon_packable( w ) )
            {
                // tier 0 (packable base gun): gun-tier the FIRST-pack price (TOP 5000 /
                // MID 4000 / BOT 3000). Save the machine's own cost once; if a Bonfire Sale
                // ever drops it below the stock 5000, keep the sale instead of overriding
                // (no bonfire powerup in this map today, but this stays safe if one is added).
                if ( !IS_TRUE( t.acc_cost_overridden ) )
                {
                    t.acc_saved_cost = t.cost;
                    t.acc_cost_overridden = true;
                }
                if ( t.acc_saved_cost < ACC_PAP_STOCK_FIRST_COST )
                    t.cost = t.acc_saved_cost;                               // bonfire/sale - keep it
                else
                    t.cost = np armory_discount( weapon_tier_cost( w, 1 ) ); // per-gun first-pack price
            }
            else
            {
                // no nearby player / non-packable held item: restore the machine's own cost (bonfire-safe).
                restore_machine_cost( t );
            }
        }
        wait 0.2;
    }
}

// is_weapon_upgraded with an undefined/weaponNone guard (the keeper may have no nearby player).
function is_upgraded_safe( w )
{
    if ( !isdefined( w ) || w == level.weaponNone ) return false;
    return zm_weapons::is_weapon_upgraded( w );
}

// Undo a tier-1 self.cost override so the machine's own cost (5000, or a bonfire 1000)
// shows again for a tier-0 first pack.
function restore_machine_cost( t )
{
    if ( IS_TRUE( t.acc_cost_overridden ) )
    {
        t.cost = t.acc_saved_cost;
        t.acc_cost_overridden = false;
    }
}

function nearest_pap_player( origin )
{
    best = 16900; // 130u - PaP machines are larger than perk vendors
    np = undefined;
    players = GetPlayers();
    for ( i = 0; i < players.size; i++ )
    {
        p = players[ i ];
        if ( !isdefined( p ) || !isplayer( p ) ) continue;
        d = DistanceSquared( p.origin, origin );
        if ( d < best ) { best = d; np = p; }
    }
    return np;
}

// =============================================================================
// PER-GUN PaP PRICING (user 2026-06-23). The per-step PaP cost depends on the gun's
// PRICE TIER (TOP/MID/BOT), assigned by ranking every gun on its PaP-form power and
// splitting the ranking into thirds (rank terciles). GENERATED by
// tools/compute_gun_tiers.js - do NOT hand-edit the table between the BEGIN/END
// markers; edit that script's roster and re-run (it regenerates docs/54 + this
// snippet to paste). IsSubStr so one entry covers a gun's base + _up + _acc twin.
// =============================================================================

// <<< BEGIN GENERATED (tools/compute_gun_tiers.js) >>>
function pap_price_bucket( weapon_name )
{
    if ( !isdefined( weapon_name ) ) return "BOT";

    // TOP  (5000 / 7500 / 10000)
    if ( IsSubStr( weapon_name, "thundergun" ) )        return "TOP";   // Thundergun (special)
    if ( IsSubStr( weapon_name, "t8_melee_figure" ) )   return "TOP";   // Action Figure (special)
    if ( IsSubStr( weapon_name, "t6_chicom_cqb" ) )     return "TOP";   // Chicom CQB (PaP 8.05)
    if ( IsSubStr( weapon_name, "t9_m60" ) )            return "TOP";   // M60 (PaP 7.97)
    if ( IsSubStr( weapon_name, "t9_ak74u" ) )          return "TOP";   // AK-74u (PaP 7.90)
    if ( IsSubStr( weapon_name, "s4_ppsh41" ) )         return "TOP";   // PPSH-41 (PaP 7.78)
    if ( IsSubStr( weapon_name, "s1_tac19" ) )          return "TOP";   // Tac-19 (PaP 7.60, -10% dmg nerf)
    if ( IsSubStr( weapon_name, "s1_mors" ) )           return "TOP";   // MORS (PaP 7.50, reserve -20%)

    // MID  (4000 / 6000 / 8000)
    if ( IsSubStr( weapon_name, "s1_mahem" ) )          return "MID";   // Mahem (special)
    if ( IsSubStr( weapon_name, "s1_ae4" ) )            return "MID";   // AE4 (PaP 7.19)
    if ( IsSubStr( weapon_name, "s1_rw1" ) )            return "MID";   // RW1 (PaP 7.15)
    if ( IsSubStr( weapon_name, "t9_ak47" ) )           return "MID";   // AK-47 (PaP 7.04)
    if ( IsSubStr( weapon_name, "s1_asm1" ) )           return "MID";   // ASM1 (PaP 7.02)
    if ( IsSubStr( weapon_name, "t6_galil" ) )          return "MID";   // Galil (PaP 6.85)

    // BOT  (3000 / 4500 / 6000)
    if ( IsSubStr( weapon_name, "t8_paladin_hb50" ) )   return "BOT";   // Paladin HB50 (PaP 6.42)
    if ( IsSubStr( weapon_name, "t9_rpd" ) )            return "BOT";   // RPD (PaP 6.10, clip+reserve +25%)
    if ( IsSubStr( weapon_name, "t6_fiveseven" ) )      return "BOT";   // Five-Seven (PaP 6.10)
    if ( IsSubStr( weapon_name, "s1_mk14" ) )           return "BOT";   // MK14 (PaP 5.99)
    if ( IsSubStr( weapon_name, "t6_olympia" ) )        return "BOT";   // Olympia (PaP 3.67, -50% dmg nerf)

    return "BOT";   // default: cheapest tier
}

// Per-step PaP cost: price tier x PaP tier (1..3). docs/54.
function tier_cost( bucket, tier )
{
    if ( bucket == "TOP" )
    {
        switch ( tier ) { case 1: return 5000; case 2: return 7500; case 3: return 10000; }
    }
    else if ( bucket == "MID" )
    {
        switch ( tier ) { case 1: return 4000; case 2: return 6000; case 3: return 8000; }
    }
    else   // "BOT" and default
    {
        switch ( tier ) { case 1: return 3000; case 2: return 4500; case 3: return 6000; }
    }
    return 0;
}
// <<< END GENERATED >>>

// Cost to buy PaP `tier` (1..3) for the held weapon `w`, by its price tier (TOP/MID/BOT).
// Twin/_up aware via the IsSubStr matching in pap_price_bucket( w.name ).
function weapon_tier_cost( w, tier )
{
    if ( !isdefined( w ) || w == level.weaponNone ) return tier_cost( "BOT", tier );
    return tier_cost( pap_price_bucket( w.name ), tier );
}

// True if the held weapon is the Action Figure melee. ONE-OFF: it has NO "_up" form, so it PaPs IN PLACE -
// tiers 1..3 add CLEAVE targets to its always-one-knife in _acc_damage (acc_pap_actionfigure does the pack).
function is_actionfigure( w )
{
    if ( !isdefined( w ) || w == level.weaponNone || !isdefined( w.name ) ) return false;
    return w.name == "t8_melee_figure" || w.name == "t8_actionfigure_melee";
}

// True if `w` actually has a PaP form (so the machine can pack it). Used by the cost display so a
// non-packable held item (knife / already-max) doesn't show a first-pack price. packed_form() returns the
// weapon UNCHANGED when there is no upgrade. EXCEPTION: the Action Figure melee packs in place (no _up form).
function pap_weapon_packable( w )
{
    if ( !isdefined( w ) || w == level.weaponNone ) return false;
    if ( is_actionfigure( w ) ) return true;   // Action Figure: in-place PaP (no _up) - see acc_pap_actionfigure
    packed = acc_weapon_variants::packed_form( w );
    return isdefined( packed ) && packed != level.weaponNone && packed != w;
}

// Stock PaP custom_validation hook (_zm_pack_a_punch.gsc:399-406). self = PaP machine,
// arg = player; runs when the player finishes the Use-hold. We do EVERY pack OURSELVES, IN
// PLACE and INSTANTLY (user 2026-06-14: no machine float / animation on any tier), and
// ALWAYS return false so the stock machine's float pack + take-back never runs (that
// take-back is also what raced + ate the Use press = the old "PaP stole my gun" bug).
//
// Routed by the player's CURRENT tier on the held gun (3-tier revamp 2026-06-16):
//   - tier 0 -> acc_do_first_pack: gold camo on the base gun + record tier 1. NO transform.
//   - tier 1 -> acc_do_tier_up (->2): swap to the packed "_up" form (the real transform) + camo.
//   - tier 2 -> acc_do_tier_up (->3): in-place damage bump, no asset re-swap.
//   - tier 3 -> acc_do_tier_up: refuses (already max).
function acc_pap_validate( player )   // self = the PaP machine trigger
{
    w = player GetCurrentWeapon();
    if ( !isdefined( w ) || w == level.weaponNone ) return false;

    // Action Figure melee: one-off in-place PaP (no _up form) - handle it entirely on its own so the gun
    // pack/transform flow below is never touched. user 2026-06-23.
    if ( is_actionfigure( w ) )
    {
        player thread acc_pap_actionfigure();
        return false;
    }

    if ( get_tier( player, w ) <= 0 )
    {
        // FIRST pack (tier 0->1): charge the gun's PRICE-TIER T1 cost (TOP 5000 / MID 4000 /
        // BOT 3000), 10% off with The Armory. BONFIRE-SAFE: the cost keeper overrides self.cost
        // for display, so read the machine's TRUE base cost (saved by the keeper) - if a sale
        // dropped it below the stock 5000, honor the sale instead of the per-gun price.
        true_machine = ( IS_TRUE( self.acc_cost_overridden ) ? self.acc_saved_cost : self.cost );
        if ( isdefined( true_machine ) && true_machine < ACC_PAP_STOCK_FIRST_COST )
            cost = true_machine;                                         // bonfire sale wins
        else
            cost = player armory_discount( weapon_tier_cost( w, 1 ) );   // per-gun first-pack price
        player thread acc_do_first_pack( w, cost );
    }
    else
        player thread acc_do_tier_up( w );

    return false;    // ALWAYS block the stock float; both packs happen in-hand, instantly
}

// self = player. 10% Armory discount (Mega Mule Kick OWNED right now - not just the
// persistent Mega flag, which survives a down - counting an EMP-paused perk as owned so a
// boss debuff doesn't drop it, a real loss does). Rounds down to a multiple of 10. Shared
// by the first pack, the tier-up, and the machine cost display.
function armory_discount( cost )
{
    if ( isdefined( self.acc_mega_perks )
         && isdefined( self.acc_mega_perks[ "specialty_additionalprimaryweapon" ] )
         && self.acc_mega_perks[ "specialty_additionalprimaryweapon" ] == true
         && ( self HasPerk( "specialty_additionalprimaryweapon" )
              || ( isdefined( self.disabled_perks ) && IS_TRUE( self.disabled_perks[ "specialty_additionalprimaryweapon" ] ) ) ) )
    {
        cost = int( cost * 0.9 );
        cost = int( cost / 10 ) * 10;
    }
    return cost;
}

// self = player. FIRST pack (tier 0->1), IN PLACE + INSTANT. The 3-tier revamp DEFERS the
// "_up" transform to tier 2, so this pack does NOT swap the asset - it applies the gold PaP
// camo to the HELD gun (base form, or base perk-twin) and records tier 1 (+50% damage). The
// gun keeps its base appearance/behavior; the explosive/akimbo/_up form arrives at tier 2.
// Debounced so one Use-hold can't pack twice.
function acc_do_first_pack( w, cost )
{
    if ( isdefined( self.acc_tier_cd ) && GetTime() < self.acc_tier_cd )
        return;
    self.acc_tier_cd = GetTime() + int( ACC_PAP_PACK_DEBOUNCE * 1000 );

    if ( !isdefined( w ) || w == level.weaponNone ) return;

    // Only PACKABLE guns: a hold with no upgrade path (knife / equipment / already-packed)
    // must NOT be chargeable. packed_form() returns the weapon UNCHANGED when there is no
    // upgrade, so packed==w means "nothing to pack".
    packed = acc_weapon_variants::packed_form( w );
    if ( !isdefined( packed ) || packed == level.weaponNone || packed == w ) return;

    if ( !isdefined( cost ) ) cost = ACC_PAP_FIRST_PACK_COST;
    if ( !( self zm_score::can_player_purchase( cost ) ) )
    {
        self acc_pap_play_on_machine( "zmb_perks_packa_deny" );
        self IPrintLnBold( "^1Not enough points ^7(need " + cost + ")" );
        return;
    }
    self zm_score::minus_to_player_score( cost );

    base = acc_weapon_variants::true_base( w );   // tier keyed by the true base
    if ( !isdefined( self.acc_pap_tier ) ) self.acc_pap_tier = [];
    self.acc_pap_tier[ base ] = 1;
    // DEV verify (acc_dev only): confirm the per-pack tier (user 2026-06-25, "Mahem only packs twice" - prove
    // the uniform 3-tier flow runs for every gun incl. launchers). No effect in normal play.
    if ( getdvarint( "acc_dev", 0 ) ) self IPrintLnBold( "^5[dev] PaP " + w.name + " -> tier 1/" + ACC_PAP_MAX_TIER );

    // Apply the gold PaP camo to the held gun (NO asset swap). replay_pack_draw re-gives the
    // held weapon WITH the camo options (tier 1 is now recorded) AND plays the draw; when the
    // draw anim is disabled it early-returns, so fall back to a direct camo re-give so tier 1
    // always gets its camo.
    self acc_pap_play_on_machine( "zmb_perks_packa_upgrade" );   // PaP "cook" sound = plasma-gun-fire wav, 3D on the machine (user 2026-06-22)
    self.acc_pap_busy = true;
    if ( getdvarint( "acc_pap_tier_anim", 1 ) != 0 )
        self replay_pack_draw( w );
    else
        self apply_pap_camo( w );
    self.acc_pap_busy = false;

    self fill_full_ammo( w );   // 100% full clip+reserve (akimbo-aware: fills BOTH dual-wield mags)

    self acc_pap_play_on_machine( "zmb_perks_packa_ready" );          // no aat::acquire -> NO alt-ammo
    // PaP tier/benefit TOAST removed (user 2026-06-22): PaP shows NO display/indication - only the machine price.
}

// self = player. Charge + bump the held gun's tier (2 or 3), INSTANT + in place.
//   tier 1 -> 2: the REAL PaP transform - swap to the packed "_up" form (the matching packed
//                TWIN if holding a perk twin) WITH gold camo, carrying ammo.
//   tier 2 -> 3: damage-only bump, no asset re-swap (replays the draw for feedback).
// Debounced so a single hold can't tier up more than once.
function acc_do_tier_up( w )
{
    if ( isdefined( self.acc_tier_cd ) && GetTime() < self.acc_tier_cd )
        return;
    self.acc_tier_cd = GetTime() + int( ACC_PAP_PACK_DEBOUNCE * 1000 );

    base = acc_weapon_variants::true_base( w );   // strips _acc twin suffix so the tier follows recoil swaps
    if ( !isdefined( self.acc_pap_tier ) ) self.acc_pap_tier = [];
    // Effective current tier: stored value, but an already-"_up" gun is at least tier 2.
    cur = ( isdefined( self.acc_pap_tier[ base ] ) ? self.acc_pap_tier[ base ] : 1 );
    if ( zm_weapons::is_weapon_upgraded( w ) && cur < 2 ) cur = 2;

    if ( cur >= ACC_PAP_MAX_TIER )
    {
        return;   // maxed - PaP shows no display (user 2026-06-22); the machine price already reads 0
    }

    next = cur + 1;
    cost = self armory_discount( weapon_tier_cost( w, next ) );   // per-gun price tier (TOP/MID/BOT) x 10% Armory
    if ( !( self zm_score::can_player_purchase( cost ) ) )
    {
        self acc_pap_play_on_machine( "zmb_perks_packa_deny" );
        self IPrintLnBold( "^1Not enough points ^7(need " + cost + ")" );
        return;
    }

    self acc_pap_play_on_machine( "zmb_perks_packa_upgrade" );   // PaP "cook" sound = plasma-gun-fire wav, 3D on the machine (user 2026-06-22)
    self.acc_pap_busy = true;
    did_transform = false;
    if ( next == 2 )
    {
        // TIER 1 -> 2: the real transform. Swap the held base gun for its packed "_up" form (or matching
        // packed twin) WITH gold camo. acc_do_transform fills the packed form to 100% ammo ITSELF (on the
        // known packed weapon). Bail WITHOUT charging if no packed form resolves (first pack proved one).
        if ( !acc_do_transform( w, base ) )
        {
            self.acc_pap_busy = false;
            return;
        }
        did_transform = true;
    }
    else
    {
        // TIER 2 -> 3: same "_up" asset, damage-only bump. Replay the draw for visible feedback
        // (user 2026-06-15: "do the same exact animation we do for first time pap" on every tier).
        self replay_pack_draw( w );
    }

    self zm_score::minus_to_player_score( cost );
    self.acc_pap_tier[ base ] = next;
    if ( getdvarint( "acc_dev", 0 ) ) self IPrintLnBold( "^5[dev] PaP " + w.name + " -> tier " + next + "/" + ACC_PAP_MAX_TIER );   // user 2026-06-25 Mahem pack-count verify
    self.acc_pap_busy = false;
    // Tier 2 is already full (filled inside the transform on the reliable packed ref). Tier 3 keeps the
    // SAME "_up" gun in hand (replay_pack_draw re-gives it), so fill THAT via the original w - NOT the
    // timing-sensitive GetCurrentWeapon (user 2026-06-22: Galil tier-2 wasn't getting full ammo).
    if ( !did_transform )
        self fill_full_ammo( w );
    self acc_pap_play_on_machine( "zmb_perks_packa_ready" ); // no aat::acquire -> NO alt-ammo
    // PaP tier/benefit TOAST removed (user 2026-06-22): no display/indication - only the machine price.
}

// self = player. PaP the Action Figure melee IN PLACE (one-off: it has no "_up" form). Charges the TOP-bucket
// tier price (5000/7500/10000; S-tier, user 2026-06-25 - pap_price_bucket now returns TOP for it) + bumps
// self.acc_pap_tier[base] 1->2->3 with the normal pack sounds. NO asset swap, NO camo re-give, NO ammo fill
// (it's a melee). The tier feeds the CLEAVE count in _acc_damage (actionfigure_cleave: hits 1 + tier zombies/swing).
function acc_pap_actionfigure()
{
    if ( isdefined( self.acc_tier_cd ) && GetTime() < self.acc_tier_cd )
        return;
    self.acc_tier_cd = GetTime() + int( ACC_PAP_PACK_DEBOUNCE * 1000 );

    w = self GetCurrentWeapon();
    if ( !isdefined( w ) || w == level.weaponNone ) return;
    base = acc_weapon_variants::true_base( w );
    if ( !isdefined( self.acc_pap_tier ) ) self.acc_pap_tier = [];
    cur = ( isdefined( self.acc_pap_tier[ base ] ) ? self.acc_pap_tier[ base ] : 0 );
    if ( cur >= ACC_PAP_MAX_TIER )
        return;   // maxed (tier 3 = 80% base one-knife); the machine price already reads 0

    next = cur + 1;
    cost = self armory_discount( weapon_tier_cost( w, next ) );
    if ( !( self zm_score::can_player_purchase( cost ) ) )
    {
        self acc_pap_play_on_machine( "zmb_perks_packa_deny" );
        self IPrintLnBold( "^1Not enough points ^7(need " + cost + ")" );
        return;
    }

    self acc_pap_play_on_machine( "zmb_perks_packa_upgrade" );
    self zm_score::minus_to_player_score( cost );
    self.acc_pap_tier[ base ] = next;
    self acc_pap_play_on_machine( "zmb_perks_packa_ready" );
}

// Play a PaP sound (the plasma "cook" / ready / deny) ON the nearest Pack-a-Punch machine (3D),
// so it emanates from the PaP instead of following the buyer (user 2026-06-22). self = player.
// acc_audio.csv: zmb_perks_packa_upgrade now points at the plasma-gun-fire wav (3D).
function acc_pap_play_on_machine( alias )
{
    m = acc_find_pap_machine( self );
    if ( isdefined( m ) )
        m PlaySound( alias );      // 3D, from the PaP machine
    else
        acc_utility::play_sound_at_origin( self.origin, alias );   // fallback: STATIC at the buy spot (= the PaP), never the moving player (user 2026-06-24: 3D alias was following the buyer)
}

// Nearest "pack_a_punch" script_noteworthy ent to the player = the PaP they are using. It is the
// USE TRIGGER (has an origin, which PlaySound positions fine) - same handle the cost keeper and
// _acc_perk_lights use: GetEntArray( "pack_a_punch", "script_noteworthy" ).
function acc_find_pap_machine( player )
{
    triggers = GetEntArray( "pack_a_punch", "script_noteworthy" );
    best = undefined;
    best_d = 999999999;
    foreach ( t in triggers )
    {
        if ( !isdefined( t ) ) continue;
        d = DistanceSquared( player.origin, t.origin );
        if ( d < best_d ) { best_d = d; best = t; }
    }
    // Also weigh our STANDALONE Paradise PaP(s). They are deliberately NOT
    // "pack_a_punch" script_noteworthy ents (that name would feed stock's
    // singleton GetEnt + the cost keeper + perk-lights), so they register here
    // instead. This affects pack-SOUND positioning ONLY - so the cook/ready
    // sounds play at the Paradise machine, not the far surface one. It can never
    // touch load / packing / tier / cost / the surface PaP. (spawn_paradise_pap_at)
    if ( isdefined( level.acc_custom_pap_machines ) )
    {
        foreach ( t in level.acc_custom_pap_machines )
        {
            if ( !isdefined( t ) ) continue;
            d = DistanceSquared( player.origin, t.origin );
            if ( d < best_d ) { best_d = d; best = t; }
        }
    }
    return best;
}

// =============================================================================
// PARADISE 2nd Pack-a-Punch - STANDALONE custom vendor (user 2026-06-25).
//
// WHY NOT A 2ND STOCK MACHINE: stock supports exactly ONE PaP. spawn_init
// (_zm_pack_a_punch.gsc:82-131) renames EVERY "zm_pack_a_punch" zbarrier to the
// shared "vending_packapunch", and vending_weapon_upgrade() (:345) does a
// SINGULAR GetEnt("vending_packapunch") that FATALS at LOAD with two of them
// ("getent ... more than one entity"). That is exactly what broke the surface
// PaP the previous time a 2nd PaP was added (see acc_dedupe_pack_a_punch in the
// entry script + memory duplicate-pap-load-crash).
//
// THE FIX: do NOT register a 2nd stock machine at all. Build a fully self-
// contained vendor (same idiom as the Paradise Mystery Box) that reuses our OWN
// in-place tier-pack path - the EXACT same acc_do_first_pack / acc_do_tier_up /
// acc_pap_actionfigure the surface PaP routes through. The PaP tier lives on
// player.acc_pap_tier[ true_base ] (NOT on any machine), so packing at the
// surface and continuing here reads the SAME stored tier - it can NEVER reset
// (the specific bug the user warned about). The trigger NEVER carries the
// "zm_pack_a_punch" targetname, so stock's singleton GetEnt is untouched and the
// surface PaP cannot break. Pure GSC - no .map entity, no bake.
// =============================================================================
function spawn_paradise_pap_at( origin, yaw )
{
    if ( !isdefined( yaw ) ) yaw = 0;

    m = spawn( "script_model", origin );
    m setmodel( "p7_zm_vending_packapunch" );   // stock PaP vending xmodel (already loaded by the surface PaP)
    m.angles = ( 0, yaw, 0 );

    t = spawn( "trigger_radius_use", origin + ( 0, 0, 40 ), 0, 72, 100 );
    t TriggerIgnoreTeam();          // REQUIRED for a script-spawned use trigger to be usable (stock _zm_perks.gsc:1523)
    t UseTriggerRequireLookAt();
    t SetCursorHint( "HINT_NOICON" );
    t SetHintString( "Hold ^3[{+activate}]^7  Pack-a-Punch" );
    t.acc_pap_model = m;

    // Register for pack-sound positioning only (acc_find_pap_machine). This is the
    // ONLY shared hook we touch and it is purely cosmetic (where the sound plays).
    if ( !isdefined( level.acc_custom_pap_machines ) ) level.acc_custom_pap_machines = [];
    ARRAY_ADD( level.acc_custom_pap_machines, t );

    t thread paradise_pap_use_loop();
    t thread paradise_pap_hint_loop();

    acc_utility::log( "pap_levels: standalone Paradise PaP spawned at " + origin );
}

// self = the Paradise PaP trigger. On each Use-hold, dispatch EXACTLY like the surface
// PaP's acc_pap_validate (Action Figure / first pack / tier-up) but drive it ourselves -
// the real debounce + charge + tier write all live inside the player-scoped pack functions.
function paradise_pap_use_loop()
{
    self endon( "death" );
    level endon( "end_game" );

    for ( ;; )
    {
        self waittill( "trigger", player );
        if ( !isdefined( player ) || !zm_utility::is_player_valid( player ) ) continue;
        if ( IS_TRUE( player.acc_pap_busy ) ) { wait 0.05; continue; }

        w = player GetCurrentWeapon();
        if ( !isdefined( w ) || w == level.weaponNone ) { wait 0.1; continue; }

        // Same routing as acc_pap_validate, minus the stock-machine bonfire-cost read
        // (there is no stock machine here and no bonfire powerup in this map).
        if ( is_actionfigure( w ) )
        {
            player thread acc_pap_actionfigure();
        }
        else if ( get_tier( player, w ) <= 0 )
        {
            cost = player armory_discount( weapon_tier_cost( w, 1 ) );   // per-gun first-pack price (TOP/MID/BOT)
            player thread acc_do_first_pack( w, cost );
        }
        else
        {
            player thread acc_do_tier_up( w );   // computes its own next-tier cost
        }

        wait 0.1;   // stop a single completed hold re-firing the trigger (player.acc_tier_cd is the real debounce)
    }
}

// self = the Paradise PaP trigger. Keep the displayed price equal to the nearby player's
// ACTUAL next-pack charge, mirroring pap_cost_display_keeper but driving our OWN hint
// (the stock cost machinery does not apply to a custom trigger). Prices stay numeric
// (memory vague-ui-no-magnitudes: only perk/PaP *benefit* text is qualitative).
function paradise_pap_hint_loop()
{
    self endon( "death" );
    level endon( "end_game" );
    level flag::wait_till( "initial_blackscreen_passed" );

    for ( ;; )
    {
        np = nearest_pap_player( self.origin );
        w = undefined;
        if ( isdefined( np ) ) w = np GetCurrentWeapon();
        ht = paradise_pap_hint_text( np, w );
        // Only re-SetHintString when the TEXT actually changes (mirrors _acc_perk_info's acc_shown_cost
        // guard). The displayed cost is bounded to a small discrete set - 3 price buckets x 3 tiers x the
        // armory-discount toggle ~= 18 strings - so it does NOT overflow the 250-cap triggerstring cache;
        // but the un-guarded 4x/sec SetHintString re-registered the same string every tick (pure waste,
        // and the exact looped-live-value anti-pattern that crashed the soul box). Rule (memory
        // triggerstring-cap-hint-strings): a hint may interpolate ONLY a small, bounded value.
        if ( !isdefined( self.acc_last_pap_hint ) || self.acc_last_pap_hint != ht )
        {
            self SetHintString( ht );
            self.acc_last_pap_hint = ht;
        }
        wait 0.25;
    }
}

function paradise_pap_hint_text( player, w )
{
    if ( !isdefined( player ) || !isdefined( w ) || w == level.weaponNone || !pap_weapon_packable( w ) )
        return "Hold ^3[{+activate}]^7  Pack-a-Punch";

    tier = get_tier( player, w );
    if ( tier >= ACC_PAP_MAX_TIER )
        return "^2Pack-a-Punch - MAX";

    cost = player armory_discount( weapon_tier_cost( w, tier + 1 ) );
    return "Hold ^3[{+activate}]^7  Pack-a-Punch  ^2[" + cost + "]";
}

// self = player. Apply the gold PaP camo to the HELD gun in place (no asset swap), carrying
// ammo. Used by the tier-1 first pack when the draw anim is disabled (acc_pap_tier_anim 0) -
// replay_pack_draw applies the camo itself when the anim is on.
function apply_pap_camo( w )
{
    if ( !isdefined( w ) || w == level.weaponNone ) return;
    if ( ( self GetCurrentWeapon() ) != w ) return;

    camo = zm_weapons::get_pack_a_punch_camo_index( undefined );
    if ( !isdefined( camo ) ) camo = 0;
    options = self CalcWeaponOptions( camo, 0, 0 );

    clip  = self GetWeaponAmmoClip( w );
    stock = self GetWeaponAmmoStock( w );
    self GiveWeapon( w, options );
    self SwitchToWeaponImmediate( w );
    self SetWeaponAmmoStock( w, stock );
    self SetWeaponAmmoClip( w, clip );
}

// self = player. Top a freshly-packed weapon to 100% full ammo - reserve AND magazine - for ANY weapon,
// dual-wield included. GiveMaxAmmo only fills the (shared) reserve, never the magazine. A DUAL-WIELD gun
// (the akimbo "_rdw_up" PaP forms - PDW, M1911) has a SECOND magazine on its off-hand weapon
// (weapon.dualWieldWeapon); filling only the main clip left one gun empty ("PDW PaP ammo issue", user
// 2026-06-22). Stock tracks both clips separately (_zm.gsc:3057-3136 store/restore weapon +
// weapon.dualWieldWeapon). clipSize is in rounds for both wield types (consistent units).
function fill_full_ammo( w )
{
    if ( !isdefined( w ) || w == level.weaponNone ) return;

    self GiveMaxAmmo( w );                                            // RESERVE (right hand)
    if ( isdefined( w.clipSize ) ) self SetWeaponAmmoClip( w, w.clipSize );   // magazine (right hand)

    // Dual-wield (akimbo "_rdw_up": PDW/M1911): the off-hand is a SEPARATE weapon entity with its OWN
    // reserve AND clip - GiveMaxAmmo/SetWeaponAmmoClip on the main weapon do NOT touch it, so it stays
    // empty after PaP ("PDW reserve/clip not filling", user 2026-06-22). Stock Max Ammo reaches it only
    // because it loops GetWeaponsList; we hit it directly via weapon.dualWieldWeapon.
    if ( isdefined( w.isDualWield ) && w.isDualWield
         && isdefined( w.dualWieldWeapon ) && w.dualWieldWeapon != level.weaponNone )
    {
        dw = w.dualWieldWeapon;
        self GiveMaxAmmo( dw );                                       // RESERVE (off hand)
        if ( isdefined( dw.clipSize ) ) self SetWeaponAmmoClip( dw, dw.clipSize );   // magazine (off hand)
    }

    // PDW akimbo-PaP ammo FIX (user 2026-06-22 - the long-standing "15 left / 17 right / 18 reserve" bug):
    // the Skye s1_pdw_rdw_up ships TWO data errors no generic fill catches - (1) the OFF-HAND magazine's
    // clipSize is 15, not the main's 17 (akimbo guns must share a magazine size); (2) maxAmmo is a broken
    // 920 that the engine clamps to ~18 SHARED reserve, not the intended 306. Stock akimbo keeps ONE shared
    // reserve on the MAIN weapon + SEPARATE per-gun magazines (verified vs _zm.gsc:3055-3062: stock_amt =
    // GetWeaponAmmoStock(weapon); left_clip_amt = the dualWieldWeapon's own clip), which is exactly the
    // symptom. So we set the shared reserve ONCE on the main + BOTH magazines explicitly to the docs/05
    // numbers (PaP PDW = clip 17 / reserve 306 combined). Gated on the akimbo-PDW name ONLY - the base PDW
    // (not dual-wield), the M1911/Five-Seven akimbos (no "pdw" in name), and every other gun are untouched.
    if ( isdefined( w.isDualWield ) && w.isDualWield && IsSubStr( w.name, "pdw" ) )
    {
        self SetWeaponAmmoStock( w, 306 );          // shared akimbo reserve (docs/05) - overrides the broken ~18
        self SetWeaponAmmoClip( w, 17 );            // right-hand magazine
        if ( isdefined( w.dualWieldWeapon ) && w.dualWieldWeapon != level.weaponNone )
            self SetWeaponAmmoClip( w.dualWieldWeapon, 17 );   // left-hand magazine (Skye shipped 15)
    }

    // DEV readout (one-flag gated, remove once verified): prints the ACTUAL clip/reserve the engine set,
    // so a "reserve not filling" report can be checked against real numbers (user 2026-06-22 triple-check).
    if ( IS_TRUE( level.acc_dev ) )
    {
        msg = "^3PaP ammo " + w.name + ": clip " + self GetWeaponAmmoClip( w ) + " / reserve " + self GetWeaponAmmoStock( w );
        if ( isdefined( w.isDualWield ) && w.isDualWield && isdefined( w.dualWieldWeapon ) && w.dualWieldWeapon != level.weaponNone )
            msg = msg + "  ^5[offhand clip " + self GetWeaponAmmoClip( w.dualWieldWeapon ) + " / reserve " + self GetWeaponAmmoStock( w.dualWieldWeapon ) + "]";
        self IPrintLnBold( msg );
    }
}

// self = player. The tier-1 -> tier-2 asset transform: swap the held gun for its packed "_up"
// form (the matching packed TWIN when holding a perk twin) WITH the gold PaP camo, carrying
// clip+reserve across (cap-delta, clamp-at-0). Mirrors the stock PaP give (CalcWeaponOptions
// -> GiveWeapon(weapon, options), _zm_weapons.gsc:2584/2597). Returns true on a real swap,
// false if no upgrade resolves (caller must not charge). NOTE: the tier is recorded by the
// CALLER after the charge succeeds, so don't write acc_pap_tier here.
function acc_do_transform( w, base )
{
    if ( !isdefined( w ) || w == level.weaponNone ) return false;

    packed = acc_weapon_variants::packed_form( w );
    if ( !isdefined( packed ) || packed == level.weaponNone || packed == w ) return false;

    camo = zm_weapons::get_pack_a_punch_camo_index( undefined );
    if ( !isdefined( camo ) ) camo = 0;
    options = self CalcWeaponOptions( camo, 0, 0 );

    self GiveWeapon( packed, options );
    self SwitchToWeaponImmediate( packed );

    // PaP = 100% full ammo (user 2026-06-22). Fill the PACKED form DIRECTLY here, while we hold a reliable
    // reference to it - NOT via the caller's GetCurrentWeapon(), which can still report the pre-swap weapon
    // for a frame (that left a single-wield gun like the Galil under-filled at tier 2). fill_full_ammo uses
    // the PACKED gun's clip/reserve CAPS (the "_up" form usually holds MORE), and handles dual-wield. This
    // replaces the old carry-current-ammo math entirely - PaP now always lands full.
    self fill_full_ammo( packed );

    self TakeWeapon( w );

    return true;
}

// self = player. Replay the first-pack "gun comes out" draw on a tier-up (user 2026-06-15).
//
// APPROACH (user's idea, 2026-06-15): a tier-up keeps the SAME packed asset, and every in-place
// re-deploy attempt either showed nothing (re-giving the already-held weapon is a no-op) or
// swapped the player onto their OTHER gun (giving the un-packed base conflicts with the held
// packed gun, and taking the current gun auto-switches to the next one). The robust fix:
//   - SNAPSHOT every primary + its ammo,
//   - TAKE THEM ALL (player is empty-handed for a split second, so there is nothing for the
//     engine to fall back to),
//   - GIVE THE PACKED GUN BACK FIRST and switch to it - a FRESH give plays the first-raise/
//     re-cock, exactly like the first pack,
//   - RESTORE the other guns WITHOUT switching, so the packed gun stays in hand.
// No base form -> no weapon-family conflict; everything is taken -> no auto-switch target.
//
// Camo: the gold PaP camo is an OPTION (not baked into the asset), so we re-apply it to the
// packed gun and to any OTHER upgraded gun on restore (all PaP'd guns share the one camo index).
// Ammo is saved/restored per gun. Wrapped in increment_is_drinking()/disable_player_move_states()
// like the stock knuckle crack so the variant reconcile loop + player input can't fight the swap.
// Gated by acc_pap_tier_anim (default 1) so tier-ups can be reverted to instant live (set 0).
// Tune knob: the empty-handed dwell is EMPTY_FRAMES below.
function replay_pack_draw( w )
{
    if ( getdvarint( "acc_pap_tier_anim", 1 ) == 0 ) return;
    if ( !isdefined( w ) || w == level.weaponNone ) return;
    if ( ( self GetCurrentWeapon() ) != w ) return; // only animate the gun actually in hand

    camo = zm_weapons::get_pack_a_punch_camo_index( undefined );
    if ( !isdefined( camo ) ) camo = 0;
    pap_options = self CalcWeaponOptions( camo, 0, 0 );

    // Snapshot every primary + ammo. Include the held gun even if the primaries list omits the
    // starting-pistol slot (mirrors reconcile()'s same guard).
    prims = self GetWeaponsListPrimaries();
    have_w = false;
    for ( i = 0; i < prims.size; i++ ) { if ( prims[ i ] == w ) have_w = true; }
    if ( !have_w ) prims[ prims.size ] = w;

    saved_w = [];
    saved_clip = [];
    saved_stock = [];
    for ( i = 0; i < prims.size; i++ )
    {
        p = prims[ i ];
        if ( !isdefined( p ) || p == level.weaponNone ) continue;
        n = saved_w.size;
        saved_w[ n ] = p;
        saved_clip[ n ] = self GetWeaponAmmoClip( p );
        saved_stock[ n ] = self GetWeaponAmmoStock( p );
    }

    self zm_utility::increment_is_drinking();
    self zm_utility::disable_player_move_states( true );

    // Take EVERY primary - now the held gun has nothing to auto-switch onto when removed.
    for ( i = 0; i < saved_w.size; i++ )
        self TakeWeapon( saved_w[ i ] );

    // Brief empty-handed dwell so the takes process and the packed gun re-gives FRESH (a
    // same-frame take+give collapses to a no-op = no draw).
    EMPTY_FRAMES = 2;
    for ( i = 0; i < EMPTY_FRAMES; i++ ) WAIT_SERVER_FRAME;
    if ( !isdefined( self ) ) return;

    // Packed gun back FIRST + raise it -> the first-raise/re-cock plays (fresh give). Tier-gate the
    // camo like the restore loop below: replay_pack_draw is now ALSO called on OVERCLOCK (any held
    // gun, incl. never-PaP'd), so a tier-0 gun must re-give WITHOUT the gold PaP camo (user 2026-06-21).
    // get_tier returns >=1 for both PaP callers (T1 sets the tier before this call; T2/T3 hold an
    // already-"_up" gun), so PaP camo is unaffected.
    if ( get_tier( self, w ) >= 1 )
        self GiveWeapon( w, pap_options );
    else
        self GiveWeapon( w );
    self SwitchToWeaponImmediate( w );

    // Restore the rest (camo for any upgraded gun, ammo for all), WITHOUT switching, so the
    // packed gun stays in hand.
    for ( i = 0; i < saved_w.size; i++ )
    {
        p = saved_w[ i ];
        if ( !isdefined( p ) || p == level.weaponNone ) continue;
        if ( p != w )
        {
            // Re-apply the gold camo to any PaP'd gun (tier >= 1) - NOT just engine-upgraded
            // ones: a tier-1 gun is a camo'd BASE form (is_weapon_upgraded false) and must keep
            // its camo across the take/restore.
            if ( get_tier( self, p ) >= 1 )
                self GiveWeapon( p, pap_options );
            else
                self GiveWeapon( p );
        }
        self SetWeaponAmmoStock( p, saved_stock[ i ] );
        self SetWeaponAmmoClip( p, saved_clip[ i ] );
    }

    self zm_utility::enable_player_move_states();
    self zm_utility::decrement_is_drinking();
}

function pap_tier_machine_watcher()
{
    level endon( "end_game" );
    level flag::wait_till( "initial_blackscreen_passed" );

    // All machine use routes through our validation (first pack via stock, tier-ups in
    // place). NO parallel trigger -> no take-back theft. We do NOT touch the stock
    // visibility loop, so the machine's own hint shows normally and there is no flicker
    // (no second trigger to fight). Bind on EVERY pack_a_punch machine, not just the singular
    // level.pack_a_punch (user 2026-06-25: a 2nd PaP in Paradise) - else the 2nd machine falls
    // through to the stock float-pack. Poll like the cost keeper (machines spawn during stock PaP init).
    machines = [];
    for ( i = 0; i < 60; i++ )
    {
        machines = GetEntArray( "pack_a_punch", "script_noteworthy" );
        if ( machines.size > 0 ) break;
        wait 0.5;
    }
    n = 0;
    foreach ( m in machines )
    {
        if ( isdefined( m ) ) { m.custom_validation = &acc_pap_validate; n++; }
    }
    // CRITICAL BUGFIX (user 2026-06-25): stock reads the validation hook from the SINGULAR
    // level.pack_a_punch.custom_validation (_zm_pack_a_punch.gsc:399-401), NOT the per-trigger
    // m.custom_validation set above. Binding ONLY per-trigger (the 2026-06-25 "bind on every
    // machine" change) left level.pack_a_punch.custom_validation undefined whenever any machine was
    // found, so stock SKIPPED our validate and ran the stock float-pack ("place gun inside") for
    // EVERY gun - the custom in-place tier system was fully bypassed. Bind the singular handle stock
    // actually reads; stock calls it with self = whichever trigger was used, so it routes EVERY
    // machine (incl. the 2nd Paradise PaP) through acc_pap_validate. The per-trigger field is kept
    // (harmless) but it is the singular bind that makes PaP work.
    if ( isdefined( level.pack_a_punch ) )
    {
        level.pack_a_punch.custom_validation = &acc_pap_validate;
        if ( n == 0 ) n = 1;
    }
    acc_utility::log( "pap_levels: tier-up custom_validation bound (singular level.pack_a_punch + " + n + " per-trigger)" );

    make_actionfigure_packable();   // let the stock machine SHOW for the no-_up Action Figure (user 2026-06-24 fix)
}

// THE Action Figure PaP-visibility fix (user 2026-06-24). The AF has NO "_up" asset, so stock's
// can_upgrade_weapon() returns false for it (it checks IsDefined( level.zombie_weapons[root].upgrade )),
// and player_use_can_pack_now() therefore HIDES the PaP machine while you hold the AF - you could never
// trigger a pack (the reason "i cant even pap"). Fix: point the AF's .upgrade at ITSELF so the visibility
// gate passes. Stock never actually swaps to it - acc_pap_validate intercepts the AF and returns false
// BEFORE the stock pack/swap runs, doing the in-place tier bump (acc_pap_actionfigure) instead.
function make_actionfigure_packable()
{
    if ( !isdefined( level.zombie_weapons ) ) return;
    w = GetWeapon( "t8_melee_figure" );   // the HELD/inventory form (what GetCurrentWeapon returns at the PaP)
    if ( !isdefined( w ) || w == level.weaponNone ) return;
    if ( !isdefined( level.zombie_weapons[ w ] ) ) return;
    if ( !isdefined( level.zombie_weapons[ w ].upgrade ) )
        level.zombie_weapons[ w ].upgrade = w;   // self-upgrade: satisfies the gate only; real pack is in-place
    acc_utility::log( "pap_levels: Action Figure marked packable (self-upgrade gate fix)" );
}

function player_setup_loop()
{
    level endon( "end_game" );
    level flag::wait_till( "initial_blackscreen_passed" );

    for ( ;; )
    {
        players = GetPlayers();
        for ( i = 0; i < players.size; i++ )
        {
            p = players[ i ];
            if ( !isdefined( p ) || !isplayer( p ) ) continue;
            if ( IS_TRUE( p.acc_pap_setup_done ) ) continue;

            p.acc_pap_setup_done = true;
            if ( !isdefined( p.acc_pap_tier ) ) p.acc_pap_tier = [];
            p thread pap_taken_watcher();
            p thread box_grab_clear_watcher();   // box guns must come out stock (3-tier revamp)
            p thread pap_hud_loop();
        }
        wait 1;
    }
}

// ---------------------------------------------------------------------------
// Tier-tracking SAFETY NET (self = player). acc_do_first_pack now records tier 1 itself
// (we block the stock float pack), so the stock "pap_taken" notify never fires in normal
// play - this watcher is a defensive fallback that still records a tier if any stock pack
// path ever runs. Harmless if it never fires.
// ---------------------------------------------------------------------------

function pap_taken_watcher()
{
    self endon( "disconnect" );

    for ( ;; )
    {
        self waittill( "pap_taken" );
        wait 0.2; // let the weapon swap settle so GetCurrentWeapon is the packed gun

        w = self GetCurrentWeapon();
        if ( !isdefined( w ) ) continue;
        base = acc_weapon_variants::true_base( w );   // strips _acc twin suffix so the tier follows recoil swaps

        if ( !isdefined( self.acc_pap_tier ) ) self.acc_pap_tier = [];
        cur = ( isdefined( self.acc_pap_tier[ base ] ) ? self.acc_pap_tier[ base ] : 0 );
        if ( cur >= ACC_PAP_MAX_TIER )
            continue;   // maxed - no PaP display (user 2026-06-22)

        cur++;
        self.acc_pap_tier[ base ] = cur;
        // PaP tier TOAST removed (user 2026-06-22): no display/indication - only the machine price.
    }
}

// self = player. The Mystery Box must hand over a STOCK gun (user 2026-06-15). Tier 1 is now a
// camo'd BASE form, so is_weapon_upgraded() can no longer keep a re-boxed copy stock - this
// watcher resets the tier of whatever base the box just gave. Stock fires "user_grabbed_weapon"
// on the player when they take a box weapon (_zm_magicbox.gsc:809); after the give settles the
// box weapon is the current weapon, so clearing that base's tier makes the copy stock again.
function box_grab_clear_watcher()
{
    self endon( "disconnect" );

    for ( ;; )
    {
        self waittill( "user_grabbed_weapon" );
        self util::waittill_any_timeout( 1.0, "weapon_change_complete" ); // let the box give settle
        if ( !isdefined( self ) ) return;

        w = self GetCurrentWeapon();
        if ( !isdefined( w ) || w == level.weaponNone ) continue;
        // A box gun is always a BASE form (the box never rolls our "_up" twins). Only clear base
        // forms so a rare BGB crate-power box upgrade isn't wrongly zeroed.
        if ( zm_weapons::is_weapon_upgraded( w ) ) continue;

        base = acc_weapon_variants::true_base( w );
        if ( isdefined( self.acc_pap_tier ) && isdefined( self.acc_pap_tier[ base ] ) )
            self.acc_pap_tier[ base ] = 0;
    }
}

// self = player. Clear acc_pap_tier[ base ] for any base the player no longer carries ANY form
// of (covers wallbuy-over / slot swaps that leave a stale tier so a future stock copy of that
// base would falsely read PaP'd). The box-grab clear above handles re-boxing the SAME base; this
// catches everything else. Gated so it never fires during a pack / perk drink / laststand -
// windows where the primaries list is transiently incomplete and a legit tier would be dropped.
function prune_lost_tiers()
{
    if ( !isdefined( self.acc_pap_tier ) ) return;
    if ( IS_TRUE( self.laststand ) || IS_TRUE( self.acc_pap_busy ) ) return;
    if ( isdefined( self.is_drinking ) && self.is_drinking > 0 ) return;

    held = [];
    guns = self GetWeaponsListPrimaries();
    eq = self GetCurrentWeapon();
    if ( isdefined( eq ) && eq != level.weaponNone ) guns[ guns.size ] = eq;
    for ( i = 0; i < guns.size; i++ )
    {
        g = guns[ i ];
        if ( !isdefined( g ) || g == level.weaponNone ) continue;
        b = acc_weapon_variants::true_base( g );
        if ( isdefined( b ) && b != level.weaponNone ) held[ b ] = true;
    }

    keys = getarraykeys( self.acc_pap_tier );
    for ( i = 0; i < keys.size; i++ )
    {
        k = keys[ i ];
        if ( self.acc_pap_tier[ k ] <= 0 ) continue;
        if ( !IS_TRUE( held[ k ] ) ) self.acc_pap_tier[ k ] = 0;
    }
}

// PaP tier for `weapon` on `player` (0..3). Twin-aware (keyed by acc_weapon_variants::true_base
// so the tier follows recoil/fire swaps). 3-tier revamp: a BASE gun reads its stored tier
// directly (0 = stock / box-fresh, 1 = camo'd first pack) - the box-grab clear + possession prune
// keep a box copy at 0, so a base gun never shows phantom PaP. An engine-"_up" gun is the tier-2
// transform form or higher; clamp up defensively if our record ever lagged behind the asset.
function get_tier( player, weapon )
{
    if ( !isdefined( weapon ) || weapon == level.weaponNone || !isdefined( player.acc_pap_tier ) ) return 0;
    base = acc_weapon_variants::true_base( weapon );   // twin-aware: tier follows recoil/fire swaps
    stored = ( isdefined( player.acc_pap_tier[ base ] ) ? player.acc_pap_tier[ base ] : 0 );
    if ( zm_weapons::is_weapon_upgraded( weapon ) && stored < 2 ) return 2;
    return stored;
}

// Tier for the INFO CARD. get_tier already clamps an "_up" gun to >= 2, so this is now a thin
// pass-through (kept for callers / future divergence).
function get_card_tier( player, weapon )
{
    return get_tier( player, weapon );
}

// PaP damage ladder (LINEAR): each pack adds +33.33% of base (a flat +1/3 each tier), so the
// body-shot multiplier is 1.3333 / 1.66666 / 1.999999 = +33.33% / +66.66% / ~+100% over base - T3
// MAX = DOUBLE damage (user 2026-06-24). Returned as a layer for _acc_damage's ADDITIVE bonus_sum
// (a "+33%" = a 1.3333 layer; bonus_factor is the literal sum of layers, _acc_damage.gsc:427-430).
// The "% is the only damage lever" model (user 2026-06-16): acc_weapon_balance_mult normalizes every
// form (base/_up/twin) per gun, so the "_up" transform's own raw damage doesn't double-count - this
// ladder IS the PaP damage progression.
function pap_tier_mult( tier )
{
    switch ( tier )
    {
    case 1: return 1.3333;     // +33.33% over base
    case 2: return 1.66666;    // +66.66% (another +33.33% of base)
    case 3: return 1.999999;   // ~+100% MAX (double damage)
    }
    return 1.0; // tier 0 (not packed)
}

function tier_benefit( tier )
{
    switch ( tier )
    {
    // Vague by design (docs/50): the "PaP TIER N/3" prefix shows progress; the benefit hides the % (exact in docs/05).
    case 1: return "more damage + camo. Pack again to TRANSFORM the gun (tier 2).";
    case 2: return "much more damage + upgraded form (explosive / akimbo / etc.)";
    case 3: return "greatly increased damage (MAX)";
    }
    return "";
}

// NOTE: the PaP tier damage multiplier formerly lived here as pap_damage_cb (a
// modifying actor-damage callback). It was consolidated into _acc_damage's
// multiplier chain on 2026-06-14 - see the init() comment and the PaP layer in
// _acc_damage::on_ai_damage. get_tier + pap_tier_mult above remain the source of
// truth that chain reads.

// ---------------------------------------------------------------------------
// HUD: held weapon's tier -> accPapTier clientuimodel (roman-numeral icon, bottom-right)
// ---------------------------------------------------------------------------

function pap_hud_loop()
{
    self endon( "disconnect" );
    level endon( "end_game" );

    // The held weapon's PaP tier is shown as a roman-numeral cyber-shield icon (I/II/III)
    // by acc_hud.lua's CoD.AccPapTierIcon, centered over the gadget HUD circle (bottom-right).
    // It's driven by the accPapTier clientuimodel, which we push here every 0.25s on change
    // (icon hidden at tier 0). This REPLACED the old bottom-right "PaP TIER x/3" font string
    // (user 2026-06-16) - the same get_tier value perk_info pushes for the PaP card, so the
    // two writers never disagree. set_pap_tier clamps; prune keeps box-fresh bases at 0.
    last_pushed = -1;

    for ( ;; )
    {
        wait 0.25;
        if ( !isdefined( self ) ) return;

        self prune_lost_tiers();   // keep box-fresh / dropped bases at tier 0

        tier = get_tier( self, self GetCurrentWeapon() );
        if ( tier != last_pushed )
        {
            acc_lui::set_pap_tier( self, tier );
            last_pushed = tier;
        }
    }
}
