// =============================================================================
// _acc_kortifex.gsc - KORTIFEX THE DEATHLESS announcer (user 2026-07-12)
//
// Full-map announcer migration to the Vanguard Zombies Kortifex VO
// ([West] Kortifex Announcer pack, westchief596). Two halves:
//
//   1) STOCK OVERRIDES (zero code, ride the pack CSV): the pack's
//      share\raw\sound\aliases\west\vg_kortifex_ann.csv REDEFINES the stock
//      vox_zmba_* announcer aliases, so everything that already talks keeps
//      working but speaks Kortifex: powerup grabs (insta-kill / double points /
//      nuke "Kaboom" / max ammo / fire sale / death machine "Full Power" /
//      bonus points), the AW box "bye bye" (driver fires "boxmove"), the
//      Apothicon Fury spawn ("dogstart" sendoffs), and the zmb_laugh_child
//      game-over laugh.
//
//   2) THIS MODULE: wires the 29 pack wavs the shipped CSV leaves silent
//      (aliased by sound/aliases/acc_kortifex_extra.csv, generated by
//      tools/oneshots/gen_kortifex_extra_aliases.js) through the SAME stock
//      announcer engine - we EXTEND the zm_audio::sndAnnouncerVoxAdd registry
//      (public, prefix "vox_zmba_") and play via sndAnnouncerPlayVox, so the
//      stock one-at-a-time gate (level.zmAnnouncerTalking - overlapping lines
//      are DROPPED, never queued) serializes us with the stock powerup lines
//      for free. On top we keep our own min-gap stamps so flavor lines can't
//      spam. What this module adds:
//
//      - MEDALS (VG multikill VO): kill CHAIN (<=2.5s between kills) ladder
//        8 Carnage / 12 Slaughter / 16 Butcher / 20 Massacre / 25 Bloodbath /
//        30 Extermination; one-blast BURST (<=400ms) >=6 explosive = Big Bang,
//        >=8 any = Excessive Force; 5 consecutive headshot kills = Deadeye
//        (zombie.damagelocation, stock-set at death - _zm_spawner.gsc:1790
//        precedent); 8-chain all while moving = Jackrabbit. Global 25s medal
//        gap so a train wipe = ONE line, not six.
//      - BOSS: first "acc_boss_spawned" of a round = a dogstart sendoff
//        ("fetch me their souls" / "tear them to pieces" - the _1 variant the
//        stock registry never plays), later same-round spawns = the roar.
//      - RANDOM PERK: "Random perk!" on zm_perks::give_random_perk - the two
//        sites (_acc_emergency_drop / _acc_glitch_altar) call the
//        level.acc_kx_announce_random_perk fn-pointer (nil-guarded, so NO
//        cross-module #using).
//      - ELIMINATIONS: player bleeds out = "player eliminated"/"Elimination".
//      - QUIPS: down = "Naughty"/"Naughty or nice" (40%), revive = "Nice"
//        (35%) - the VG holiday-event reaction lines, repurposed.
//      - TAUNTS: rare round-start flavor from the 12 VG holiday-event taunts
//        ("Season's BEATINGS, mortals"...). Default 25%/round, >=3 rounds
//        apart, 9-14s into the round, skipped near boss activity. Tunables:
//        acc_kortifex_taunt_pct (0 = off) / acc_kortifex_on (module kill-switch).
//
// UNWIRED (6 wavs, no matching mechanic): timer frozen / cranked / time
// extended / gun game (VG mode lines), max armor (no armor system), ammo mod
// (no AAT system). See docs/05 SS Announcer.
// =============================================================================

#using scripts\shared\flag_shared;
#using scripts\shared\util_shared;

#using scripts\zm\_zm_audio;      // sndAnnouncerVoxAdd / sndAnnouncerPlayVox (stock registry we extend; NOT private)
#using scripts\zm\_zm_spawner;    // register_zombie_death_event_callback (medal kill feed)

#using scripts\zm\zm_abandoned_cyber_city\_acc_utility;

#insert scripts\shared\shared.gsh;

// Medal engine tunables (announcer types = "acc_medal_*", aliases vox_zmba_acc_medal_*_0
// in acc_kortifex_extra.csv). #defines live ABOVE #namespace (directive-order lint).
#define ACC_KX_CHAIN_GAP_MS   2500    // max ms between kills to keep a chain alive
#define ACC_KX_BURST_MS       400     // one-blast window (Thundergun / Havoc / nuke wipe)
#define ACC_KX_MEDAL_GAP_MS   25000   // min ms between medal lines (a horde wipe = ONE line)
#define ACC_KX_QUIP_GAP_MS    8000    // min ms between flavor quips (down/revive/taunt)
#define ACC_KX_MOVE_SPEED_SQ  22500   // 150 u/s squared - "moving" threshold for Jackrabbit

#namespace acc_kortifex;

function init()
{
	if ( getdvarint( "acc_kortifex_on", 1 ) != 1 ) return;   // live kill-switch (NOT a dev flag)

	register_lines();

	level.acc_kx_last_line_ms  = -100000;   // our min-gap stamp (stock gate handles overlap)
	level.acc_kx_last_medal_ms = -100000;
	level.acc_kx_boss_round    = -1;        // round of the last acc_boss_spawned (sendoff-vs-roar)
	level.acc_kx_last_boss_ms  = -100000;
	level.acc_kx_last_taunt_round = -99;

	// Random-perk announce hook: the give_random_perk sites call this nil-guarded
	// fn-pointer, so neither module needs a #using on us (absent = silent no-op).
	level.acc_kx_announce_random_perk = &announce_random_perk;

	zm_spawner::register_zombie_death_event_callback( &on_zombie_death_medals );

	level thread boss_spawn_watch();
	level thread round_taunt_watch();
	level thread connect_watch();

	acc_utility::log( "kortifex: announcer online (medals + boss + quips + taunts)" );
}

// Extend the stock announcer registry. sndAnnouncerPlayVox plays "vox_zmba_" + suffix
// (_zm_audio.gsc:1295 ZOMBIE_ANNOUNCER_PREFIX) - the stock types (insta_kill, nuke,
// boxmove, dogstart, ...) are already registered by sndAnnouncer_Init and now resolve
// to Kortifex via the pack's override CSV; these are OUR additions on top.
function register_lines()
{
	zm_audio::sndAnnouncerVoxAdd( "acc_bossround",    "event_dogstart_1" );   // pack alias; stock registry only ever plays _0
	zm_audio::sndAnnouncerVoxAdd( "acc_roar",         "acc_roar_0" );
	zm_audio::sndAnnouncerVoxAdd( "acc_random_perk",  "acc_random_perk_0" );
	zm_audio::sndAnnouncerVoxAdd( "acc_elim_0",       "acc_elim_0" );
	zm_audio::sndAnnouncerVoxAdd( "acc_elim_1",       "acc_elim_1" );
	zm_audio::sndAnnouncerVoxAdd( "acc_down_0",       "acc_down_0" );
	zm_audio::sndAnnouncerVoxAdd( "acc_down_1",       "acc_down_1" );
	zm_audio::sndAnnouncerVoxAdd( "acc_revive_0",     "acc_revive_0" );

	medals = medal_types();
	for ( i = 0; i < medals.size; i++ )
		zm_audio::sndAnnouncerVoxAdd( medals[ i ], medals[ i ] + "_0" );

	for ( i = 0; i < 12; i++ )
		zm_audio::sndAnnouncerVoxAdd( "acc_taunt_" + i, "acc_taunt_" + i );
}

function medal_types()
{
	m = [];
	m[ m.size ] = "acc_medal_carnage";
	m[ m.size ] = "acc_medal_slaughter";
	m[ m.size ] = "acc_medal_butcher";
	m[ m.size ] = "acc_medal_massacre";
	m[ m.size ] = "acc_medal_bloodbath";
	m[ m.size ] = "acc_medal_extermination";
	m[ m.size ] = "acc_medal_bigbang";
	m[ m.size ] = "acc_medal_excessive";
	m[ m.size ] = "acc_medal_deadeye";
	m[ m.size ] = "acc_medal_jackrabbit";
	return m;
}

// ---------------------------------------------------------------------------
// Core play gate. Stock sndAnnouncerPlayVox DROPS a line if one is already
// playing (level.zmAnnouncerTalking) - we mirror that check BEFORE stamping our
// min-gap so a dropped line doesn't burn the cooldown, then stamp and fire.
// Returns true if the line was actually dispatched.
// ---------------------------------------------------------------------------
function announce( type, min_gap_ms )
{
	if ( !isdefined( min_gap_ms ) ) min_gap_ms = ACC_KX_QUIP_GAP_MS;
	if ( IS_TRUE( level.zmAnnouncerTalking ) ) return false;                       // stock gate would drop it
	if ( GetTime() - level.acc_kx_last_line_ms < min_gap_ms ) return false;        // our anti-spam gap
	level.acc_kx_last_line_ms = GetTime();
	level thread zm_audio::sndAnnouncerPlayVox( type );
	return true;
}

function announce_random_perk()
{
	announce( "acc_random_perk", 2000 );   // short gap: it should beat the perk jingle
}

// ---------------------------------------------------------------------------
// BOSS: first spawn of a round gets the sendoff, later spawns get the roar.
// Rides the same universal "acc_boss_spawned" notify the nameplate consumes
// (fired by core/Avogadro/Panzer/Phantom; the glitch boss opts out by design).
// ---------------------------------------------------------------------------
function boss_spawn_watch()
{
	level endon( "end_game" );

	for ( ;; )
	{
		level waittill( "acc_boss_spawned", boss, name );
		level.acc_kx_last_boss_ms = GetTime();

		if ( level.round_number != level.acc_kx_boss_round )
		{
			level.acc_kx_boss_round = level.round_number;
			// random sendoff: stock "dogstart" = "fetch me their souls" (_0),
			// our "acc_bossround" = "tear them to pieces" (_1).
			type = ( ( RandomInt( 2 ) == 0 ) ? "dogstart" : "acc_bossround" );
			announce( type, 1500 );
		}
		else
		{
			announce( "acc_roar", 4000 );
		}
	}
}

// ---------------------------------------------------------------------------
// TAUNTS: rare round-start flavor. Never on back-to-back rounds, never right
// on top of boss activity, and lands 9-14s in so it doesn't fight the round
// stinger. acc_kortifex_taunt_pct 0 silences just the taunts.
// ---------------------------------------------------------------------------
function round_taunt_watch()
{
	level endon( "end_game" );

	for ( ;; )
	{
		level waittill( "acc_round_start", round_number );

		pct = getdvarint( "acc_kortifex_taunt_pct", 25 );
		if ( pct <= 0 ) continue;
		if ( round_number - level.acc_kx_last_taunt_round < 3 ) continue;
		if ( RandomInt( 100 ) >= pct ) continue;

		wait RandomFloatRange( 9.0, 14.0 );

		if ( GetTime() - level.acc_kx_last_boss_ms < 20000 ) continue;   // boss just talked/spawned
		if ( level.acc_kx_last_taunt_round == round_number ) continue;

		if ( announce( "acc_taunt_" + RandomInt( 12 ), ACC_KX_QUIP_GAP_MS ) )
			level.acc_kx_last_taunt_round = round_number;
	}
}

// ---------------------------------------------------------------------------
// PLAYER QUIPS: down / bleed-out / revive.
// ---------------------------------------------------------------------------
function connect_watch()
{
	for ( i = 0; i < level.players.size; i++ )
		level.players[ i ] thread player_quip_watch();

	for ( ;; )
	{
		level waittill( "connected", player );
		player thread player_quip_watch();
	}
}

function player_quip_watch()
{
	self endon( "disconnect" );

	for ( ;; )
	{
		msg = self util::waittill_any_return( "player_downed", "bled_out", "player_revived" );

		if ( msg == "bled_out" )
		{
			announce( "acc_elim_" + RandomInt( 2 ), 2000 );   // always worth saying
		}
		else if ( msg == "player_downed" )
		{
			if ( RandomInt( 100 ) < 40 )
				announce( "acc_down_" + RandomInt( 2 ), ACC_KX_QUIP_GAP_MS );
		}
		else // player_revived
		{
			if ( RandomInt( 100 ) < 35 )
				announce( "acc_revive_0", ACC_KX_QUIP_GAP_MS );
		}
	}
}

// ---------------------------------------------------------------------------
// MEDALS: per-attacker chain / burst / headshot / mobility counters, fed by the
// stock zombie-death event (self = the zombie, attacker = the killer). Cheap:
// arithmetic only, no spawns. Boss/elite deaths count as +1 like any kill.
// ---------------------------------------------------------------------------
function on_zombie_death_medals( attacker )
{
	if ( !isdefined( attacker ) || !isplayer( attacker ) ) return;

	now = GetTime();

	if ( !isdefined( attacker.acc_kx_last_kill_ms ) || ( now - attacker.acc_kx_last_kill_ms ) > ACC_KX_CHAIN_GAP_MS )
	{
		attacker.acc_kx_chain      = 0;
		attacker.acc_kx_chain_tier = 0;      // highest ladder tier already announced this chain
		attacker.acc_kx_hs_chain   = 0;
		attacker.acc_kx_move_chain = 0;
		attacker.acc_kx_move_done  = false;
		attacker.acc_kx_burst_ms   = now;
		attacker.acc_kx_burst      = 0;
		attacker.acc_kx_burst_done = false;
	}
	attacker.acc_kx_last_kill_ms = now;
	attacker.acc_kx_chain++;

	// one-blast burst window (rolls forward when a blast pauses >400ms)
	if ( ( now - attacker.acc_kx_burst_ms ) > ACC_KX_BURST_MS )
	{
		attacker.acc_kx_burst_ms   = now;
		attacker.acc_kx_burst      = 0;
		attacker.acc_kx_burst_done = false;
	}
	attacker.acc_kx_burst++;

	// headshot chain (zombie.damagelocation is stock-set on the killing hit; may be
	// undefined for script kills - T7 THROWS on string == undefined, so guard first)
	loc = self.damagelocation;
	if ( isdefined( loc ) && ( loc == "head" || loc == "helmet" ) )
		attacker.acc_kx_hs_chain++;
	else
		attacker.acc_kx_hs_chain = 0;

	// mobility chain (kill registered while the killer is moving)
	vel = attacker GetVelocity();
	if ( LengthSquared( vel ) > ACC_KX_MOVE_SPEED_SQ )
		attacker.acc_kx_move_chain++;
	else
		attacker.acc_kx_move_chain = 0;

	// ---- pick the best NEW medal this kill (burst > ladder > deadeye > jackrabbit) ----
	medal = undefined;

	if ( !IS_TRUE( attacker.acc_kx_burst_done ) )
	{
		mod = self.damagemod;
		explosive = isdefined( mod )
			&& ( IsSubStr( mod, "GRENADE" ) || IsSubStr( mod, "EXPLOSIVE" ) || IsSubStr( mod, "PROJECTILE" ) );
		if ( attacker.acc_kx_burst >= 8 )
		{
			medal = "acc_medal_excessive";
			attacker.acc_kx_burst_done = true;
		}
		else if ( attacker.acc_kx_burst >= 6 && explosive )
		{
			medal = "acc_medal_bigbang";
			attacker.acc_kx_burst_done = true;
		}
	}

	if ( !isdefined( medal ) )
	{
		tier = chain_tier( attacker.acc_kx_chain );
		if ( tier > attacker.acc_kx_chain_tier )
		{
			attacker.acc_kx_chain_tier = tier;
			medal = chain_medal( tier );
		}
	}

	if ( !isdefined( medal ) && attacker.acc_kx_hs_chain >= 5 )
	{
		medal = "acc_medal_deadeye";
		attacker.acc_kx_hs_chain = 0;
	}

	if ( !isdefined( medal ) && attacker.acc_kx_move_chain >= 8 && !IS_TRUE( attacker.acc_kx_move_done ) )
	{
		medal = "acc_medal_jackrabbit";
		attacker.acc_kx_move_done = true;
	}

	if ( !isdefined( medal ) ) return;
	if ( ( now - level.acc_kx_last_medal_ms ) < ACC_KX_MEDAL_GAP_MS ) return;   // one line per horde
	if ( announce( medal, 1500 ) )
		level.acc_kx_last_medal_ms = now;
}

function chain_tier( n )
{
	if ( n >= 30 ) return 6;
	if ( n >= 25 ) return 5;
	if ( n >= 20 ) return 4;
	if ( n >= 16 ) return 3;
	if ( n >= 12 ) return 2;
	if ( n >= 8 )  return 1;
	return 0;
}

function chain_medal( tier )
{
	if ( tier == 6 ) return "acc_medal_extermination";
	if ( tier == 5 ) return "acc_medal_bloodbath";
	if ( tier == 4 ) return "acc_medal_massacre";
	if ( tier == 3 ) return "acc_medal_butcher";
	if ( tier == 2 ) return "acc_medal_slaughter";
	return "acc_medal_carnage";
}
