// =============================================================================
// _acc_weapon_variants.gsc - perk/ability weapon-variant SWAP framework
//
// Design reference: docs/10_perks.md (Deadshot §7, Double Tap §4),
// docs/21_adding_a_gun_runbook.md, docs/21_adding_a_gun_runbook.md §4-5,
// docs/04_weapons.md (Stabilizer weapon ability).
//
// THE PROBLEM (verified 2026-06-14 audit): recoil and fire rate are baked
// weapon-GDT properties. The engine exposes NO per-player recoil or fire-rate
// setter on a live weapon (grep-proven: zero Set*FireRate / Set*Recoil builtins,
// zero fire-rate dvar; those fields are read-only). The only way to give a player
// reduced-recoil or faster-firing guns is to SWAP the weapon for a cloned twin
// whose GDT SCALES the recoil tables / lowers fireTime, then swap the base back
// when the perk/ability ends. This module is that swap engine.
//
// WHAT IT DELIVERS (the real perk magnitudes - docs/10_perks.md), as
// independent twin AXES (one weapon-stat effect each, cross-producted per gun):
//   - Deadshot base:              NO recoil twin (recoil reduction is Mega-only since 2026-06-16)
//   - Deadshot Mega (Am. Sniper): -50% recoil -> "recoil50" twin (recoil x0.50 of the 1.75x map base -> ~0.875x vanilla)
//   - Speed Cola Mega (Sleight Expert): +75% reload -> "fastreload" twin (reloadTime x0.857, on top of engine +50%)
//   - Turbocharger implant (boss item 8): "turbo" twin, HAVOC-ONLY (sprintOutTime 0.98 -> 0.2; added 2026-07-08).
//     The first GUN-SCOPED axis: the token is active for every gun but twins are baked ONLY for
//     apex_beam_rifle (allow-list filter) - the trailing-token drop degrades all other guns.
//   (Deadshot base +1.5 / Mega +2 headshot and DT base +33% RoF are NOT here -
//    headshot is _acc_damage; the +33% is engine-granted free off the specialty.)
//   - Mule Kick Mega "The Armory" (ammo) REMOVED 2026-06-16 -> runtime round-start refill, not a twin.
//   - Double Tap Mega "Gun Slinger" (fastfire: +45% RoF / -50% swap) REMOVED 2026-07-04 ->
//     Mega Double Tap is now a pure DAMAGE buff (extra-bullet temper x0.6 -> x0.8 in _acc_damage),
//     so it needs no twin.
//   - Speed-Cola-ONLY wonders/specials (user 2026-07-08): Mahem / Thundergun / Fire Bow bake JUST
//     "_acc_fastreload" (5 hand-cloned forms - the bow has no _up; Thundergun's upgrade name is the
//     irregular "thundergun_upgraded"). Their charge/fling behaviors needed twin-compat shims:
//     twin_thundergun_fire_shim below + the bow family-name normalize in _zm_weap_elemental_bow.
//   CURRENT MATRIX (2026-07-08): 3 axes; 22 full guns x (recoil50 x fastreload) x 2 forms = 132
//   + 8 Havoc turbo + 5 wonder fastreload = 145 twins total, ~85 under the ~230 boot-proven cap.
//
// BAKED + ACTIVE (2026-06-14; SLIMMED 2026-06-16): the twin matrix is generated by
// tools/apply_recoil_overhaul.js into source_data/acc_weapon_variants.gdt, listed in
// the zone (weaponfull,*) AND in build_available_twins(), with dvar default
// `acc_weapon_variants 1`. To ADD a new effect axis, see the EXTENSION POINT banner
// below. Safety net: the allow-list gates GetWeapon so an un-baked combo can never
// throw; on a gun/combo with no twin, the axis no-ops (gun stays on its base form).
//
// PERK-GATED (unlike a flat GDT cap bump): the twin is only ever given to a
// player while they hold the qualifying perk (or fire the timed ability), and is
// stripped the instant they lose it. State is derived LIVE from the perk each
// reconcile, so it survives the death/re-buy cycle (Mega flag is sticky).
// =============================================================================

#using scripts\shared\array_shared;
#using scripts\shared\util_shared;

#insert scripts\shared\shared.gsh;

#using scripts\zm\_zm_weapons;
#using scripts\zm\_zm_weap_thundergun;   // thundergun_fired - the fling driver our twin fire shim re-triggers (stock's own watcher is ==-object gated and misses twins)

#using scripts\zm\zm_abandoned_cyber_city\_acc_utility;

// Default ON (2026-06-14): the recoil twins are baked + the 2.1x-base skill theme
// is a core feature, so the system runs by default. Set dvar `acc_weapon_variants 0`
// to disable. `acc_variants_debug 1` prints each swap to the player (proof-of-life).
#define ACC_VARIANTS_DEFAULT 1

// NOTE: Pack-a-Punch now packs the held gun IN PLACE via _acc_pap_levels (instant swap to
// the packed form, twin or base alike) - there is NO machine animation and NO proximity
// suppression. The gun changes ONLY when you actually pack, so this module no longer has to
// revert twins to base near the machine. packed_form() (below) is the only PaP hook here.

#namespace acc_weapon_variants;

// ---------------------------------------------------------------------------
// Init
// ---------------------------------------------------------------------------

function init()
{
    acc_utility::log( "weapon_variants init (inert until twins baked + acc_weapon_variants 1)" );

    // Known twin suffixes (logical_stem_name strips a trailing one to recover the player's
    // logical weapon). GENERATED from variant_dims() - list order is irrelevant because no legal
    // suffix is a tail of another (verified programmatically 2026-07-08, scratchpad
    // verify_twin_logic.js CHECK 1 - the old "LONGEST FIRST" hand-ordering rule is obsolete).
    // Legal combos = {optional recoil50} x {optional fastreload} x {optional turbo}. recoil50 is
    // the ONLY recoil twin (Mega Deadshot ONLY; base Deadshot has NO recoil twin since 2026-06-16;
    // x0.50 off the 1.75x base). turbo = Turbocharger implant, HAVOC-only baked forms (2026-07-08).
    // (fastfire/Gun Slinger axis REMOVED 2026-07-04 - Mega Double Tap is a damage buff now.)
    // Trailing variant-suffix strip list for logical_stem_name() - every legal
    // token combination ("_acc_<tok>...", all axes), built from the dims so it stays
    // in sync. Forward-safe: listing a combo whose twin isn't baked yet is harmless.
    level.acc_variant_suffixes = build_variant_suffixes();

    // Variant AXES in CANONICAL ORDER (= the order tokens appear in a twin name) -
    // MUST match tools/apply_recoil_overhaul.js TWIN_DIMS order. Each is a
    // function(self=player) returning its active token or undefined.
    // >>> ADD A NEW PERK/ABILITY EFFECT by appending its axis here (and a matching
    // dim in variant_dims() + the built combos in build_available_twins). See the
    // "EXTENSION POINT" banner above the axis functions. <<<
    level.acc_variant_axes = array( &axis_recoil, &axis_reload, &axis_turbo, &axis_lev_speed );   // ammo axis removed 2026-06-16 (Armory = runtime refill); FIRE axis removed 2026-07-04 (Mega Double Tap = damage buff in _acc_damage); TURBO axis added 2026-07-08 (Turbocharger implant -> Havoc sprintOutTime 0.2 twin); SPD axis added 2026-07-09 (Leviathan Axe +5% swing per PaP tier - LEVIATHAN-only twins, trailing token so every other gun degrades to its other twins)

    // Allow-list of twin weapon names that ACTUALLY EXIST in the build. We only
    // ever GetWeapon() a name in here, so an un-baked twin cannot throw. POPULATE
    // this as you bake twins in APE (docs/21 §4-5). Empty = whole system inert.
    level.acc_variant_available = build_available_twins();

    // Make the PaP'd ("_up") twins first-class engine UPGRADES so the Pack-a-Punch
    // HUD / tier-up / re-pack all recognize a held twin (fixes "PaP indicator breaks").
    register_twin_upgrades();

    // Make the un-upgraded ("base") twins PACKABLE by the stock PaP machine, so the
    // interact prompt SHOWS while you hold a perk-swapped twin (fixes "some guns have no
    // Pack-a-Punch option at all"). Must run AFTER the stock CSV weapons are registered.
    register_twin_box_weapons();

    // Same engine-upgrade registration, but for NON-twinned box guns whose ported _up form the engine
    // left unmapped. DEFENSIVE NET ONLY - NOT the Mahem fix. (We long thought this fixed the Mahem "only
    // packs twice"; it did NOT - stock add_zombie_weapon line 554 ALREADY maps every CSV upgrade, so
    // is_weapon_upgraded(s1_mahem_up) was always true and this loop SKIPS the Mahem. The real blocker was
    // the Mahem's AAT exemption hiding the PaP machine after pack 2 - fixed in
    // _acc_pap_levels::make_mahem_pap_visible_to_tier3.) Kept for any future port stock genuinely doesn't
    // map. Must run AFTER the stock CSV weapons are registered (same precondition as the twin pass above).
    register_special_upgrades();
}

// Register every PaP'd ("_up") twin in level.zombie_weapons_upgraded (twin OBJECT ->
// true-base OBJECT) - the exact table stock add_zombie_weapon writes (_zm_weapons.gsc:554).
// Result: is_weapon_upgraded(_up twin) = true and get_base_weapon(_up twin) = base
// NATIVELY, so _acc_pap_levels + the stock PaP machine read a held _up twin correctly.
//
// ONLY the _up twins are registered - the un-PaP'd base twins (e.g. t9_ak47_acc_recoil50 with
// NO _up) must stay un-upgraded, or the FIRST pack would skip tier 1. We never add
// twins to level.zombie_weapons / zombie_include_weapons, so the Mystery Box can't roll them.
function register_twin_upgrades()
{
    if ( !isdefined( level.zombie_weapons_upgraded ) ) level.zombie_weapons_upgraded = [];

    keys = getarraykeys( level.acc_variant_available );
    n = 0;
    for ( i = 0; i < keys.size; i++ )
    {
        name = keys[ i ];
        tw = GetWeapon( name );
        if ( !isdefined( tw ) || tw == level.weaponNone ) continue;

        stem_w = GetWeapon( logical_stem_name( name ) );   // strip _acc -> base or _up form
        if ( !isdefined( stem_w ) || stem_w == level.weaponNone ) continue;

        // Only PaP'd twins are "upgrades": a base twin's stem is the un-upgraded base.
        if ( !( zm_weapons::is_weapon_upgraded( stem_w ) ) ) continue;

        level.zombie_weapons_upgraded[ tw ] = zm_weapons::get_base_weapon( stem_w );
        n++;
    }
    acc_utility::log( "weapon_variants: registered " + n + " _up twins as engine upgrades" );
}

// Same idea for NON-twinned box guns. A ported special (the AW Mahem: s1_mahem -> s1_mahem_up) can
// reach the box + PaP, but the engine never put its _up form in level.zombie_weapons_upgraded - so
// is_weapon_upgraded(s1_mahem_up) is FALSE and get_base_weapon(s1_mahem_up) does NOT strip to the base.
// That breaks the PaP tier key (the tier is stored at key s1_mahem on packs 1-2, but a held _up reads
// key s1_mahem_up at pack 3) AND the is_weapon_upgraded clamp that normally bridges that gap -> get_tier
// returns 0, the pack routes back to acc_do_first_pack which finds no upgrade to apply, and the gun
// "only packs twice" (user 2026-06-26). Register the _up of every base box weapon whose upgrade the
// engine left unmapped. Idempotent: skips any _up that already maps back to its base natively (every
// stock gun + the twins handled above), so we only patch the broken ports.
//
// KEY-MISMATCH HARDENING (user 2026-06-26, "must be 100% correct"): verified vs the real stock
// _zm_weapons.gsc - stock add_zombie_weapon keys level.zombie_weapons_upgraded by the RAW upgrade
// OBJECT (:554 `level.zombie_weapons_upgraded[upgrade] = weapon`), but the LOOKUPS that gate the PaP
// (is_weapon_upgraded :1736 / get_base_weapon :1630 / can_upgrade_weapon - machine visibility) normalize
// the held weapon FIRST: `get_nonalternate_weapon(w).rootWeapon`. For a conventional gun those coincide;
// for an AW launcher port like the Mahem the held s1_mahem_up can normalize to a DIFFERENT object (alt-fire
// form / a non-identity rootWeapon) than the raw upgrade object stock keyed by - so the raw-keyed mapping is
// never hit. Registering the raw object ALONE (what stock already did, and the first cut of this fix) would
// therefore still miss. So we register under EVERY key a held copy can normalize to: the raw upgrade, its
// rootWeapon, and the non-alternate form + its rootWeapon. Setting extra keys is harmless - an _up form's
// root/alt is itself or its alt-fire twin, never a real base gun - so this can only ever make MORE held
// _up copies resolve to their base, which is exactly correct.
function register_special_upgrades()
{
    if ( !isdefined( level.zombie_weapons ) ) return;
    if ( !isdefined( level.zombie_weapons_upgraded ) ) level.zombie_weapons_upgraded = [];

    keys = getarraykeys( level.zombie_weapons );
    n = 0;
    for ( i = 0; i < keys.size; i++ )
    {
        base = keys[ i ];
        if ( !isdefined( base ) || base == level.weaponNone ) continue;
        if ( zm_weapons::is_weapon_upgraded( base ) ) continue;   // this IS an _up form, not a base

        up = level.zombie_weapons[ base ].upgrade;
        if ( !isdefined( up ) || up == level.weaponNone || up == base ) continue;   // no real upgrade form

        // Already mapped correctly (stock guns + register_twin_upgrades)? leave it alone. is_weapon_upgraded
        // here uses the SAME normalized lookup the in-game gate will - so a TRUE here means a held copy
        // already resolves, and only the genuinely-broken ports (the Mahem) fall through to the register.
        if ( zm_weapons::is_weapon_upgraded( up ) && zm_weapons::get_base_weapon( up ) == base ) continue;

        register_upgrade_key( up, base );                         // raw upgrade object + its rootWeapon
        nonalt = zm_weapons::get_nonalternate_weapon( up );       // alt-fire -> primary form (identity for non-alt)
        if ( isdefined( nonalt ) && nonalt != up )
            register_upgrade_key( nonalt, base );                 // + the non-alt form + its rootWeapon
        n++;
    }
    acc_utility::log( "weapon_variants: registered " + n + " non-twin _up form(s) as engine upgrades (Mahem fix)" );
}

// Map a weapon AND its rootWeapon -> base in level.zombie_weapons_upgraded. The stock PaP lookups
// normalize a held weapon to `get_nonalternate_weapon(w).rootWeapon` before the table read, so the
// rootWeapon key is the one that actually gets hit for a no-attachment _up form; the raw key is kept too
// for any path that reads the object directly. Both point at the same base. Field access is via a temp var
// (no chained `.a.b` / no `( call ).field`, per the BO3 GSC primitive-field rule in CLAUDE.md).
function register_upgrade_key( w, base )
{
    if ( !isdefined( w ) || w == level.weaponNone ) return;
    level.zombie_weapons_upgraded[ w ] = base;
    root = w.rootWeapon;
    if ( isdefined( root ) && root != level.weaponNone )
        level.zombie_weapons_upgraded[ root ] = base;
}

// Make the UN-upgraded ("base") variant twins PACKABLE by the STOCK Pack-a-Punch machine.
//
// ROOT CAUSE of the recurring "some guns have no PaP interact option at all" report
// (AE4 / Tac-19 / earlier the pistols, 2026-06-15): the PaP trigger's PROMPT VISIBILITY is
// gated by the stock can_pack_weapon (_zm_pack_a_punch.gsc:253) -> is_weapon_or_base_included
// + can_upgrade_weapon, both of which look up level.zombie_weapons[ weapon.rootWeapon ]. A
// base twin (e.g. s1_ae4_acc_recoil50 - what you HOLD whenever Deadshot Mega /
// Speed Cola Mega / the Turbocharger is active) has rootWeapon == itself and is DELIBERATELY absent
// from level.zombie_weapons (so the Mystery Box can't roll a twin). So the machine decides the
// held weapon is un-packable and SetInvisibleToPlayer-hides the trigger -> no prompt. It read
// as random because it is perk-gated and twin-only (the 5 variant_guns), "moving" to whichever
// twin gun you happen to hold with a qualifying perk. NOT max-tier, NOT the akimbo CSV bug.
//
// FIX: register each base twin in level.zombie_weapons mirroring its base gun's struct
// (.upgrade -> the packed twin) but with is_in_box = FALSE. is_weapon_included +
// can_upgrade_weapon now pass so the prompt shows, while the box still skips it
// (treasure_chest_CanPlayerReceiveWeapon gates on get_is_in_box, _zm_magicbox.gsc:1222). The
// actual pack is unchanged - our acc_pap_validate custom_validation still does the in-place
// first-pack and returns false, so the stock float pack never runs. The PaP'd ("_up") twins
// already show the prompt via the AAT re-pack path, so ONLY the base twins need this.
function register_twin_box_weapons()
{
    if ( !isdefined( level.zombie_weapons ) ) return;

    guns = variant_guns();
    suffixes = build_variant_suffixes();   // every legal "_acc_<combo>"
    n = 0;
    for ( gi = 0; gi < guns.size; gi++ )
    {
        base_name = guns[ gi ];
        base_w = GetWeapon( base_name );
        if ( !isdefined( base_w ) || base_w == level.weaponNone ) continue;
        if ( !isdefined( level.zombie_weapons[ base_w ] ) ) continue;   // base gun must be CSV-registered first

        base_struct = level.zombie_weapons[ base_w ];

        for ( si = 0; si < suffixes.size; si++ )
        {
            tw_name = base_name + suffixes[ si ];   // base twin "<gun>_acc_<combo>"
            if ( !isdefined( level.acc_variant_available[ tw_name ] ) ) continue;

            tw = GetWeapon( tw_name );
            if ( !isdefined( tw ) || tw == level.weaponNone ) continue;

            key = tw.rootWeapon;   // == tw (a twin has no attachments / rootWeapon override)
            if ( isdefined( level.zombie_weapons[ key ] ) ) continue;   // already registered

            up = try_resolve_twin( variant_up_name( base_name ) + suffixes[ si ] );   // matching packed twin

            struct = SpawnStruct();
            struct.weapon = tw;
            struct.upgrade = ( isdefined( up ) ? up : base_struct.upgrade );   // .upgrade must be defined for can_upgrade_weapon
            struct.weapon_classname = "weapon_" + tw_name + "_zm";
            struct.hint = base_struct.hint;
            struct.cost = base_struct.cost;
            struct.vox = base_struct.vox;
            struct.vox_response = base_struct.vox_response;
            struct.is_wonder_weapon = base_struct.is_wonder_weapon;
            struct.force_attachments = [];
            struct.ammo_cost = base_struct.ammo_cost;
            struct.is_in_box = false;   // KEY: the Mystery Box must NEVER roll a twin

            level.zombie_weapons[ key ] = struct;
            n++;
        }
    }
    acc_utility::log( "weapon_variants: registered " + n + " base twins as PaP-includable (box-excluded)" );
}

// The guns that have twins (imported box guns only - stock guns have no editable
// GDT). On any other gun the perk no-ops (reconcile finds no twin -> stays on base).
// NOTE: s1_tac19 also carries an always-on baseline buff (small range x1.5 + FMJ penetrateType
// large + wider spread x1.25, traded for -15% damage) baked into its base/_up GDT
// (tools/apply_recoil_overhaul.js GUNS.baseline), so its base AND every twin have it. That's a
// GDT-only change; the swap engine here is unaffected (base <-> twin still differ only by
// recoil/fire/reload).
function variant_guns()
{
    // CURRENT (2026-07-09): 22 guns x 6 twins/gun = 132 + 8 Havoc turbo + 5 wonder fastreload
    // (Mahem/Thundergun base+_up, Fire Bow base) + 3 Leviathan spd tier forms = 148 twins, ~80 under
    // the ~230 boot-proven cap. (History: FIRE axis removed 2026-07-04 - recoil50 x fastreload = 3 combos
    // x 2 forms = 6/gun, was 14/gun; XM4 + Streetsweeper added 2026-07-04, Klauser 2026-07-05, hand-gen twins;
    // + Chicom CQB BO2 3-round-burst SMG. user 2026-06-24: + MK14 AW DMR + MORS AW railgun sniper. M60+RPD+RW1
    // twinned 2026-06-23 so EVERY conventional box gun is fully twinned; the Mahem launcher + Thundergun WW are
    // EXEMPT specials). MUST mirror tools/apply_recoil_overhaul.js GUNS. AK-74u/M60/RPD are now Cold War (t9)
    // ports, all with the REGULAR "_up" PaP form. Ripper/Nail/PDW/M1911 were REMOVED (convertible/projectile/
    // akimbo = can't be twinned).
    // ASM1 RETIRED 2026-07-03 (user; zone twin lines commented too) - re-add "s1_asm1" to restore.
    // Blast-O-Matic ADDED 2026-07-03 (user: "make sure it has all twins"): t9_semiauto_cosplay is a
    // PROJECTILEWEAPON, which apply_recoil_overhaul/gen_weapon_variant_gdt refuse - its twins are
    // HAND-BUILT clones in acc_weapon_variants.gdt (scratchpad gen_blasto_twins recipe: canonical
    // TWIN_DIMS mults on the projectile-equivalent fields; the swap path here is name-based and
    // works for any weapon class). XM4 + Streetsweeper ADDED 2026-07-04 (both bulletweapons, twins
    // hand-generated via scratchpad/gen_new_gun_twins.js -> gen_weapon_variant_gdt.js; NOT via a full
    // apply_recoil_overhaul re-run, which would drop Blast-O-Matic's hand-built twins).
    // APEX MIGRATION 2026-07-06: removed t8_paladin_hb50, t6_chicom_cqb, s4_klauser (guns swapped out).
    // APEX TWINS ADDED same day (user: "All guns need to be twinned up" - the migration wrongly shipped
    // them twin-less): all 5 Apex guns, RUNTIME names here (no _zm - the engine strips the baked mode
    // suffix; twin GDT block ids put _zm LAST: apex_X_acc_Y_zm -> runtime apex_X_acc_Y). The 4
    // bulletweapons via scratchpad gen_apex_twins.js -> gen_weapon_variant_gdt.js; the Havoc is a
    // PROJECTILEWEAPON so its 6 twins are HAND-BUILT clones (scratchpad gen_havoc_twins.js, the
    // Blast-O-Matic recipe) - they inherit the charge fields (fireDelay + riser) so spool-up feel is
    // identical on twins. Roster: 22 guns x 6 = 132 twins (CEL-3 twinned 2026-07-06 - was the last twin-less conventional gun) - still well under the ~230 boot-proven cap.
    // FASTRELOAD-ONLY wonders/specials appended 2026-07-08 (user: "Mahem, Thundergun and Fire Bow get
    // the mega speed cola. No changes with deadshot") - they bake JUST the "_acc_fastreload" combo
    // (form_bakes_suffix filters the rest; the subset resolver reaches it even when recoil50 is active).
    // The Fire Bow additionally has NO _up form (it PaPs IN PLACE via acc_firebow_tier).
    // LEVIATHAN appended 2026-07-09 (user: "+10% swing per PaP tier"): the axe bakes ONLY the 3 spd
    // tier twins (base+_acc_spd1 / _up+_acc_spd2 / _up+_acc_spd3 - form_bakes_suffix scopes them);
    // no recoil50/fastreload forms (melee - recoil/reload meaningless). Clones are hand-generated
    // (scratchpad gen_leviathan_spd_twins.js) in acc_weapon_variants.gdt scaling meleeTime+fireTime
    // x0.90 per tier COMPOUNDING off the 0.48/0.52 base (spd1 0.432/0.468, spd2 0.389/0.421,
    // spd3 0.35/0.379; meleeTime = the REAL swing lever on a melee weapon - fireTime does nothing
    // there, the Action Figure speed twins proved it live). Was x0.95 (+5%) same day, user bumped to +10%.
    return array( "s1_tac19", "t6_fiveseven", "t9_ak47", "s1_ae4", "t9_semiauto_cosplay",
                  "s4_ppsh41_base", "t9_grav", "t6_olympia", "t9_ak74u",
                  "t9_m60", "t9_rpd", "s1_rw1", "s1_mk14", "s1_mors",
                  "t9_xm4", "t9_streetsweeper",
                  "apex_peacekeeper", "apex_alternator", "apex_prowler", "apex_g2a4", "s1_cel3",
                  "apex_beam_rifle",
                  "s1_mahem", "thundergun", "elemental_bow_demongate", "leviathan", "t6_war_machine" );
}

// The PaP upgrade asset name for a base gun = "<base>_up" for every box gun, with ONE irregular:
// the Thundergun's upgrade is "thundergun_upgraded" (stock naming, 2026-07-08 fastreload twin).
// MUST mirror the `up` field in tools/apply_recoil_overhaul.js GUNS so the twins and GSC lookups agree.
function variant_up_name( base_name )
{
    if ( base_name == "thundergun" ) return "thundergun_upgraded";
    return base_name + "_up";
}

// Variant DIMENSIONS = the token level(s) per axis, CANONICAL ORDER. ONE source of
// truth, shared by build_variant_suffixes (strip list) and the available-combo menu.
// MUST mirror tools/apply_recoil_overhaul.js TWIN_DIMS order. The "axis inactive"
// level (no token) is implied; list only the real tokens.
function variant_dims()
{
    dims = [];
    dims[ 0 ] = array( "recoil50" );               // axis_recoil  (Deadshot MEGA only, -50%)
    dims[ 1 ] = array( "fastreload" );             // axis_reload  (Speed Cola Mega)
    dims[ 2 ] = array( "turbo" );                  // axis_turbo   (Turbocharger implant; HAVOC-ONLY twins - see build_available_twins)
    dims[ 3 ] = array( "spd1", "spd2", "spd3" );   // axis_lev_speed (Leviathan Axe PaP tier +5% swing/tier; LEVIATHAN-ONLY twins - see form_bakes_suffix. user 2026-07-09)
    // ammo axis REMOVED 2026-06-16: Armory = runtime round-start refill, not a twin.
    // FIRE axis (fastfire) REMOVED 2026-07-04: Mega Double Tap is now a damage buff
    // (extra-bullet temper x0.6 -> x0.8 in _acc_damage), not a fire-rate/swap twin.
    // TURBO axis ADDED 2026-07-08 (user: "0.98 without turbocharger, faster WITH it" - a per-player GDT
    // value only exists as a twin swap): while self.acc_item_turbocharger is set, the Havoc swaps to an
    // "_acc_[...]turbo" clone whose GDT bakes sprintOutTime 0.2 (base Havoc keeps its long 0.98 sprint-out).
    // Turbo is deliberately the LAST dim/token: desired_weapon() drops TRAILING tokens on a miss, so every
    // NON-Havoc gun (no turbo twins baked) still degrades to its recoil50/fastreload twin instead of base.
    // NOTE: tools/apply_recoil_overhaul.js TWIN_DIMS does NOT know this axis - the 8 Havoc turbo clones are
    // hand-generated (scratchpad gen_havoc_turbo_twins.js); never re-run the generator expecting turbo forms.
    return dims;
}

// Every legal "_acc_<tok>..." suffix (cross-product of the dims, minus the all-none
// combo) for logical_stem_name() to strip. Mixed-radix enumeration (no array copies);
// tokens always emit in canonical axis order. Forward-safe (a combo whose twin isn't
// baked is harmless here - it just never appears on a held weapon).
function build_variant_suffixes()
{
    dims = variant_dims();
    radix = [];
    total = 1;
    for ( d = 0; d < dims.size; d++ ) { radix[ d ] = dims[ d ].size + 1; total = total * radix[ d ]; }

    out = [];
    for ( n = 0; n < total; n++ )
    {
        rem = n;
        suffix = "_acc";
        any = false;
        for ( d = 0; d < dims.size; d++ )
        {
            choice = rem % radix[ d ];        // 0 = axis inactive; 1..size = token[choice-1]
            rem = int( rem / radix[ d ] );
            if ( choice > 0 ) { suffix = suffix + "_" + dims[ d ][ choice - 1 ]; any = true; }
        }
        if ( any ) out[ out.size ] = suffix;
    }
    return out;
}

// The twin weapon names that ACTUALLY EXIST in the build. We only ever GetWeapon() a
// name in here, so an un-built twin can never throw. This MUST match the GDT
// (source_data/acc_weapon_variants.gdt) + zone weaponfull lines.
//
// GENERATED from the SAME dims as the GDT + zone (build_variant_suffixes() mirrors
// tools/apply_recoil_overhaul.js TWIN_DIMS / allTwinNames()), so the three can never drift:
// every gun + its _up form crossed with every legal "_acc_<combo>" suffix. The generator bakes
// the FULL cross-product OF THE GLOBAL AXES, so every non-turbo name here exists; desired_weapon()
// still degrades gracefully if a combo is somehow absent. ADD AN AXIS: add a variant_dims() row
// (+ matching TWIN_DIMS + axis fn + level.acc_variant_axes) - this list, the suffixes, and the zone
// all follow. A GUN-SCOPED axis (baked for a subset of guns) additionally needs a filter in the loop
// below - see the turbo precedent.
// CURRENT MATRIX (2026-07-09): global axes recoil50 x fastreload = 3 combos x 22 guns x 2 forms = 132,
// + the HAVOC-ONLY turbo axis (4 turbo combos x 2 forms = 8) + 5 wonder fastreload forms + the
// LEVIATHAN-ONLY spd tier axis (base+spd1, _up+spd2, _up+spd3 = 3) = 148 twins; ~80 under the ~230
// boot-proven cap. (History: was 7 combos = 14/gun = 224 before the 2026-07-04 fastfire removal.)
function build_available_twins()
{
    suffixes = build_variant_suffixes();   // every legal "_acc_<combo>" (incl. turbo combos)

    t = [];
    guns = variant_guns();
    for ( gi = 0; gi < guns.size; gi++ )
    {
        forms = array( guns[ gi ], variant_up_name( guns[ gi ] ) );
        for ( fi = 0; fi < forms.size; fi++ )
        {
            for ( si = 0; si < suffixes.size; si++ )
            {
                if ( !form_bakes_suffix( guns[ gi ], forms[ fi ], suffixes[ si ] ) ) continue;
                t[ forms[ fi ] + suffixes[ si ] ] = true;   // suffix already "_acc_<combo>"
            }
        }
    }
    return t;
}

// Which twin combos are BAKED for a gun/form. The allow-list must NEVER contain a name that does not
// exist in the build - GetWeapon on an unknown name is the "unknown weapon" runtime error the list
// exists to prevent - so every gun-scoped axis/tier gets its filter here (single source of truth).
function form_bakes_suffix( gun, form, suffix )
{
    // TURBO combos: HAVOC ONLY (8 hand-generated clones, 2026-07-08).
    if ( IsSubStr( suffix, "turbo" ) && gun != "apex_beam_rifle" ) return false;

    // SPD (Leviathan PaP-tier swing) combos: LEVIATHAN ONLY, and only the 3 EXACT tier forms
    // (base+spd1 at tier 1; _up+spd2 / _up+spd3 at tiers 2/3 - 3 hand-generated clones, 2026-07-09).
    // Any spd combo on another gun, or a mixed combo (e.g. _acc_fastreload_spd1), is NOT baked.
    if ( IsSubStr( suffix, "spd" ) )
    {
        if ( gun != "leviathan" ) return false;
        if ( form == gun ) return ( suffix == "_acc_spd1" );
        return ( suffix == "_acc_spd2" || suffix == "_acc_spd3" );
    }
    // The axe bakes NOTHING else - no recoil50/fastreload forms (melee: recoil + reload meaningless).
    if ( gun == "leviathan" ) return false;

    // FASTRELOAD-ONLY wonders/specials (user 2026-07-08): Mahem / Thundergun / Fire Bow bake JUST the
    // pure Speed-Cola combo - no recoil50 forms exist for them (recoil is meaningless on a wind cone /
    // launcher / bow, and the user explicitly scoped them to speed cola only). War Machine drum GL
    // joined the tier 2026-07-09 (same launcher logic; blocks in acc_war_machine_twins.gdt).
    if ( gun == "s1_mahem" || gun == "thundergun" || gun == "elemental_bow_demongate" || gun == "t6_war_machine" )
    {
        if ( suffix != "_acc_fastreload" ) return false;
        // The Fire Bow PaPs IN PLACE (CSV upgrade = self; tier lives in acc_firebow_tier) - there is
        // no "_up" weapon at all, so only its BASE form bakes a twin.
        if ( gun == "elemental_bow_demongate" && form != gun ) return false;
    }
    return true;
}

function on_player_connect( player )
{
    // Timed ability overlay (Stabilizer): a struct {recoil, fast, expiry} or undef.
    // Perk-driven state is derived live in reconcile(), never stored.
    player.acc_variant_timed = undefined;
    player thread variant_manager();
    player thread twin_thundergun_fire_shim();
}

// THUNDERGUN TWIN FIRE SHIM (2026-07-08, with the fastreload twin): the BO1-port Thundergun deals
// ZERO GDT damage - EVERYTHING it does is the stock script fling, and stock's per-player watcher
// (_zm_weap_thundergun::wait_for_thundergun_fired:77) triggers it ONLY on == object equality with
// the two stock defs. A held TWIN ("thundergun_acc_fastreload") fires and stock does nothing -> a
// completely dead gun. This shim replicates stock's trigger body verbatim for twin-named thunderguns
// (the fling itself - thundergun_fired -> affect_ais - is weaponless DoDamage, no held re-checks, so
// everything downstream just works). Same finish-the-stock-pipeline pattern as electric cherry.
function twin_thundergun_fire_shim()   // self = player
{
    self endon( "disconnect" );
    self waittill( "spawned_player" );   // mirror stock's watcher lifecycle

    for ( ;; )
    {
        self waittill( "weapon_fired" );
        cur = self GetCurrentWeapon();
        if ( !isdefined( cur ) || cur == level.weaponNone || !isdefined( cur.name ) ) continue;
        if ( !IsSubStr( cur.name, "thundergun" ) || !IsSubStr( cur.name, "_acc_" ) ) continue;   // twins only - stock handles the base forms

        // verbatim stock body (_zm_weap_thundergun.gsc:79-85)
        self thread zm_weap_thundergun::thundergun_fired();
        view_pos = self GetTagOrigin( "tag_flash" ) - self GetPlayerViewHeight();
        view_angles = self GetTagAngles( "tag_flash" );
        PlayFx( level._effect[ "thundergun_smoke_cloud" ], view_pos, AnglesToForward( view_angles ), AnglesToUp( view_angles ) );
    }
}

// ---------------------------------------------------------------------------
// Per-player reconcile loop. Idempotent: each pass brings every carried primary
// into line with the player's desired state (base when nothing is active). Wakes
// on weapon switches / explicit pokes, otherwise ~1/s.
// ---------------------------------------------------------------------------

function variant_manager()
{
    self endon( "disconnect" );

    for ( ;; )
    {
        // weapon_change[_complete] are the stock switch notifies; acc_variant_dirty is
        // our own poke from the perk/ability hooks. The timeout is the SAFETY NET that
        // re-derives state from HasPerk() live, so any edge that doesn't poke us (going
        // DOWN and losing Deadshot, a bleed-out/revive) still converges. Swaps are
        // instant+invisible, so polling is cheap.
        //
        // No PaP proximity special-case anymore: the gun is NEVER force-swapped near the
        // machine (PaP packs in place via _acc_pap_levels, on a twin or base alike), so a
        // flat 3s safety-net poll plus the event wakes (perk pokes / weapon switches) suffice.
        self util::waittill_any_timeout( 3, "acc_variant_dirty", "weapon_change", "weapon_change_complete" );
        self reconcile();
    }
}

// self = player. Bring every carried primary into line with the desired (recoil,
// fast) state.  recoil is 0 / 25 / 40 (percent reduction off the 2.1x base); fast
// is bool.
function reconcile( force )
{
    // Don't re-enter on our own swap's weapon_change (swap_weapon sets this).
    if ( IS_TRUE( self.acc_swapping ) ) return;

    // Don't touch guns while DOWNED: primaries are removed/restored by the laststand
    // flow, and Deadshot may be getting stripped. Defer to after revive - the gun is
    // reconciled then (post-revive weapon_change / the 3s net) against live HasPerk,
    // so a down that loses Deadshot reverts the gun to base once you're back up.
    if ( IS_TRUE( self.laststand ) ) return;

    // Don't swap while the HAVOC CHARGE GATE is live (turbo axis, 2026-07-08): _acc_havoc_charge blanks
    // the held Havoc to 0/0 as its fire-block during the 1.25s wind-up. A swap in that window copies the
    // BLANKED clip/stock onto the new form and the gate's restore then can't find the taken weapon ->
    // all Havoc ammo lost. acc_havoc_gated is set/cleared by the charge loop (max ~1.25s); the 3s net +
    // the next weapon_change/poke reconcile as soon as it clears.
    if ( IS_TRUE( self.acc_havoc_gated ) ) return;

    // Don't fight the stock perk-drink (THE "buying Deadshot ate my ammo" bug).
    // perk_give_bottle_begin (_zm_perks.gsc) captures your gun as `original_weapon`,
    // holsters it for the bottle, raises weapon_change (which wakes our async loop), and
    // perk_give_bottle_end switches BACK to that captured weapon. If we swap base->twin
    // mid-drink, the base it captured is gone -> the switch-back re-gives base with
    // default ammo and the next reconcile copies that (often 0 reserve) onto the twin.
    // So defer: once the drink ends, the switch-back's weapon_change_complete / the 3s
    // safety-net reconciles cleanly on the re-equipped real gun (ammo intact, <=3s).
    // The Mega path (_acc_mega_bottles::replay_perk_drink) IS mid-drink on purpose -
    // it drives its own holstered swap + re-raises the twin - so it passes force=true.
    if ( !IS_TRUE( force ) && isdefined( self.is_drinking ) && self.is_drinking > 0 ) return;

    // Active variant tokens (canonical axis order), derived LIVE from perks. Empty = hold
    // the plain base gun. No Pack-a-Punch proximity suppression: PaP packs the held gun IN
    // PLACE (twin or base alike, via _acc_pap_levels), so the gun never has to revert to
    // base near the machine - it changes ONLY when you actually pack.
    tokens = [];
    if ( variants_enabled() )
        tokens = compute_tokens( self );

    equipped = self GetCurrentWeapon();
    guns = self GetWeaponsListPrimaries();

    // Reconcile the EQUIPPED weapon too: in zombies the starting-pistol slot is not
    // always in GetWeaponsListPrimaries, so add it (deduped) - otherwise Deadshot
    // wouldn't touch the gun you're holding. Non-gun holds (knife/grenade/bottle)
    // have no twin and no-op safely.
    if ( isdefined( equipped ) && equipped != level.weaponNone )
    {
        b_have = false;
        for ( i = 0; i < guns.size; i++ ) { if ( guns[ i ] == equipped ) b_have = true; }
        if ( !b_have ) guns[ guns.size ] = equipped;
    }

    for ( i = 0; i < guns.size; i++ )
    {
        w = guns[ i ];
        if ( !isdefined( w ) || w == level.weaponNone ) continue;

        stem_name = logical_stem_name( w.name );

        if ( tokens.size == 0 )
        {
            // Base state -> the gun should be its plain base form.
            if ( stem_name == w.name ) continue;   // already base, no GetWeapon needed
            desired = GetWeapon( stem_name );        // strip a lingering twin back
        }
        else
        {
            desired = desired_weapon( stem_name, tokens );
        }

        if ( !isdefined( desired ) || desired == level.weaponNone ) continue;
        if ( desired.name == w.name ) continue;     // already correct

        self swap_weapon( w, desired, equipped );
    }
}

// self = player. Replace w_from with w_to, carrying clip + reserve across.
// Mirrors the stock PaP ammo-carry swap (_zm_pack_a_punch.gsc:688-696); a variant
// twin shares the stem's clipSize/maxAmmo (only recoil/fireTime differ), so the
// clip/stock copy across 1:1 with no cap-delta math.
function swap_weapon( w_from, w_to, equipped )
{
    self endon( "disconnect" );

    // Mute reconcile while we swap: GiveWeapon/SwitchToWeapon raise our OWN
    // weapon_change notify, which would otherwise re-wake the manager mid-swap and
    // fight us. reconcile() early-returns while this is set.
    self.acc_swapping = true;

    clip  = self GetWeaponAmmoClip( w_from );
    stock = self GetWeaponAmmoStock( w_from );
    was_equipped = ( w_from == equipped );

    // Re-give the twin with no options. (Gold PaP camo removed 2026-06-27 - there is no longer a
    // camo option to preserve across a Deadshot / Speed Cola perk-twin swap; the PaP
    // tier itself rides player.acc_pap_tier[ true_base ], independent of the held asset.)
    self GiveWeapon( w_to );
    // IMMEDIATE switch = no raise/lower animation, so the swap is invisible AND
    // GetCurrentWeapon never returns a transitional value during a ~0.5s raise -
    // that transitional window was the flip-flop / "random swap out" source.
    // Verified stock builtin (_zm_weapons / _zm_laststand / player_shared).
    if ( was_equipped ) self SwitchToWeaponImmediate( w_to );

    // Carry ammo the stock-PaP way (_zm_pack_a_punch.gsc:693-696): add any clip/reserve
    // CAP delta between the forms so the copy never clamps. A variant twin shares the
    // stem's clipSize/maxAmmo today (delta 0 == straight copy), but the delta form stays
    // correct if a future twin ever changes a cap, and clamping at 0 guards a negative.
    // Set AFTER the switch, exactly as stock does.
    new_clip  = clip  + ( w_to.clipSize - w_from.clipSize );
    new_stock = stock + ( w_to.maxAmmo  - w_from.maxAmmo );
    if ( new_clip  < 0 ) new_clip  = 0;
    if ( new_stock < 0 ) new_stock = 0;
    self SetWeaponAmmoStock( w_to, new_stock );
    self SetWeaponAmmoClip( w_to, new_clip );
    self TakeWeapon( w_from );

    // Proof-of-life: `acc_variants_debug 1` shows each swap on-screen so you can
    // confirm Deadshot/Mega is actually changing the weapon (recoil is invisible
    // otherwise). Off by default.
    if ( ( isdefined( level.acc_dev ) && level.acc_dev ) || getdvarint( "acc_variants_debug", 0 ) == 1 )
        self iprintln( "^3[variants]^7 " + w_from.name + " ^2->^7 " + w_to.name );

    self.acc_swapping = false;
}

// ===========================================================================
// Desired-state derivation -- THE EXTENSION POINT for new perk/ability twins.
//
// Each "axis" is a function(self=player) returning the active TOKEN for one
// independent weapon-stat effect (recoil, fire rate, reload, ...), or undefined.
// level.acc_variant_axes (set in init) lists them in CANONICAL ORDER - the order
// tokens appear in a twin's name. compute_tokens() collects the active tokens;
// desired_weapon() turns them into the gun the player should hold
// (`<stem>_acc_<tok1>_<tok2>...`), with graceful fallback. The swap engine and PaP
// integration (true_base / register_twin_upgrades / packed_form) are all effect-AGNOSTIC,
// so a new effect never touches them.
//
// >>> TO ADD A NEW EFFECT (e.g. Speed Cola reload) - an agent does ONLY this: <<<
//   1. Generate the twins (tools/apply_recoil_overhaul.js style, or
//      gen_weapon_variant_gdt.js) scaling the relevant GDT field(s), named
//      "<gun>[_up]_acc_<token>" for every gun + its _up PaP form.
//   2. Add a variant_dims() row for the token - the suffix strip list AND the allow-list
//      cross-product follow automatically (nothing is hand-listed). Bake the twins + add their
//      zone weaponfull lines. GUN-SCOPED axis (baked for a subset)? Filter the combos in
//      build_available_twins() like the turbo axis does - the allow-list must NEVER contain an
//      un-baked name (GetWeapon on one is a runtime error).
//   3. Write an axis function below returning the token while the perk/ability is
//      active (honor timed_has() for ability overlays), and add it to
//      level.acc_variant_axes in init() in canonical order (same order as variant_dims).
// Full walkthrough: docs/21_adding_a_gun_runbook.md "Adding a weapon-variant effect".
// ===========================================================================

// Ordered list of active variant tokens for this player (canonical axis order).
function compute_tokens( player )
{
    tokens = [];
    for ( i = 0; i < level.acc_variant_axes.size; i++ )
    {
        t = player [[ level.acc_variant_axes[ i ] ]]();
        if ( isdefined( t ) ) tokens[ tokens.size ] = t;
    }
    return tokens;
}

// --- AXIS: Deadshot recoil (-25% base / -40% Mega "American Sniper") ---------
// self = player. Returns "recoil50" / undefined (Deadshot MEGA only since 2026-06-16). Honors a timed
// overlay (Stabilizer) taking the STRONGER reduction.
function axis_recoil()
{
    // 2026-06-16: single -50% recoil tier, MEGA Deadshot (American Sniper) ONLY. Base Deadshot
    // is now a pure headshot-damage perk with NO recoil twin (the dropped layer).
    if ( self HasPerk( "specialty_deadshot" ) && has_mega( self, "specialty_deadshot" ) ) return "recoil50";
    if ( timed_has( self, "recoil50" ) ) return "recoil50";
    return undefined;
}

// --- AXIS: Gun Slinger fire rate REMOVED 2026-07-04 -------------------------
// The "fastfire" twin axis (axis_fire + gunslinger_fast) was deleted: Mega Double
// Tap is now a pure damage buff (extra-bullet temper x0.6 -> x0.8 in _acc_damage),
// so no fire-rate/swap twin is needed. Freed 8 twins/gun (224 -> 96 at the then-16-gun
// roster; current matrix is in the header).

// --- AXIS: Speed Cola reload (Sleight of Hand Expert, Mega only) -> fastreload -
// self = player. Mega-only: base Speed Cola keeps the free engine +50% (no twin);
// the Mega twin layers reload x0.857 on top for the +75% net (docs/10_perks §3).
function axis_reload()
{
    if ( self HasPerk( "specialty_fastreload" ) && has_mega( self, "specialty_fastreload" ) )
        return "fastreload";
    if ( timed_has( self, "fastreload" ) ) return "fastreload";
    return undefined;
}

// --- AXIS: Turbocharger implant (boss item 8) -> turbo (HAVOC-ONLY twins) ------
// self = player. While the Turbocharger is implanted (self.acc_item_turbocharger, set by
// _acc_boss_items::apply_turbocharger) the token is active for ALL guns, but only the Havoc has
// turbo twins baked (sprintOutTime 0.2 vs the base's 0.98) - every other gun degrades gracefully
// to its remaining twins because turbo is the trailing token (see variant_dims). Result: implant
// -> your Havoc swaps to the fast-sprint-out form; unequip/bleed-out -> back to the 0.98 base.
// The implant apply/remove poke request_reconcile so the swap is immediate, not the 3s net.
function axis_turbo()
{
    if ( IS_TRUE( self.acc_item_turbocharger ) ) return "turbo";
    return undefined;
}

// --- AXIS: Leviathan Axe PaP-tier swing speed -> spd1/spd2/spd3 (LEVIATHAN-ONLY twins) --------
// self = player. +5% swing per PaP tier (user 2026-07-09): the tier is the SAME stored counter
// _acc_pap_levels writes (player.acc_pap_tier keyed by the true-base weapon OBJECT - read as a raw
// field here, like has_mega, to avoid a cyclic #using with _acc_pap_levels). Token active for all
// guns while the player's AXE is tiered, but only the leviathan bakes spd forms - every other gun
// degrades through the subset resolver. The PaP flows poke request_reconcile after a tier change,
// so the swap lands immediately; the 3s net covers every other path (give/revive/re-box).
function axis_lev_speed()
{
    base = GetWeapon( "leviathan" );
    if ( !isdefined( base ) || base == level.weaponNone ) return undefined;
    if ( !isdefined( self.acc_pap_tier ) || !isdefined( self.acc_pap_tier[ base ] ) ) return undefined;
    t = self.acc_pap_tier[ base ];
    if ( t >= 3 ) return "spd3";
    if ( t == 2 ) return "spd2";
    if ( t == 1 ) return "spd1";
    return undefined;
}

// --- AXIS: Mule Kick Mega "The Armory" ammo REMOVED 2026-06-16 ---------------
// (axis_ammo deleted 2026-07-08 dead-code sweep: the axis was unregistered when the Armory became a
// runtime round-start refill - _acc_mega_bottles::armory_refill, ACC_ARMORY_ROUND_REFILL - but the
// uncalled function lingered and kept describing a "+25% maxAmmo twin" that no longer exists.)

// (deadshot_recoil_level() deleted 2026-07-08 dead-code sweep: uncalled since 2026-06-16, and its
// 25/40 tiers described the DROPPED base-Deadshot recoil design - the shipped design is the single
// Mega-only recoil50 twin, axis_recoil above.)

// (gunslinger_fast() REMOVED 2026-07-04 with the fastfire twin axis - Mega Double
// Tap is now a damage buff in _acc_damage, not a fire-rate twin.)

// Local mirror of acc_mega_bottles::has_mega_perk - read the field directly to
// avoid a cyclic #using (mega_bottles #usings THIS module to poke reconcile).
function has_mega( player, specialty )
{
    if ( !isdefined( player ) ) return false;
    if ( !isdefined( player.acc_mega_perks ) ) return false;
    if ( !isdefined( player.acc_mega_perks[ specialty ] ) ) return false;
    return player.acc_mega_perks[ specialty ] == true;
}

// ---------------------------------------------------------------------------
// Twin-name resolution
// ---------------------------------------------------------------------------

// Resolve the gun the player should hold for `tokens` (canonical order). Tries every SUBSET of the
// active tokens, largest first (ties broken toward keeping EARLIER/canonical tokens), so a gun that
// bakes only a sparse combo still resolves. REWORKED 2026-07-08 from a trailing-token drop: the old
// prefix-only fallback could NEVER reach a non-prefix combo - e.g. the fastreload-ONLY wonders
// (Mahem / Thundergun / Fire Bow) would have resolved to BASE for any player who also had Mega
// Deadshot (tokens [recoil50, fastreload] -> tried recoil50_fastreload, then recoil50, never plain
// fastreload). Subset order for [r,f,t]: rft; rf, rt, ft; r, f, t; base. tokens.size <= 3 so the
// bitmask scan is at most 7 tries, each gated by the allow-list (no GetWeapon on un-baked names).
function desired_weapon( stem_name, tokens )
{
    n = tokens.size;
    total = 1;
    for ( i = 0; i < n; i++ ) total = total * 2;

    for ( count = n; count >= 1; count-- )
    {
        for ( mask = 1; mask < total; mask++ )
        {
            bits = 0;
            for ( i = 0; i < n; i++ ) { if ( ( mask & ( 1 << i ) ) != 0 ) bits++; }
            if ( bits != count ) continue;   // largest subsets first; mask-ascending = earlier tokens preferred

            suffix = "_acc";
            for ( i = 0; i < n; i++ ) { if ( ( mask & ( 1 << i ) ) != 0 ) suffix = suffix + "_" + tokens[ i ]; }
            w = try_resolve_twin( stem_name + suffix );
            if ( isdefined( w ) ) return w;
        }
    }
    return GetWeapon( stem_name );   // nothing baked for any combo -> base
}

// Only ever GetWeapon() a twin we declared in the allow-list, so an un-baked name
// can never raise an "unknown weapon" runtime error.
function try_resolve_twin( name )
{
    if ( !isdefined( level.acc_variant_available[ name ] ) ) return undefined;
    w = GetWeapon( name );
    if ( isdefined( w ) && w != level.weaponNone ) return w;
    return undefined;
}

// Strip a trailing variant suffix to recover the player's logical weapon
// (handles base + PaP stems, e.g. "t6_fiveseven_up_acc_recoil50" -> "t6_fiveseven_up").
function logical_stem_name( name )
{
    for ( i = 0; i < level.acc_variant_suffixes.size; i++ )
    {
        suf = level.acc_variant_suffixes[ i ];
        if ( ends_with( name, suf ) ) return GetSubStr( name, 0, name.size - suf.size );
    }
    return name;
}

function ends_with( s, suffix )
{
    if ( suffix.size > s.size ) return false;
    return GetSubStr( s, s.size - suffix.size, s.size ) == suffix;
}

// ---------------------------------------------------------------------------
// Pack-a-Punch helper (called by _acc_pap_levels for the instant in-place pack)
// ---------------------------------------------------------------------------

// The UPGRADED ("packed") form of a (possibly twin) weapon, PRESERVING any active twin
// suffix so an in-place first pack hands over the packed TWIN in ONE swap (no
// base->_up->twin double swap). Non-twin -> the stock engine upgrade
// (zm_weapons::get_upgrade_weapon). Twin (always one of the 5 variant guns, "_up"-
// convention) -> the matching "<stem>_up_acc_<combo>" from the allow-list. Returns the
// weapon UNCHANGED when there is no upgrade (already packed / a non-upgradeable hold), so
// the caller can read packed==held as "nothing to first-pack".
function packed_form( weapon )
{
    if ( !isdefined( weapon ) || weapon == level.weaponNone ) return weapon;

    stem = logical_stem_name( weapon.name );
    if ( stem != weapon.name )
    {
        // A twin: "<stem>_acc_<combo>". Its packed form is "<upgrade-of-stem>_acc_<combo>" - via
        // variant_up_name so the Thundergun's irregular "thundergun_upgraded" resolves too (2026-07-08;
        // was a literal stem+"_up", which only irregular-free guns survived).
        suffix = GetSubStr( weapon.name, stem.size, weapon.name.size );   // "_acc_<combo>"
        up = try_resolve_twin( variant_up_name( stem ) + suffix );
        if ( isdefined( up ) ) return up;
        // un-baked combo: fall through to upgrade the base, reconcile re-twins after.
    }

    base = GetWeapon( stem );
    if ( !isdefined( base ) || base == level.weaponNone ) return weapon;
    if ( zm_weapons::is_weapon_upgraded( base ) ) return base;   // stem already packed
    // [acc] GUARD (user session 2026-07-02: "undefined is not a field object" x2 via _acc_pap_levels ->
    // here -> _zm_weapons): stock get_upgrade_weapon() derefs level.zombie_weapons[rootWeapon].upgrade
    // UNGUARDED (_zm_weapons.gsc:1649). A held weapon whose stem is NOT registered in the zombie-weapons
    // table (the Action Figure - PaPs in place, no _up registration; knife/hero/dev gives) crashed there.
    // Route unregistered/upgrade-less stems back unchanged - every caller treats packed==held as
    // "nothing to first-pack" (the Action Figure's own tier path handles its in-place packs).
    root = base.rootWeapon;
    if ( !isdefined( root ) ) root = base;
    if ( !isdefined( level.zombie_weapons[ root ] ) || !isdefined( level.zombie_weapons[ root ].upgrade ) )
        return weapon;
    return zm_weapons::get_upgrade_weapon( base );               // stock base -> upgrade
}

// ---------------------------------------------------------------------------
// Public hooks (called by _acc_mega_bottles + _acc_weapon_abilities + _acc_pap_levels)
// ---------------------------------------------------------------------------

// Resolve a (possibly variant-twin) weapon to its TRUE base weapon OBJECT: strip
// our `_acc_*` suffix, then map through the stock base-weapon table. So
// s1_tac19_up_acc_recoil50 -> s1_tac19_up -> s1_tac19. THIS is the key that lets
// the PaP tier (keyed by base) follow a gun across recoil/fast swaps - the PaP
// modules key player.acc_pap_tier by this instead of zm_weapons::get_base_weapon.
function true_base( weapon )
{
    if ( !isdefined( weapon ) || weapon == level.weaponNone ) return weapon;
    stem = logical_stem_name( weapon.name );
    w = GetWeapon( stem );
    if ( !isdefined( w ) || w == level.weaponNone ) w = weapon;
    base = zm_weapons::get_base_weapon( w );

    // NAME-BASED FALLBACK (Mahem-class robustness, user 2026-06-26). get_base_weapon strips an _up via the
    // stock zombie_weapons_upgraded table; if a ported gun's _up isn't resolved there (or normalizes to a
    // different object), get_base_weapon RETURNS THE _up FORM UNCHANGED - so the PaP tier would be keyed by
    // "<gun>_up" while packs 1-2 keyed it by "<gun>", and pack 3 reads tier 0. Belt-and-suspenders: if the
    // resolved base STILL ends in "_up", strip it by name and re-resolve, so the tier key is ALWAYS the true
    // base for every gun regardless of stock-table state. No-op for conventional guns (their base never ends
    // in _up). This is independent of the AAT-visibility fix in _acc_pap_levels and the upgrade-table net.
    if ( isdefined( base ) && base != level.weaponNone && isdefined( base.name ) && ends_with( base.name, "_up" ) )
    {
        stripped_name = GetSubStr( base.name, 0, base.name.size - 3 );   // drop trailing "_up"
        stripped = GetWeapon( stripped_name );
        if ( isdefined( stripped ) && stripped != level.weaponNone )
            base = stripped;
    }
    return base;
}

// Poke a player's reconcile loop after their perk / Mega / loadout state changes.
function request_reconcile( player )
{
    if ( !isdefined( player ) ) return;
    player notify( "acc_variant_dirty" );
}

// The weapon the player SHOULD hold for `held` given live perk/timed state - the twin,
// or the plain base if no axis is active / no twin is baked. RETURNS only (no inventory
// change), mirroring reconcile()'s desired computation. Used by the perk-drink
// (_acc_mega_bottles::replay_perk_drink) to re-raise the correct twin so a Mega's twin
// swap is hidden by the drink animation instead of showing afterwards.
function resolve_held( player, held )
{
    if ( !isdefined( held ) || held == level.weaponNone ) return held;
    stem_name = logical_stem_name( held.name );
    if ( !variants_enabled() ) return GetWeapon( stem_name );

    tokens = compute_tokens( player );
    if ( tokens.size == 0 ) return GetWeapon( stem_name );

    w = desired_weapon( stem_name, tokens );
    return ( isdefined( w ) ? w : GetWeapon( stem_name ) );
}

// self = player. Timed overlay for weapon ABILITIES (e.g. Stabilizer): force the
// given variant TOKENS active for duration_sec, then clear. Axes OR-merge these with
// perk state (axis_recoil takes the STRONGER reduction). `tokens` = array of token
// strings, e.g. array( "recoil50" ). Only currently-baked axes exist (recoil50, fastreload);
// a token whose twin isn't baked just no-ops. (fastfire removed 2026-07-04.)
function apply_timed_variant( tokens, duration_sec )
{
    if ( !variants_enabled() ) return;

    s = spawnstruct();
    s.tokens = [];
    for ( i = 0; i < tokens.size; i++ ) s.tokens[ tokens[ i ] ] = true;
    s.expiry = gettime() + int( duration_sec * 1000 );
    self.acc_variant_timed = s;

    self notify( "acc_variant_dirty" );
    self thread clear_timed_variant_after( duration_sec );
}

// True if `token` is in this player's UNEXPIRED timed overlay. Axes call this so an
// ability overlay stacks with perk-derived state.
function timed_has( player, token )
{
    if ( !isdefined( player.acc_variant_timed ) ) return false;
    if ( gettime() >= player.acc_variant_timed.expiry ) return false;
    return IS_TRUE( player.acc_variant_timed.tokens[ token ] );
}

function clear_timed_variant_after( duration_sec )
{
    self endon( "disconnect" );
    wait duration_sec;

    // Only clear if THIS overlay expired (a later re-arm pushes expiry forward).
    if ( isdefined( self.acc_variant_timed ) && gettime() >= self.acc_variant_timed.expiry )
        self.acc_variant_timed = undefined;
    self notify( "acc_variant_dirty" );
}

function variants_enabled()
{
    return getdvarint( "acc_weapon_variants", ACC_VARIANTS_DEFAULT ) == 1;
}
