// =============================================================================
// _acc_pap_levels.gsc - 3-tier money-track Pack-a-Punch
//
// 3 TIERS (revamp 2026-06-16, user): the damage ladder is LINEAR +33.33%/pack -> +33% / +67% / +100%
// over the gun's normalized base damage (T3 MAX = double dmg), and the ACTUAL PaP TRANSFORM (the "_up" asset - explosive
// M1911, akimbo PDW, etc.) is DEFERRED to tier 2. Tier 1 is a pure DAMAGE pack that keeps the
// base gun's appearance/behavior. (Gold PaP camo removed 2026-06-27 - no longer a feature.)
//
// COSTS ARE PER-GUN (user 2026-06-23): every gun has a PRICE TIER (WONDER/TOP/MID/BOT) from
// pap_price_bucket() - ranked by PaP-form power (docs/33); the 4 wonder weapons get their own premium
// WONDER tier (user 2026-07-07). The four numbers below are WONDER / TOP / MID / BOT for that step.
//   TIER 0->1 (cost 10000 / 5000 / 4000 / 3000): acc_do_first_pack - record tier 1 on the HELD gun IN PLACE
//     (NO asset swap - still the base form / base perk-twin). +33% dmg. The "_up" transform does NOT happen yet.
//   TIER 1->2 (cost 15000 / 7500 / 6000 / 4500): acc_do_tier_up - NOW swap to the packed "_up" form (the matching
//     packed TWIN when holding a perk twin), carrying ammo. This is the real PaP transform. +67% dmg.
//   TIER 2->3 (cost 20000 / 10000 / 8000 / 6000): acc_do_tier_up - in place, no asset re-swap, bump damage. +100% (MAX, double dmg).
//
// ALL packs happen IN PLACE - no machine float / take-back animation, on any tier. Holding
// Use packs the held gun right there, and EVERY tier replays the first-pack in-hand "gun
// comes out" draw (user 2026-06-15; see replay_pack_draw / acc_pap_tier_anim). The stock
// machine's float pack is BLOCKED (acc_pap_validate returns false for EVERY gun).
//
//   player.acc_pap_tier[ base_weapon ] = 1..3   (keyed by acc_weapon_variants::true_base)
//   -> _acc_damage multiplies pap_tier_mult(tier) into every gun hit (1.3333 / 1.66666 / 1.999999).
//   -> HUD shows a roman-numeral cyber-shield icon (I/II/III) for the held weapon, centered
//      on the gadget circle (bottom-right) - acc_hud.lua CoD.AccPapTierIcon via accPapTier.
//   -> each pack/tier-up prints the new tier's benefit so the player can decide.
//
// BOX GUNS MUST COME OUT STOCK (user 2026-06-15). Tier 1 is now a BASE-FORM gun (damage only, no asset swap),
// so we can NO LONGER lean on is_weapon_upgraded() to keep a box copy stock (that was the old
// 5-tier invariant: tier rode the "_up" asset). Two mechanisms replace it, both keyed by
// true_base:
//   - box_grab_clear_watcher (per player, on the stock "user_grabbed_weapon" notify): the
//     weapon just handed over by the Mystery Box is reset to tier 0, so a re-boxed copy of a
//     gun you previously packed is stock again.
//   - tier_possession_prune (in pap_hud_loop): clears acc_pap_tier[ base ] for any base the
//     player no longer carries ANY form of (covers wallbuy-over / slot swaps). Gated on
//     !laststand && !is_drinking && !acc_pap_busy so it never fires mid-pack / mid-down.
//
// "Can't PaP gun X" with the prompt PRESENT but a re-pack no-op = MAX TIER (3/3). Re-packing
// a maxed gun correctly REFUSES ("already max tier 3").
// =============================================================================

#using scripts\shared\flag_shared;
#using scripts\shared\hud_util_shared;
#using scripts\shared\util_shared;

#insert scripts\shared\shared.gsh;

#using scripts\zm\_zm;
#using scripts\zm\_zm_score;
#using scripts\zm\_zm_utility;
#using scripts\zm\_zm_weapons;

#using scripts\zm\zm_abandoned_cyber_city\_acc_utility;
#using scripts\zm\zm_abandoned_cyber_city\_acc_weapon_variants;
#using scripts\zm\zm_abandoned_cyber_city\_acc_lui;

#define ACC_PAP_MAX_TIER 3
// Per-step PaP costs are now PER-GUN by PRICE TIER (TOP/MID/BOT) - see pap_price_bucket()
// + tier_cost() below (generated by tools/compute_gun_tiers.js, docs/33). The old flat
// ACC_PAP_TIER_COST_2/3 #defines were replaced by that table 2026-06-23.
#define ACC_PAP_STOCK_FIRST_COST 5000   // stock machine first-pack price; a Bonfire Sale would lower it (none in this map, but the T1 override is guarded against it)

// PaP has no machine float / weapon-lock on any tier - the pack/upgrade happens in hand the
// moment you finish the Use-hold (every tier replays the first-pack in-hand draw, 2026-06-15).
// This debounce just stops one completed Use-hold from re-firing the machine trigger and
// packing/tiering twice (double-charge); short, spans a single hold.
#define ACC_PAP_PACK_DEBOUNCE 1.0
#define ACC_PAP_FIRST_PACK_COST 5000   // fallback if a gun has no bucket entry / live self.cost is unset

#namespace acc_pap_levels;

function init()
{
    acc_utility::log( "pap_levels: init (max tier " + ACC_PAP_MAX_TIER + ")" );
    // The PaP tier damage multiplier is applied inside _acc_damage's single
    // multiplier chain (2026-06-14), NOT a separate actor-damage callback. Two
    // modifying callbacks can't coexist: stock dispatch takes the first non -1
    // and passes the original damage to each (_zm.gsc:5824), so a second callback
    // never stacked - PaP tier silently dropped on headshots/perk'd hits. get_tier
    // + pap_tier_mult below stay as the queryable source of truth for that chain.
    level thread player_setup_loop();
    level thread pap_tier_machine_watcher(); // multi-pack tiers 2-5, no AAT
    level thread pap_cost_display_keeper(); // show the real tier-up cost on the machine
    // DEV on-screen PaP probes REMOVED 2026-07-10 (clean screen in hardcoded dev). Re-thread either line to debug PaP.
    // level thread dev_mahem_pap_watch();      // acc_dev ground-truth readout for the Mahem PaP (user 2026-06-26)
    // level thread dev_pap_machine_probe();    // acc_dev: print what the PaP machine entity actually is (2026-07-02)
    // CW/BO6 PaP machine model (ALXS pack, user 2026-07-02; 3rd attempt same day): swapped at
    // the ZBARRIER ASSET level - install-side zbarriers.gdt "zmcore_packapunch" boardModel1/2/5 ->
    // p9_fxanim_zm_gp_pap_xmodel(_off) + those boardAnims blanked (backup zbarriers.gdt.acc-orig).
    // History: (1) runtime SetModel on the zbarrier NO-OPS (verified in-game); (2) per-ENTITY
    // zbarrierboardModelN overrides in the prefab clone (_prefabs/acc/vending_weapon_upgrade_alxs.map)
    // ALSO did not take in-game -> the runtime board set evidently binds to the zbarrier ASSET.
    // The prefab clone is kept (consistent intent, harmless). The Paradise clone
    // (spawn_paradise_pap_at below) is a plain script_model and SetModels the p9 model directly.
    // *** REINSTALL TRAP (found 2026-07-09, "lab still shows the old model"): source_data is
    // un-tracked and NOT synced by sync_to_modtools, so the 2026-07-03 new-box Mod Tools install
    // silently REVERTED this GDT edit. Re-apply it any time with tools/apply_pap_zbarrier_swap.ps1
    // (idempotent; edits the block, rebuilds gdt.db, backup-safe) - run it after ANY tools reinstall.
}

// acc_dev PROBE (2026-07-02): make the next playtest TELL us what the surface PaP machine is.
// Prints the zbarrier entity's .model once found. Readings: stock p7 name -> the asset edit
// didn't drive it either (remaining lever: hide zbarrier + overlay script_model); p9 name but
// machine LOOKS stock -> impossible (boards ARE the look); "" / undefined -> boards only (asset-
// driven, expected); machine INVISIBLE in-game -> the fxanim static-render risk (docs/35).
function dev_pap_machine_probe()
{
    if ( !IS_TRUE( level.acc_dev ) ) return;
    machine = undefined;
    for ( i = 0; i < 300 && !isdefined( machine ); i++ )
    {
        machine = GetEnt( "vending_packapunch", "targetname" );
        if ( !isdefined( machine ) ) wait 0.1;
    }
    wait 8;   // past the blackscreen so the print is visible
    if ( !isdefined( machine ) )
    {
        foreach ( p in GetPlayers() ) p IPrintLnBold( "^1[ACC] PaP probe: NO vending_packapunch entity" );
        return;
    }
    m = machine.model;
    if ( !isdefined( m ) || m == "" ) m = "(none - board-driven)";
    foreach ( p in GetPlayers() )
        p IPrintLnBold( "^3[ACC] PaP machine .model = " + m );
}

// DEV ground-truth readout for the Mahem "only packs twice" investigation (user 2026-06-26). Prints the EXACT
// runtime state whenever a player HOLDS any Mahem form, so we stop guessing: is_weapon_upgraded, the resolved
// tier base, the current tier, AAT-exemption, and whether stock's machine-visibility gate would SHOW the
// machine (player_use_can_pack_now shows it iff can_pack_weapon || weapon_supports_aat; for an _up gun
// can_pack_weapon is false, so it rides weapon_supports_aat = is_weapon_upgraded(root) && !is_exempt).
// On-change only (not spammy). acc_dev-gated -> ZERO cost in normal play. Read the printed line when the gun
// "won't pack a 3rd time" - it tells you immediately whether it's hidden (vis=0), mis-tiered (tier!=2), or fine.
function dev_mahem_pap_watch()
{
    if ( !IS_TRUE( level.acc_dev ) ) return;
    level endon( "end_game" );
    level flag::wait_till( "initial_blackscreen_passed" );

    last = [];
    for ( ;; )
    {
        wait 0.5;
        players = GetPlayers();
        for ( i = 0; i < players.size; i++ )
        {
            p = players[ i ];
            if ( !isdefined( p ) || !isplayer( p ) ) continue;
            w = p GetCurrentWeapon();
            if ( !isdefined( w ) || w == level.weaponNone || !isdefined( w.name ) || !IsSubStr( w.name, "s1_mahem" ) )
                continue;

            nonalt = zm_weapons::get_nonalternate_weapon( w );
            upg    = zm_weapons::is_weapon_upgraded( nonalt );
            tier   = get_tier( p, w );
            base   = acc_weapon_variants::true_base( w );
            base_n = ( isdefined( base ) && isdefined( base.name ) ? base.name : "?" );
            exempt = ( isdefined( level.aat_exemptions ) && isdefined( level.aat_exemptions[ nonalt ] ) );
            supports_aat = ( upg && !exempt );                 // weapon_supports_aat() core for an _up gun
            vis    = ( supports_aat || tier <= 0 );            // _up shows via aat; base (tier 0/1) shows via can_pack_weapon

            msg = w.name + " upg=" + upg + " base=" + base_n + " tier=" + tier + " exempt=" + exempt + " machine_visible=" + vis;
            if ( !isdefined( last[ i ] ) || last[ i ] != msg )
            {
                p IPrintLnBold( "^5[dev mahem] " + msg );
                last[ i ] = msg;
            }
        }
    }
}

// Keep the machine's advertised price equal to the player's ACTUAL next-pack charge. The
// stock hint reads the cost LIVE every frame: an UPGRADED ("_up") gun shows self.aat_cost,
// a base/upgradeable gun shows self.cost (verified vs _zm_pack_a_punch.gsc:430-442). We can't
// reword the stock string from a usermap, but we CAN drive the number. Per-player isn't
// possible on the shared trigger, so it tracks the nearest player (solo-exact). The 10% Armory
// discount is folded in. Reads the perk field directly (no #using cycle). self unused; level loop.
//
// 3-tier mapping (revamp 2026-06-16):
//   tier 0 (stock base)      -> self.cost stays the machine's own cost (5000, or 1000 on a
//                               bonfire sale) - DON'T touch it, so bonfire sales survive.
//   tier 1 (base, dmg only)  -> the NEXT pack is the transform (tier 2). The gun is still
//                               un-upgraded, so the prompt reads self.cost -> OVERRIDE it to the
//                               tier-2 price (save/restore so a leftover override never clobbers
//                               the bonfire/stock cost once a tier-0 player returns).
//   tier 2 (_up)             -> self.aat_cost = tier-3 price.
//   tier 3 (_up, MAX)        -> self.aat_cost = 0 (no re-pack; holding Use no-ops, so zeroing
//                               stops the stale tier-3 price falsely advertising a re-pack).
function pap_cost_display_keeper()
{
    level endon( "end_game" );
    level flag::wait_till( "initial_blackscreen_passed" );

    triggers = [];
    for ( i = 0; i < 60; i++ )
    {
        triggers = GetEntArray( "pack_a_punch", "script_noteworthy" );
        if ( triggers.size > 0 ) break;
        wait 0.5;
    }
    if ( triggers.size == 0 ) return;

    for ( ;; )
    {
        for ( i = 0; i < triggers.size; i++ )
        {
            t = triggers[ i ];
            if ( !isdefined( t ) ) continue;

            np = nearest_pap_player( t.origin );
            tier = -1;
            w = undefined;
            if ( isdefined( np ) )
            {
                w = np GetCurrentWeapon();
                if ( isdefined( w ) && w != level.weaponNone )
                    tier = get_tier( np, w );
            }

            if ( is_actionfigure( w ) || is_firebow( w ) || is_cyberjack( w ) )
            {
                // Action Figure + Fire Bow + CYBERJACK PaP IN PLACE (no _up form) - drive the price off their own tier.
                // TRAP (user 2026-07-07): both are is_weapon_upgraded at their packed tiers - the AF SPEED TWINS
                // (fast1/2/3), and the Fire Bow's demon-gate form at EVERY tier - and the stock machine prompt
                // reads self.AAT_COST for an upgraded weapon (self.cost only for a NON-upgraded base). The old AF
                // branch always wrote self.cost, so a PaP'd Action Figure showed a STALE price (the prompt was
                // reading aat_cost). set_inplace_pap_cost writes whichever field the prompt actually reads. This
                // MUST run before the is_upgraded_safe branch below (the Fire Bow is is_weapon_upgraded, so it
                // would otherwise be misread as a tier-2 _up gun and shown the wrong tier's cost).
                set_inplace_pap_cost( t, np, w, tier );
            }
            else if ( is_upgraded_safe( w ) )
            {
                // tier 2/3 (_up form): stock prompt reads self.aat_cost. Clear any leftover
                // self.cost override first so a returning tier-0 player sees the real cost.
                restore_machine_cost( t );
                if ( tier < 2 ) tier = 2; // an _up gun is always >= tier 2
                if ( tier >= ACC_PAP_MAX_TIER )
                    t.aat_cost = 0; // maxed: no re-pack
                else
                    t.aat_cost = np armory_discount( weapon_tier_cost( w, tier + 1 ) );
            }
            else if ( tier == 1 )
            {
                // tier 1 (base, damage only, still un-upgraded): stock prompt reads self.cost, but the
                // NEXT pack is the tier-2 transform - override the displayed cost to its price.
                if ( !IS_TRUE( t.acc_cost_overridden ) )
                {
                    t.acc_saved_cost = t.cost;
                    t.acc_cost_overridden = true;
                }
                t.cost = np armory_discount( weapon_tier_cost( w, 2 ) );
            }
            else if ( tier == 0 && pap_weapon_packable( w ) )
            {
                // tier 0 (packable base gun): gun-tier the FIRST-pack price (TOP 5000 /
                // MID 4000 / BOT 3000). Save the machine's own cost once; if a Bonfire Sale
                // ever drops it below the stock 5000, keep the sale instead of overriding
                // (no bonfire powerup in this map today, but this stays safe if one is added).
                if ( !IS_TRUE( t.acc_cost_overridden ) )
                {
                    t.acc_saved_cost = t.cost;
                    t.acc_cost_overridden = true;
                }
                // CRASH GUARD (co-op pre-power audit 2026-06-27): stock sets t.cost only AFTER Pack_A_Punch_on,
                // but this map ships power OFF behind the manual dual-switch and everyone spawns with a packable
                // tier-0 gun, so the keeper reaches here with t.cost (hence the saved t.acc_saved_cost) UNDEFINED.
                // A relational compare on undefined is a FATAL script error -> CTD the moment anyone walks within
                // 130u of PaP before power. The isdefined-guard falls through to the per-gun first-pack price,
                // which is the correct pre-power display anyway.
                if ( isdefined( t.acc_saved_cost ) && t.acc_saved_cost < ACC_PAP_STOCK_FIRST_COST )
                    t.cost = t.acc_saved_cost;                               // bonfire/sale - keep it
                else
                    t.cost = np armory_discount( weapon_tier_cost( w, 1 ) ); // per-gun first-pack price
            }
            else
            {
                // no nearby player / non-packable held item: restore the machine's own cost (bonfire-safe).
                restore_machine_cost( t );
            }
        }
        wait 0.2;
    }
}

// Displayed PaP price for an IN-PLACE-pack weapon (Action Figure / Fire Bow): write the field the STOCK PROMPT
// reads. An is_weapon_upgraded weapon's prompt reads self.aat_cost; a non-upgraded base reads self.cost. Writing
// the wrong one leaves a stale/wrong price on the machine - the AF speed-twin bug (user 2026-07-07). The Fire
// Bow is is_weapon_upgraded at every tier (aat_cost); the AF is a non-upgraded base at tier 0 (cost) and an
// is_weapon_upgraded twin at tiers 1-3 (aat_cost), so this keys off is_upgraded_safe per held form.
function set_inplace_pap_cost( t, np, w, tier )
{
    upgraded = is_upgraded_safe( w );
    if ( tier >= ACC_PAP_MAX_TIER )
    {
        if ( upgraded ) t.aat_cost = 0;          // maxed: re-pack no-ops (prompt reads aat_cost)
        else            restore_machine_cost( t );
        return;
    }
    next_cost = np armory_discount( weapon_tier_cost( w, tier + 1 ) );
    if ( upgraded )
    {
        restore_machine_cost( t );               // clear any stale t.cost override left from a tier-0 state
        t.aat_cost = next_cost;
    }
    else
    {
        if ( !IS_TRUE( t.acc_cost_overridden ) )
        {
            t.acc_saved_cost = t.cost;
            t.acc_cost_overridden = true;
        }
        t.cost = next_cost;
    }
}

// is_weapon_upgraded with an undefined/weaponNone guard (the keeper may have no nearby player).
function is_upgraded_safe( w )
{
    if ( !isdefined( w ) || w == level.weaponNone ) return false;
    return zm_weapons::is_weapon_upgraded( w );
}

// Undo a tier-1 self.cost override so the machine's own cost (5000, or a bonfire 1000)
// shows again for a tier-0 first pack.
function restore_machine_cost( t )
{
    if ( IS_TRUE( t.acc_cost_overridden ) )
    {
        t.cost = t.acc_saved_cost;
        t.acc_cost_overridden = false;
    }
}

function nearest_pap_player( origin )
{
    best = 16900; // 130u - PaP machines are larger than perk vendors
    np = undefined;
    players = GetPlayers();
    for ( i = 0; i < players.size; i++ )
    {
        p = players[ i ];
        if ( !isdefined( p ) || !isplayer( p ) ) continue;
        d = DistanceSquared( p.origin, origin );
        if ( d < best ) { best = d; np = p; }
    }
    return np;
}

// =============================================================================
// PER-GUN PaP PRICING (user 2026-06-23). The per-step PaP cost depends on the gun's
// PRICE TIER (TOP/MID/BOT), assigned by ranking every gun on its PaP-form power and
// splitting the ranking into thirds (rank terciles). GENERATED by
// tools/compute_gun_tiers.js - do NOT hand-edit the table between the BEGIN/END
// markers; edit that script's roster and re-run (it regenerates docs/33 + this
// snippet to paste). IsSubStr so one entry covers a gun's base + _up + _acc twin.
// =============================================================================

// <<< BEGIN GENERATED >>>  pap_price_bucket = tools/gen_box_dynamic.js (CURATED rank bands + per-gun price
//     overrides carried in that script's RANK table; 29-entry roster. Regenerated 2026-07-10 after adding the
//     HAMR (BO2 LMG, MID price, rank #24 between Streetsweeper and RPD) - every pre-existing gun's PRICE is
//     unchanged. tier_cost below stays from compute_gun_tiers.js.
function pap_price_bucket( weapon_name )
{
    if ( !isdefined( weapon_name ) ) return "BOT";

    // WONDER  (10000 / 15000 / 20000)
    if ( IsSubStr( weapon_name, "thundergun" ) )            return "WONDER";   // #1 Thundergun (special)
    if ( IsSubStr( weapon_name, "t9_semiauto_cosplay" ) )   return "WONDER";   // #2 Blast-O-Matic (special)
    if ( IsSubStr( weapon_name, "elemental_bow_demongate" ) ) return "WONDER";   // #3 Fire Bow (special)
    if ( IsSubStr( weapon_name, "apex_lstar" ) )              return "WONDER";   // THE CYBERJACK (L-STAR chassis, quest-only wonder - docs/43; chassis swap 2026-07-17)
    if ( IsSubStr( weapon_name, "leviathan" ) )             return "WONDER";   // #4 Leviathan Axe (special)
    if ( IsSubStr( weapon_name, "freezegun" ) )             return "WONDER";   // Winter's Howl (utility freeze wonder, 2026-07-11; is_aat_exempt FALSE in CSV so tier-3 PaP stays visible - no thundergun-style fix needed)

    // TOP  (5000 / 7500 / 10000)
    if ( IsSubStr( weapon_name, "t8_melee_figure" ) )       return "TOP";   // #5 Action Figure (special)
    if ( IsSubStr( weapon_name, "knife_ballistic" ) )       return "TOP";   // Ballistic Knife (utility special, AF-adjacent - review 2026-07-11: unlisted = silent BOT; tier 2 = the _upgraded transform that unlocks the Krauss revive, price it like the AF)
    if ( IsSubStr( weapon_name, "t9_xm4" ) )                return "TOP";   // #6 XM4
    if ( IsSubStr( weapon_name, "apex_peacekeeper" ) )      return "TOP";   // #7 Peacekeeper
    if ( IsSubStr( weapon_name, "t9_ak47" ) )               return "TOP";   // #8 AK-47
    if ( IsSubStr( weapon_name, "t9_m60" ) )                return "TOP";   // #9 M60
    if ( IsSubStr( weapon_name, "s4_ppsh41" ) )             return "TOP";   // #10 PPSH-41
    if ( IsSubStr( weapon_name, "apex_beam_rifle" ) )       return "TOP";   // #11 Havoc (special)
    if ( IsSubStr( weapon_name, "s1_mahem" ) )              return "TOP";   // #12 Mahem (special)
    if ( IsSubStr( weapon_name, "t6_war_machine" ) )        return "TOP";   // #13 War Machine (special)
    if ( IsSubStr( weapon_name, "s1_mors" ) )               return "TOP";   // #14 MORS
    if ( IsSubStr( weapon_name, "s1_cel3" ) )               return "TOP";   // #18 CEL-3

    // MID  (4000 / 6000 / 8000)
    if ( IsSubStr( weapon_name, "s1_ae4" ) )                return "MID";   // #16 AE4
    if ( IsSubStr( weapon_name, "s1_rw1" ) )                return "MID";   // #17 RW1
    if ( IsSubStr( weapon_name, "apex_tripletake" ) )       return "MID";   // #19 Triple Take (took the retired M16's slot, 2026-07-11)
    if ( IsSubStr( weapon_name, "s1_tac19" ) )              return "MID";   // #21 Tac-19
    if ( IsSubStr( weapon_name, "t9_ak74u" ) )              return "MID";   // #22 AK-74u
    if ( IsSubStr( weapon_name, "t6_hamr" ) )               return "MID";   // #25 HAMR
    if ( IsSubStr( weapon_name, "t9_rpd" ) )                return "MID";   // #26 RPD

    // BOT  (3000 / 4500 / 6000)
    if ( IsSubStr( weapon_name, "apex_alternator" ) )       return "BOT";   // #15 Alternator
    if ( IsSubStr( weapon_name, "s1_mk14" ) )               return "BOT";   // #20 MK14 (user 2026-07-11: MID->BOT, 3000/4500/6000)
    if ( IsSubStr( weapon_name, "apex_prowler" ) )          return "BOT";   // #23 Prowler
    if ( IsSubStr( weapon_name, "t9_streetsweeper" ) )      return "BOT";   // #24 Streetsweeper
    if ( IsSubStr( weapon_name, "t6_olympia" ) )            return "BOT";   // #27 Olympia
    if ( IsSubStr( weapon_name, "t9_grav" ) )               return "BOT";   // #28 Grav
    if ( IsSubStr( weapon_name, "t6_fiveseven" ) )          return "BOT";   // #29 Five-Seven

    return "BOT";   // default: cheapest tier
}

// Per-step PaP cost: price tier x PaP tier (1..3). docs/33.
function tier_cost( bucket, tier )
{
    // WONDER tier (user 2026-07-07): the 4 wonder weapons (Thundergun / Fire Bow / Leviathan Axe /
    // Blast-O-Matic) cost MORE to PaP than any normal gun - 10k / 15k / 20k across the 3 steps.
    if ( bucket == "WONDER" )
    {
        switch ( tier ) { case 1: return 10000; case 2: return 15000; case 3: return 20000; }
    }
    else if ( bucket == "TOP" )
    {
        switch ( tier ) { case 1: return 5000; case 2: return 7500; case 3: return 10000; }
    }
    else if ( bucket == "MID" )
    {
        switch ( tier ) { case 1: return 4000; case 2: return 6000; case 3: return 8000; }
    }
    else   // "BOT" and default
    {
        switch ( tier ) { case 1: return 3000; case 2: return 4500; case 3: return 6000; }
    }
    return 0;
}
// <<< END GENERATED >>>

// Cost to buy PaP `tier` (1..3) for the held weapon `w`, by its price tier (TOP/MID/BOT).
// Twin/_up aware via the IsSubStr matching in pap_price_bucket( w.name ).
function weapon_tier_cost( w, tier )
{
    if ( !isdefined( w ) || w == level.weaponNone ) return tier_cost( "BOT", tier );
    return tier_cost( pap_price_bucket( w.name ), tier );
}

// True if the held weapon is the Action Figure melee. ONE-OFF: it has NO "_up" form, so it PaPs IN PLACE -
// tiers 1..3 add CLEAVE targets to its always-one-knife in _acc_damage (acc_pap_actionfigure does the pack).
function is_actionfigure( w )
{
    if ( !isdefined( w ) || w == level.weaponNone || !isdefined( w.name ) ) return false;
    // covers the base figure, the off-hand sibling, AND the per-tier SPEED TWINS (t8_melee_figure_fast1/2/3).
    return IsSubStr( w.name, "t8_melee_figure" ) || w.name == "t8_actionfigure_melee";
}

// FIRE BOW (HB21 demon-gate) â€” like the Action Figure, an IN-PLACE PaP with NO "_up" form (CSV upgrade=self).
// The stock flow breaks it two ways: `is_weapon_upgraded` is STATICALLY true for the demon-gate (it's an
// upgraded bow variant) so get_tier misreads it as tier 2 at base, and acc_do_transform bails (packed==self).
// So we own its tier in a dedicated counter (player.acc_firebow_tier, 0..3) driven by acc_pap_firebow, exactly
// like actionfigure_tier_of. get_tier + the demon-gate scaling both read firebow_tier for a clean 0-3 ramp.
// (user 2026-07-07 - fixes "clip still 50 at base": get_tier's is_weapon_upgraded bump was forcing tier 2.)
function is_firebow( w )
{
    if ( !isdefined( w ) || w == level.weaponNone || !isdefined( w.name ) ) return false;
    return IsSubStr( w.name, "elemental_bow_demongate" );
}

function firebow_tier( player )
{
    if ( !isdefined( player ) || !isdefined( player.acc_firebow_tier ) ) return 0;
    t = player.acc_firebow_tier;
    if ( t < 0 ) t = 0;
    if ( t > 3 ) t = 3;
    return t;
}

// self = player. One-off in-place PaP for the Fire Bow: charge the WONDER price tier, bump acc_firebow_tier,
// refill + replay the pack draw for feedback. NO transform (there is no packed form). Mirrors acc_pap_actionfigure.
function acc_pap_firebow()
{
    self endon( "disconnect" );
    if ( isdefined( self.acc_tier_cd ) && GetTime() < self.acc_tier_cd )
        return;
    self.acc_tier_cd = GetTime() + int( ACC_PAP_PACK_DEBOUNCE * 1000 );

    w = self GetCurrentWeapon();
    if ( !is_firebow( w ) ) return;

    cur = firebow_tier( self );
    if ( cur >= ACC_PAP_MAX_TIER )
        return;                                            // maxed (tier 3); the machine price already reads 0
    next = cur + 1;

    cost = self armory_discount( weapon_tier_cost( w, next ) );   // WONDER tier: 10000 / 15000 / 20000
    if ( !( self zm_score::can_player_purchase( cost ) ) )
    {
        self acc_pap_play_on_machine( "zmb_perks_packa_deny" );
        self IPrintLnBold( "^1Not enough points ^7(need " + cost + ")" );
        return;
    }

    self acc_pap_play_on_machine( "zmb_perks_packa_upgrade" );
    self zm_score::minus_to_player_score( cost );

    self.acc_firebow_tier = next;    // demon-gate radius/chompers/clip read this live (via get_tier -> firebow_tier)
    self replay_pack_draw( w );      // in-place: same weapon, just the pack animation for feedback
    self fill_full_ammo( w );        // the clip watcher re-clamps to the new tier's cap within a tick

    self acc_pap_play_on_machine( "zmb_perks_packa_ready" );
    // [dev] Fire-Bow PaP-tier on-screen print REMOVED 2026-07-10 (clean screen in hardcoded dev)
}

// THE CYBERJACK (apex_lstar / L-STAR chassis, docs/43; chassis swap from the storm bow 2026-07-17
// - user: "the part I don't really like is that it's a bow") - the Fire Bow's in-place-PaP template:
// no "_up" asset (CSV upgrade=self), so it owns its tier in a dedicated counter
// (player.acc_cyberjack_tier, 0..3) driven by acc_pap_cyberjack. QUEST-ONLY - never in the box
// (decision 2); acquisition = the ICEBREAKER COMPILE (M4) / _acc_dev grant until then.
function is_cyberjack( w )
{
    if ( !isdefined( w ) || w == level.weaponNone || !isdefined( w.name ) ) return false;
    return IsSubStr( w.name, "apex_lstar" );
}

function cyberjack_tier( player )
{
    if ( !isdefined( player ) || !isdefined( player.acc_cyberjack_tier ) ) return 0;
    t = player.acc_cyberjack_tier;
    if ( t < 0 ) t = 0;
    if ( t > 3 ) t = 3;
    return t;
}

// self = player. One-off in-place PaP for the CYBERJACK: charge the WONDER price tier, bump acc_cyberjack_tier,
// refill + replay the pack draw for feedback. NO transform (there is no packed form). Mirrors acc_pap_firebow.
function acc_pap_cyberjack()
{
    self endon( "disconnect" );
    if ( isdefined( self.acc_tier_cd ) && GetTime() < self.acc_tier_cd )
        return;
    self.acc_tier_cd = GetTime() + int( ACC_PAP_PACK_DEBOUNCE * 1000 );

    w = self GetCurrentWeapon();
    if ( !is_cyberjack( w ) ) return;

    cur = cyberjack_tier( self );
    if ( cur >= ACC_PAP_MAX_TIER )
        return;                                            // maxed (tier 3); the machine price already reads 0
    next = cur + 1;

    cost = self armory_discount( weapon_tier_cost( w, next ) );   // WONDER tier: 10000 / 15000 / 20000
    if ( !( self zm_score::can_player_purchase( cost ) ) )
    {
        self acc_pap_play_on_machine( "zmb_perks_packa_deny" );
        self IPrintLnBold( "^1Not enough points ^7(need " + cost + ")" );
        return;
    }

    self acc_pap_play_on_machine( "zmb_perks_packa_upgrade" );
    self zm_score::minus_to_player_score( cost );

    self.acc_cyberjack_tier = next;   // M1+ behavior (hops/slow/harvest) reads this live via get_tier -> cyberjack_tier
    self replay_pack_draw( w );       // in-place: same weapon, just the pack animation for feedback
    self fill_full_ammo( w );

    self acc_pap_play_on_machine( "zmb_perks_packa_ready" );
}

// The Action Figure's current PaP tier = which SPEED-TWIN form is held (base=0, fast1/2/3=1/2/3). This is the
// source of truth (survives re-boxing), NOT a stored counter. Each tier swaps to a twin with a faster meleeTime.
function actionfigure_tier_of( w )
{
    if ( !isdefined( w ) || !isdefined( w.name ) ) return 0;
    // Berzerker (boss item 11, 2026-07-11) forms: each tier has a "_brz" twin (+35% swing on top of
    // the tier speed; _acc_boss_items swaps ladders on implant/unequip). Same tier, faster GDT.
    if ( w.name == "t8_melee_figure_fast3" || w.name == "t8_melee_figure_fast3_brz" ) return 3;
    if ( w.name == "t8_melee_figure_fast2" || w.name == "t8_melee_figure_fast2_brz" ) return 2;
    if ( w.name == "t8_melee_figure_fast1" || w.name == "t8_melee_figure_fast1_brz" ) return 1;
    return 0;   // t8_melee_figure / t8_melee_figure_brz
}

// True if `w` actually has a PaP form (so the machine can pack it). Used by the cost display so a
// non-packable held item (knife / already-max) doesn't show a first-pack price. packed_form() returns the
// weapon UNCHANGED when there is no upgrade. EXCEPTION: the Action Figure melee packs in place (no _up form).
function pap_weapon_packable( w )
{
    if ( !isdefined( w ) || w == level.weaponNone ) return false;
    if ( is_actionfigure( w ) ) return true;   // Action Figure: in-place PaP (no _up) - see acc_pap_actionfigure
    if ( is_firebow( w ) ) return true;        // Fire Bow: in-place PaP (no _up, upgrade=self) - see acc_pap_firebow
    if ( is_cyberjack( w ) ) return true;      // CYBERJACK: in-place PaP (no _up, upgrade=self) - see acc_pap_cyberjack
    packed = acc_weapon_variants::packed_form( w );
    return isdefined( packed ) && packed != level.weaponNone && packed != w;
}

// Stock PaP custom_validation hook (_zm_pack_a_punch.gsc:399-406). self = PaP machine,
// arg = player; runs when the player finishes the Use-hold. We do EVERY pack OURSELVES, IN
// PLACE and INSTANTLY (user 2026-06-14: no machine float / animation on any tier), and
// ALWAYS return false so the stock machine's float pack + take-back never runs (that
// take-back is also what raced + ate the Use press = the old "PaP stole my gun" bug).
//
// Routed by the player's CURRENT tier on the held gun (3-tier revamp 2026-06-16):
//   - tier 0 -> acc_do_first_pack: record tier 1 on the base gun (+damage). NO transform.
//   - tier 1 -> acc_do_tier_up (->2): swap to the packed "_up" form (the real transform).
//   - tier 2 -> acc_do_tier_up (->3): in-place damage bump, no asset re-swap.
//   - tier 3 -> acc_do_tier_up: refuses (already max).
function acc_pap_validate( player )   // self = the PaP machine trigger
{
    // [acc] Avogadro "cyberhacker" boss has PaP disabled for 30s (user 2026-07-04): block packing
    // while hacked. The glow is darkened separately by _acc_boss_avogadro. Restores when the hack expires.
    if ( isdefined( level.acc_pap_hacked ) && level.acc_pap_hacked )
        return false;

    w = player GetCurrentWeapon();
    if ( !isdefined( w ) || w == level.weaponNone ) return false;

    acc_utility::levbug( player, "validate w=" + acc_utility::levbug_wname( w ) + " tier=" + get_tier( player, w ) );   // [LEVBUG-TEMP]

    // Action Figure melee: one-off in-place PaP (no _up form) - handle it entirely on its own so the gun
    // pack/transform flow below is never touched. user 2026-06-23.
    if ( is_actionfigure( w ) )
    {
        player thread acc_pap_actionfigure();
        return false;
    }

    // Fire Bow: in-place PaP with no _up form + a statically-"upgraded" weapon def - handle it on its own
    // (dedicated tier counter) so the transform/tier flow below never misreads it. user 2026-07-07.
    if ( is_firebow( w ) )
    {
        player thread acc_pap_firebow();
        return false;
    }

    // THE CYBERJACK: same shape as the Fire Bow (in-place, dedicated tier counter). docs/43, M0 2026-07-17.
    if ( is_cyberjack( w ) )
    {
        player thread acc_pap_cyberjack();
        return false;
    }

    if ( get_tier( player, w ) <= 0 )
    {
        // FIRST pack (tier 0->1): charge the gun's PRICE-TIER T1 cost (TOP 5000 / MID 4000 /
        // BOT 3000), 10% off with The Armory. BONFIRE-SAFE: the cost keeper overrides self.cost
        // for display, so read the machine's TRUE base cost (saved by the keeper) - if a sale
        // dropped it below the stock 5000, honor the sale instead of the per-gun price.
        true_machine = ( IS_TRUE( self.acc_cost_overridden ) ? self.acc_saved_cost : self.cost );
        if ( isdefined( true_machine ) && true_machine < ACC_PAP_STOCK_FIRST_COST )
            cost = true_machine;                                         // bonfire sale wins
        else
            cost = player armory_discount( weapon_tier_cost( w, 1 ) );   // per-gun first-pack price
        player thread acc_do_first_pack( w, cost );
    }
    else
        player thread acc_do_tier_up( w );

    return false;    // ALWAYS block the stock float; both packs happen in-hand, instantly
}

// self = player. 10% Armory discount (Mega Mule Kick OWNED right now - not just the
// persistent Mega flag, which survives a down - counting an EMP-paused perk as owned so a
// boss debuff doesn't drop it, a real loss does). Rounds down to a multiple of 10. Shared
// by the first pack, the tier-up, and the machine cost display.
function armory_discount( cost )
{
    if ( isdefined( self.acc_mega_perks )
         && isdefined( self.acc_mega_perks[ "specialty_additionalprimaryweapon" ] )
         && self.acc_mega_perks[ "specialty_additionalprimaryweapon" ] == true
         && ( self HasPerk( "specialty_additionalprimaryweapon" )
              || ( isdefined( self.disabled_perks ) && IS_TRUE( self.disabled_perks[ "specialty_additionalprimaryweapon" ] ) ) ) )
    {
        cost = int( cost * 0.9 );
        cost = int( cost / 10 ) * 10;
    }
    return cost;
}

// self = player. FIRST pack (tier 0->1), IN PLACE + INSTANT. The 3-tier revamp DEFERS the
// "_up" transform to tier 2, so this pack does NOT swap the asset - it just records tier 1 on the
// HELD gun (base form, or base perk-twin), giving +33% damage. The gun keeps its base
// appearance/behavior; the explosive/akimbo/_up form arrives at tier 2.
// Debounced so one Use-hold can't pack twice.
function acc_do_first_pack( w, cost )
{
    // CRASH GUARD (co-op disconnect audit 2026-06-27): invoked as `player thread`, and replay_pack_draw below
    // has a multi-frame empty-handed wait. Without this endon, a disconnect mid-pack resumes on a FREED player
    // (self minus_to_player_score / fill_full_ammo / self.acc_pap_busy) -> fatal CTD. self = player; the endon
    // only aborts THIS player's own pack thread, which is exactly what we want when they leave.
    self endon( "disconnect" );

    if ( isdefined( self.acc_tier_cd ) && GetTime() < self.acc_tier_cd )
        return;
    self.acc_tier_cd = GetTime() + int( ACC_PAP_PACK_DEBOUNCE * 1000 );

    if ( !isdefined( w ) || w == level.weaponNone ) return;

    // Only PACKABLE guns: a hold with no upgrade path (knife / equipment / already-packed)
    // must NOT be chargeable. packed_form() returns the weapon UNCHANGED when there is no
    // upgrade, so packed==w means "nothing to pack".
    packed = acc_weapon_variants::packed_form( w );
    if ( !isdefined( packed ) || packed == level.weaponNone || packed == w ) return;

    if ( !isdefined( cost ) ) cost = ACC_PAP_FIRST_PACK_COST;
    if ( !( self zm_score::can_player_purchase( cost ) ) )
    {
        self acc_pap_play_on_machine( "zmb_perks_packa_deny" );
        self IPrintLnBold( "^1Not enough points ^7(need " + cost + ")" );
        return;
    }
    self zm_score::minus_to_player_score( cost );

    base = acc_weapon_variants::true_base( w );   // tier keyed by the true base
    if ( !isdefined( self.acc_pap_tier ) ) self.acc_pap_tier = [];
    self.acc_pap_tier[ base ] = 1;
    acc_utility::levbug( self, "first_pack w=" + acc_utility::levbug_wname( w ) + " base=" + acc_utility::levbug_wname( base ) );   // [LEVBUG-TEMP]
    // DEV verify (acc_dev only): confirm the per-pack tier (user 2026-06-25, "Mahem only packs twice" - prove
    // the uniform 3-tier flow runs for every gun incl. launchers). No effect in normal play.
    // [dev] PaP tier-1 on-screen print REMOVED 2026-07-10 (clean screen in hardcoded dev)

    // Tier 1 is a damage-only pack (NO asset swap, NO camo - gold PaP camo removed 2026-06-27).
    // replay_pack_draw re-gives the held weapon AND plays the first-pack "gun comes out" draw for
    // feedback; when the draw anim is disabled (acc_pap_tier_anim 0) tier 1 has no visible change.
    self acc_pap_play_on_machine( "zmb_perks_packa_upgrade" );   // PaP "cook" sound = plasma-gun-fire wav, 3D on the machine (user 2026-06-22)
    self.acc_pap_busy = true;
    if ( getdvarint( "acc_pap_tier_anim", 1 ) != 0 )
        self replay_pack_draw( w );

    self fill_full_ammo( w );   // 100% full clip+reserve (akimbo-aware: fills BOTH dual-wield mags)

    // [acc] SETTLE GATE (user 2026-07-15) - see acc_do_tier_up: keep the reconcile defer up until the
    // engine actually has the packed gun raised, so the tier-1 spd1 twin swap re-switches correctly
    // instead of landing holstered against a stale GetCurrentWeapon (the draw's frag/knife dwell).
    self wait_pack_settled( w );
    self.acc_pap_busy = false;

    self acc_pap_play_on_machine( "zmb_perks_packa_ready" );          // no aat::acquire -> NO alt-ammo
    // PaP tier/benefit TOAST removed (user 2026-06-22): PaP shows NO display/indication - only the machine price.

    // Leviathan spd axis (user 2026-07-09): a tier change can change the axe's desired speed twin -
    // poke the variant reconcile so the swap is immediate (harmless no-op for every other gun).
    acc_weapon_variants::request_reconcile( self );
}

// self = player. Block until the engine's CURRENT weapon really is `w` (two consecutive 50ms polls),
// capped at 1.5s (a player who instantly switches off, or a hold the engine never raises, must not
// wedge acc_pap_busy on). Same problem class as _acc_weapon_variants::wait_box_give_settled: right
// after a raw give/immediate-switch, GetCurrentWeapon() keeps reporting the pre-swap hold for a few
// frames (during replay_pack_draw's empty dwell it can read the FRAG/knife), and any consumer acting
// on that stale value mis-routes. user 2026-07-15 ("switch back to the axe after packing").
function wait_pack_settled( w )
{
    if ( !isdefined( w ) || w == level.weaponNone ) return;
    stable = 0;
    for ( i = 0; i < 30; i++ )   // 30 x 0.05s = 1.5s cap
    {
        if ( ( self GetCurrentWeapon() ) == w )
        {
            stable++;
            if ( stable >= 2 )
            {
                acc_utility::levbug( self, "pack settled on " + acc_utility::levbug_wname( w ) + " after " + ( i * 50 ) + "ms" );   // [LEVBUG-TEMP]
                return;
            }
        }
        else
        {
            stable = 0;
        }
        wait 0.05;
    }
    acc_utility::levbug( self, "pack settle TIMEOUT waiting for " + acc_utility::levbug_wname( w ) );   // [LEVBUG-TEMP]
}

// self = player. Charge + bump the held gun's tier (2 or 3), INSTANT + in place.
//   tier 1 -> 2: the REAL PaP transform - swap to the packed "_up" form (the matching packed
//                TWIN if holding a perk twin), carrying ammo.
//   tier 2 -> 3: damage-only bump, no asset re-swap (replays the draw for feedback).
// Debounced so a single hold can't tier up more than once.
function acc_do_tier_up( w )
{
    // CRASH GUARD (co-op disconnect audit 2026-06-27): invoked as `player thread`; replay_pack_draw / acc_do_transform
    // below yield, so a disconnect mid-tier-up would resume on a FREED player (self minus_to_player_score /
    // fill_full_ammo) -> fatal CTD. self = player; the endon aborts this player's own pack thread cleanly on leave.
    self endon( "disconnect" );

    if ( isdefined( self.acc_tier_cd ) && GetTime() < self.acc_tier_cd )
        return;
    self.acc_tier_cd = GetTime() + int( ACC_PAP_PACK_DEBOUNCE * 1000 );

    base = acc_weapon_variants::true_base( w );   // strips _acc twin suffix so the tier follows recoil swaps
    if ( !isdefined( self.acc_pap_tier ) ) self.acc_pap_tier = [];
    // Effective current tier: stored value, but an already-"_up" gun is at least tier 2.
    cur = ( isdefined( self.acc_pap_tier[ base ] ) ? self.acc_pap_tier[ base ] : 1 );
    if ( zm_weapons::is_weapon_upgraded( w ) && cur < 2 ) cur = 2;

    if ( cur >= ACC_PAP_MAX_TIER )
    {
        return;   // maxed - PaP shows no display (user 2026-06-22); the machine price already reads 0
    }

    next = cur + 1;
    acc_utility::levbug( self, "tier_up IN w=" + acc_utility::levbug_wname( w ) + " cur=" + cur + " next=" + next );   // [LEVBUG-TEMP]
    cost = self armory_discount( weapon_tier_cost( w, next ) );   // per-gun price tier (TOP/MID/BOT) x 10% Armory
    if ( !( self zm_score::can_player_purchase( cost ) ) )
    {
        self acc_pap_play_on_machine( "zmb_perks_packa_deny" );
        self IPrintLnBold( "^1Not enough points ^7(need " + cost + ")" );
        return;
    }

    self acc_pap_play_on_machine( "zmb_perks_packa_upgrade" );   // PaP "cook" sound = plasma-gun-fire wav, 3D on the machine (user 2026-06-22)
    self.acc_pap_busy = true;
    did_transform = false;
    w_expect = w;   // the gun that must end up in the player's hands when the pack settles
    if ( next == 2 )
    {
        // TIER 1 -> 2: the real transform. Swap the held base gun for its packed "_up" form (or matching
        // packed twin). acc_do_transform fills the packed form to 100% ammo ITSELF (on the
        // known packed weapon). Bail WITHOUT charging if no packed form resolves (first pack proved one).
        packed = acc_do_transform( w, base );
        if ( !isdefined( packed ) )
        {
            self.acc_pap_busy = false;
            return;
        }
        did_transform = true;
        w_expect = packed;
    }
    else
    {
        // TIER 2 -> 3: same "_up" asset, damage-only bump. Replay the draw for visible feedback
        // (user 2026-06-15: "do the same exact animation we do for first time pap" on every tier).
        self replay_pack_draw( w );
    }

    self zm_score::minus_to_player_score( cost );
    self.acc_pap_tier[ base ] = next;
    // [dev] PaP tier-N on-screen print REMOVED 2026-07-10 (clean screen in hardcoded dev)   // user 2026-06-25 Mahem pack-count verify
    // Tier 2 is already full (filled inside the transform on the reliable packed ref). Tier 3 keeps the
    // SAME "_up" gun in hand (replay_pack_draw re-gives it), so fill THAT via the original w - NOT the
    // timing-sensitive GetCurrentWeapon (user 2026-06-22: Galil tier-2 wasn't getting full ammo).
    if ( !did_transform )
        self fill_full_ammo( w );

    // [acc] SETTLE GATE (user 2026-07-15 "sometimes you need to switch back to the axe after packing"):
    // hold acc_pap_busy - which reconcile() now defers on - until the engine's current weapon really IS
    // the packed gun. GetCurrentWeapon() lags the raw give/switch by a few frames (during the draw's
    // empty-handed dwell it can even read the FRAG), so an instant reconcile poke saw a stale equipped,
    // swap_weapon skipped its re-switch (was_equipped false), and the tier twin landed HOLSTERED. Only
    // the axe surfaced it because only its desired twin changes with the tier (spd axis).
    self wait_pack_settled( w_expect );
    self.acc_pap_busy = false;
    self acc_pap_play_on_machine( "zmb_perks_packa_ready" ); // no aat::acquire -> NO alt-ammo
    // PaP tier/benefit TOAST removed (user 2026-06-22): no display/indication - only the machine price.

    // Leviathan spd axis (user 2026-07-09): tiers 2/3 change the axe's desired speed twin (the tier-2
    // transform lands its packed spd twin directly since the packed_form routing fix, and tier 3
    // re-twins spd2 -> spd3 here). No-op for other guns. Runs on SETTLED state (gate above).
    acc_weapon_variants::request_reconcile( self );
}

// self = player. PaP the Action Figure melee. It has no "_up" form; instead each PaP tier SWAPS the held figure
// to a faster SPEED TWIN (faster meleeTime = faster swing, +33% per tier - the twins are GDT clones built by
// tools/gen_actionfigure_speed_twins.js; fireTime does NOTHING on a melee weapon, verified live). The tier IS
// which form you hold (actionfigure_tier_of), so it survives re-boxing. Charges the TOP-bucket tier price
// (5000/7500/10000). The machine stays VISIBLE while you hold a twin via make_actionfigure_packable (it marks
// the twins is_weapon_upgraded). user 2026-06-27 (replaced the removed cleave).
function acc_pap_actionfigure()
{
    self endon( "disconnect" );
    if ( isdefined( self.acc_tier_cd ) && GetTime() < self.acc_tier_cd )
        return;
    self.acc_tier_cd = GetTime() + int( ACC_PAP_PACK_DEBOUNCE * 1000 );

    w = self GetCurrentWeapon();
    if ( !is_actionfigure( w ) ) return;

    cur = actionfigure_tier_of( w );
    if ( cur >= ACC_PAP_MAX_TIER )
        return;                                            // maxed (tier 3); the machine price already reads 0
    next = cur + 1;

    // Berzerker carriers (boss item 11, 2026-07-11) pack up the "_brz" ladder so the +35% implant
    // swing persists across PaP tiers (the implant's apply/remove reconciles the ladder itself).
    sfx = ( ( isdefined( self.acc_item_berzerker ) && self.acc_item_berzerker ) ? "_brz" : "" );
    twin = GetWeapon( "t8_melee_figure_fast" + next + sfx );
    if ( !isdefined( twin ) || twin == level.weaponNone )  // speed twin not in this build
        return;

    cost = self armory_discount( weapon_tier_cost( w, next ) );
    if ( !( self zm_score::can_player_purchase( cost ) ) )
    {
        self acc_pap_play_on_machine( "zmb_perks_packa_deny" );
        self IPrintLnBold( "^1Not enough points ^7(need " + cost + ")" );
        return;
    }

    self acc_pap_play_on_machine( "zmb_perks_packa_upgrade" );
    self zm_score::minus_to_player_score( cost );

    // Swap to the faster twin. GIVE-then-TAKE so there is never an empty-handed frame (co-op disconnect-safe).
    self GiveWeapon( twin );
    self SwitchToWeapon( twin );
    if ( w != twin ) self TakeWeapon( w );

    self acc_pap_play_on_machine( "zmb_perks_packa_ready" );
}

// Play a PaP sound (the plasma "cook" / ready / deny) ON the nearest Pack-a-Punch machine (3D),
// so it emanates from the PaP instead of following the buyer (user 2026-06-22). self = player.
// acc_audio.csv: zmb_perks_packa_upgrade now points at the plasma-gun-fire wav (3D).
function acc_pap_play_on_machine( alias )
{
    m = acc_find_pap_machine( self );
    if ( isdefined( m ) )
        m PlaySound( alias );      // 3D, from the PaP machine
    else
        acc_utility::play_sound_at_origin( self.origin, alias );   // fallback: STATIC at the buy spot (= the PaP), never the moving player (user 2026-06-24: 3D alias was following the buyer)
}

// Nearest "pack_a_punch" script_noteworthy ent to the player = the PaP they are using. It is the
// USE TRIGGER (has an origin, which PlaySound positions fine) - same handle the cost keeper and
// _acc_perk_lights use: GetEntArray( "pack_a_punch", "script_noteworthy" ).
function acc_find_pap_machine( player )
{
    triggers = GetEntArray( "pack_a_punch", "script_noteworthy" );
    best = undefined;
    best_d = 999999999;
    foreach ( t in triggers )
    {
        if ( !isdefined( t ) ) continue;
        d = DistanceSquared( player.origin, t.origin );
        if ( d < best_d ) { best_d = d; best = t; }
    }
    // Also weigh our STANDALONE Paradise PaP(s). They are deliberately NOT
    // "pack_a_punch" script_noteworthy ents (that name would feed stock's
    // singleton GetEnt + the cost keeper + perk-lights), so they register here
    // instead. This affects pack-SOUND positioning ONLY - so the cook/ready
    // sounds play at the Paradise machine, not the far surface one. It can never
    // touch load / packing / tier / cost / the surface PaP. (spawn_paradise_pap_at)
    if ( isdefined( level.acc_custom_pap_machines ) )
    {
        foreach ( t in level.acc_custom_pap_machines )
        {
            if ( !isdefined( t ) ) continue;
            d = DistanceSquared( player.origin, t.origin );
            if ( d < best_d ) { best_d = d; best = t; }
        }
    }
    return best;
}

// =============================================================================
// PARADISE 2nd Pack-a-Punch - STANDALONE custom vendor (user 2026-06-25).
//
// WHY NOT A 2ND STOCK MACHINE: stock supports exactly ONE PaP. spawn_init
// (_zm_pack_a_punch.gsc:82-131) renames EVERY "zm_pack_a_punch" zbarrier to the
// shared "vending_packapunch", and vending_weapon_upgrade() (:345) does a
// SINGULAR GetEnt("vending_packapunch") that FATALS at LOAD with two of them
// ("getent ... more than one entity"). That is exactly what broke the surface
// PaP the previous time a 2nd PaP was added (see acc_dedupe_pack_a_punch in the
// entry script + memory duplicate-pap-load-crash).
//
// THE FIX: do NOT register a 2nd stock machine at all. Build a fully self-
// contained vendor (same idiom as the Paradise Mystery Box) that reuses our OWN
// in-place tier-pack path - the EXACT same acc_do_first_pack / acc_do_tier_up /
// acc_pap_actionfigure the surface PaP routes through. The PaP tier lives on
// player.acc_pap_tier[ true_base ] (NOT on any machine), so packing at the
// surface and continuing here reads the SAME stored tier - it can NEVER reset
// (the specific bug the user warned about). The trigger NEVER carries the
// "zm_pack_a_punch" targetname, so stock's singleton GetEnt is untouched and the
// surface PaP cannot break. Pure GSC - no .map entity, no bake.
// =============================================================================
function spawn_paradise_pap_at( origin, yaw )
{
    if ( !isdefined( yaw ) ) yaw = 0;

    m = spawn( "script_model", origin );
    m setmodel( "p9_fxanim_zm_gp_pap_xmodel" );   // CW/BO6 PaP machine (ALXS pack, user 2026-07-02) - matches the surface machine model swap
    m.angles = ( 0, yaw, 0 );

    t = spawn( "trigger_radius_use", origin + ( 0, 0, 40 ), 0, 72, 100 );
    t TriggerIgnoreTeam();          // REQUIRED for a script-spawned use trigger to be usable (stock _zm_perks.gsc:1523)
    t UseTriggerRequireLookAt();
    t SetCursorHint( "HINT_NOICON" );
    t SetHintString( "Hold ^3[{+activate}]^7  Pack-a-Punch" );
    t.acc_pap_model = m;

    // Register for pack-sound positioning only (acc_find_pap_machine). This is the
    // ONLY shared hook we touch and it is purely cosmetic (where the sound plays).
    if ( !isdefined( level.acc_custom_pap_machines ) ) level.acc_custom_pap_machines = [];
    ARRAY_ADD( level.acc_custom_pap_machines, t );

    t thread paradise_pap_use_loop();
    t thread paradise_pap_hint_loop();

    acc_utility::log( "pap_levels: standalone Paradise PaP spawned at " + origin );
}

// self = the Paradise PaP trigger. On each Use-hold, dispatch EXACTLY like the surface
// PaP's acc_pap_validate (Action Figure / first pack / tier-up) but drive it ourselves -
// the real debounce + charge + tier write all live inside the player-scoped pack functions.
function paradise_pap_use_loop()
{
    self endon( "death" );
    level endon( "end_game" );

    for ( ;; )
    {
        self waittill( "trigger", player );
        if ( !isdefined( player ) || !zm_utility::is_player_valid( player ) ) continue;
        if ( IS_TRUE( player.acc_pap_busy ) ) { wait 0.05; continue; }

        // [acc] Avogadro "cyberhacker" hack: PaP disabled for 30s (user 2026-07-04) - ignore the Use.
        if ( isdefined( level.acc_pap_hacked ) && level.acc_pap_hacked ) { wait 0.1; continue; }

        w = player GetCurrentWeapon();
        if ( !isdefined( w ) || w == level.weaponNone ) { wait 0.1; continue; }

        // Same routing as acc_pap_validate, minus the stock-machine bonfire-cost read
        // (there is no stock machine here and no bonfire powerup in this map).
        if ( is_actionfigure( w ) )
        {
            player thread acc_pap_actionfigure();
        }
        else if ( is_firebow( w ) )
        {
            player thread acc_pap_firebow();   // dedicated in-place Fire Bow tier (see acc_pap_validate)
        }
        else if ( is_cyberjack( w ) )
        {
            player thread acc_pap_cyberjack(); // dedicated in-place CYBERJACK tier (see acc_pap_validate)
        }
        else if ( get_tier( player, w ) <= 0 )
        {
            cost = player armory_discount( weapon_tier_cost( w, 1 ) );   // per-gun first-pack price (TOP/MID/BOT)
            player thread acc_do_first_pack( w, cost );
        }
        else
        {
            player thread acc_do_tier_up( w );   // computes its own next-tier cost
        }

        wait 0.1;   // stop a single completed hold re-firing the trigger (player.acc_tier_cd is the real debounce)
    }
}

// self = the Paradise PaP trigger. Keep the displayed price equal to the nearby player's
// ACTUAL next-pack charge, mirroring pap_cost_display_keeper but driving our OWN hint
// (the stock cost machinery does not apply to a custom trigger). Prices stay numeric
// (memory vague-ui-no-magnitudes: only perk/PaP *benefit* text is qualitative).
function paradise_pap_hint_loop()
{
    self endon( "death" );
    level endon( "end_game" );
    level flag::wait_till( "initial_blackscreen_passed" );

    for ( ;; )
    {
        np = nearest_pap_player( self.origin );
        w = undefined;
        if ( isdefined( np ) ) w = np GetCurrentWeapon();
        ht = paradise_pap_hint_text( np, w );
        // Only re-SetHintString when the TEXT actually changes (mirrors _acc_perk_info's acc_shown_cost
        // guard). The displayed cost is bounded to a small discrete set - 3 price buckets x 3 tiers x the
        // armory-discount toggle ~= 18 strings - so it does NOT overflow the 250-cap triggerstring cache;
        // but the un-guarded 4x/sec SetHintString re-registered the same string every tick (pure waste,
        // and the exact looped-live-value anti-pattern that crashed the soul box). Rule (memory
        // triggerstring-cap-hint-strings): a hint may interpolate ONLY a small, bounded value.
        if ( !isdefined( self.acc_last_pap_hint ) || self.acc_last_pap_hint != ht )
        {
            self SetHintString( ht );
            self.acc_last_pap_hint = ht;
        }
        wait 0.25;
    }
}

// The hint must ask the TIER question, not the ASSET question (user 2026-07-15). pap_weapon_packable is an
// "is there an upgrade ASSET" test, and for a BARE "_up" gun - no _acc twin, i.e. every player WITHOUT a Mega
// perk after the tier-1->2 transform - packed_form returns the weapon ITSELF (_acc_weapon_variants.gsc:1095,
// "stem already packed"), so packable read FALSE and this early-returned the PRICE-LESS generic string even
// though paradise_pap_use_loop happily routes the same gun to acc_do_tier_up and charges tier 3. Same gate also
// made the MAX string below UNREACHABLE for a bare _up, so a maxed gun still advertised a Use-hold that
// acc_do_tier_up silently no-ops (cur >= ACC_PAP_MAX_TIER). A Mega-twin holder HID the bug (packed_form -> the
// bare _up != the held twin -> packable TRUE -> correct price), which is why it only ever reads as "no price on
// normal guns, only after tier 2, only without a Mega". FIX: let an already-upgraded gun through as well,
// mirroring the surface keeper's is_upgraded_safe branch (:234). get_tier already clamps an _up gun to >= 2
// (:1563) with the SAME rule acc_do_tier_up charges by (:727), so hint == charge for every form. The Action
// Figure / Fire Bow are unaffected - pap_weapon_packable still short-circuits both in-place packers (:529-530).
function paradise_pap_hint_text( player, w )
{
    if ( !isdefined( player ) || !isdefined( w ) || w == level.weaponNone ||
         ( !pap_weapon_packable( w ) && !is_upgraded_safe( w ) ) )
        return "Hold ^3[{+activate}]^7  Pack-a-Punch";

    tier = get_tier( player, w );
    if ( tier >= ACC_PAP_MAX_TIER )
        return "^2Pack-a-Punch - MAX";

    cost = player armory_discount( weapon_tier_cost( w, tier + 1 ) );
    return "Hold ^3[{+activate}]^7  Pack-a-Punch  ^2[" + cost + "]";
}

// self = player. Top a freshly-packed weapon to 100% full ammo - reserve AND magazine - for ANY weapon,
// dual-wield included. GiveMaxAmmo only fills the (shared) reserve, never the magazine. A DUAL-WIELD gun
// (the akimbo "_rdw_up" PaP forms - PDW, M1911) has a SECOND magazine on its off-hand weapon
// (weapon.dualWieldWeapon); filling only the main clip left one gun empty ("PDW PaP ammo issue", user
// 2026-06-22). Stock tracks both clips separately (_zm.gsc:3057-3136 store/restore weapon +
// weapon.dualWieldWeapon). clipSize is in rounds for both wield types (consistent units).
function fill_full_ammo( w )
{
    if ( !isdefined( w ) || w == level.weaponNone ) return;

    self GiveMaxAmmo( w );                                            // RESERVE (right hand)
    if ( isdefined( w.clipSize ) ) self SetWeaponAmmoClip( w, w.clipSize );   // magazine (right hand)

    // Dual-wield (akimbo "_rdw_up": PDW/M1911): the off-hand is a SEPARATE weapon entity with its OWN
    // reserve AND clip - GiveMaxAmmo/SetWeaponAmmoClip on the main weapon do NOT touch it, so it stays
    // empty after PaP ("PDW reserve/clip not filling", user 2026-06-22). Stock Max Ammo reaches it only
    // because it loops GetWeaponsList; we hit it directly via weapon.dualWieldWeapon.
    if ( isdefined( w.isDualWield ) && w.isDualWield
         && isdefined( w.dualWieldWeapon ) && w.dualWieldWeapon != level.weaponNone )
    {
        dw = w.dualWieldWeapon;
        self GiveMaxAmmo( dw );                                       // RESERVE (off hand)
        if ( isdefined( dw.clipSize ) ) self SetWeaponAmmoClip( dw, dw.clipSize );   // magazine (off hand)
    }

    // PDW akimbo-PaP ammo FIX (user 2026-06-22 - the long-standing "15 left / 17 right / 18 reserve" bug):
    // the Skye s1_pdw_rdw_up ships TWO data errors no generic fill catches - (1) the OFF-HAND magazine's
    // clipSize is 15, not the main's 17 (akimbo guns must share a magazine size); (2) maxAmmo is a broken
    // 920 that the engine clamps to ~18 SHARED reserve, not the intended 306. Stock akimbo keeps ONE shared
    // reserve on the MAIN weapon + SEPARATE per-gun magazines (verified vs _zm.gsc:3055-3062: stock_amt =
    // GetWeaponAmmoStock(weapon); left_clip_amt = the dualWieldWeapon's own clip), which is exactly the
    // symptom. So we set the shared reserve ONCE on the main + BOTH magazines explicitly to the docs/04
    // numbers (PaP PDW = clip 17 / reserve 306 combined). Gated on the akimbo-PDW name ONLY - the base PDW
    // (not dual-wield), the M1911/Five-Seven akimbos (no "pdw" in name), and every other gun are untouched.
    if ( isdefined( w.isDualWield ) && w.isDualWield && IsSubStr( w.name, "pdw" ) )
    {
        self SetWeaponAmmoStock( w, 306 );          // shared akimbo reserve (docs/04) - overrides the broken ~18
        self SetWeaponAmmoClip( w, 17 );            // right-hand magazine
        if ( isdefined( w.dualWieldWeapon ) && w.dualWieldWeapon != level.weaponNone )
            self SetWeaponAmmoClip( w.dualWieldWeapon, 17 );   // left-hand magazine (Skye shipped 15)
    }

    // DEV readout (one-flag gated, remove once verified): prints the ACTUAL clip/reserve the engine set,
    // so a "reserve not filling" report can be checked against real numbers (user 2026-06-22 triple-check).
    if ( 0 )   // DEV PaP-ammo readout REMOVED FROM SCREEN 2026-07-10 (clean screen in hardcoded dev); restore IS_TRUE( level.acc_dev ) to re-enable
    {
        msg = "^3PaP ammo " + w.name + ": clip " + self GetWeaponAmmoClip( w ) + " / reserve " + self GetWeaponAmmoStock( w );
        if ( isdefined( w.isDualWield ) && w.isDualWield && isdefined( w.dualWieldWeapon ) && w.dualWieldWeapon != level.weaponNone )
            msg = msg + "  ^5[offhand clip " + self GetWeaponAmmoClip( w.dualWieldWeapon ) + " / reserve " + self GetWeaponAmmoStock( w.dualWieldWeapon ) + "]";
        self IPrintLnBold( msg );
    }
}

// self = player. The tier-1 -> tier-2 asset transform: swap the held gun for its packed "_up"
// form (the matching packed TWIN when holding a perk twin), carrying clip+reserve across
// (cap-delta, clamp-at-0). Mirrors the stock PaP give (GiveWeapon, _zm_weapons.gsc:2584/2597).
// Returns true on a real swap, false if no upgrade resolves (caller must not charge). NOTE:
// the tier is recorded by the CALLER after the charge succeeds, so don't write acc_pap_tier here.
// (Gold PaP camo option removed 2026-06-27 - the "_up" form is given with no camo.)
function acc_do_transform( w, base )
{
    if ( !isdefined( w ) || w == level.weaponNone ) return undefined;

    packed = acc_weapon_variants::packed_form( w );
    if ( !isdefined( packed ) || packed == level.weaponNone || packed == w ) return undefined;

    // [LEVBUG-TEMP] forensics (see _acc_dev levbug_forensics)
    acc_utility::levbug( self, "transform IN w=" + acc_utility::levbug_wname( w ) + " packed=" + acc_utility::levbug_wname( packed ) );

    self GiveWeapon( packed );
    self SwitchToWeaponImmediate( packed );
    acc_utility::levbug( self, "transform gave+switched " + acc_utility::levbug_wname( packed ) );   // [LEVBUG-TEMP]

    // PaP = 100% full ammo (user 2026-06-22). Fill the PACKED form DIRECTLY here, while we hold a reliable
    // reference to it - NOT via the caller's GetCurrentWeapon(), which can still report the pre-swap weapon
    // for a frame (that left a single-wield gun like the Galil under-filled at tier 2). fill_full_ammo uses
    // the PACKED gun's clip/reserve CAPS (the "_up" form usually holds MORE), and handles dual-wield. This
    // replaces the old carry-current-ammo math entirely - PaP now always lands full.
    self fill_full_ammo( packed );

    self TakeWeapon( w );
    acc_utility::levbug( self, "transform took " + acc_utility::levbug_wname( w ) );   // [LEVBUG-TEMP]

    // (LEVIATHAN melee-slot sync REMOVED 2026-07-15: the axe is NOT a melee-slot weapon at runtime -
    // writing it into current_melee_weapon made Widow's Wine eat the axe + clobbered the Berzerker
    // knife. See _acc_weapon_variants::swap_weapon removal note; the real Five-Seven-reset fix is the
    // stale-equipped HasWeapon guards there.)

    acc_utility::levbug( self, "transform OUT" );   // [LEVBUG-TEMP]
    // Return the PACKED weapon (2026-07-15; was a bool) so the caller can settle-wait on the exact
    // gun that must end up in the player's hands. undefined = no transform (caller must not charge).
    return packed;
}

// self = player. Replay the first-pack "gun comes out" draw on a tier-up (user 2026-06-15).
//
// APPROACH (user's idea, 2026-06-15): a tier-up keeps the SAME packed asset, and every in-place
// re-deploy attempt either showed nothing (re-giving the already-held weapon is a no-op) or
// swapped the player onto their OTHER gun (giving the un-packed base conflicts with the held
// packed gun, and taking the current gun auto-switches to the next one). The robust fix:
//   - SNAPSHOT every primary + its ammo,
//   - TAKE THEM ALL (player is empty-handed for a split second, so there is nothing for the
//     engine to fall back to),
//   - GIVE THE PACKED GUN BACK FIRST and switch to it - a FRESH give plays the first-raise/
//     re-cock, exactly like the first pack,
//   - RESTORE the other guns WITHOUT switching, so the packed gun stays in hand.
// No base form -> no weapon-family conflict; everything is taken -> no auto-switch target.
//
// Ammo is saved/restored per gun. Wrapped in increment_is_drinking()/disable_player_move_states()
// like the stock knuckle crack so the variant reconcile loop + player input can't fight the swap.
// Gated by acc_pap_tier_anim (default 1) so tier-ups can be reverted to instant live (set 0).
// Tune knob: the empty-handed dwell is EMPTY_FRAMES below.
function replay_pack_draw( w )
{
    if ( getdvarint( "acc_pap_tier_anim", 1 ) == 0 ) return;
    if ( !isdefined( w ) || w == level.weaponNone ) return;
    if ( ( self GetCurrentWeapon() ) != w ) return; // only animate the gun actually in hand

    // Snapshot every primary + ammo. Include the held gun even if the primaries list omits the
    // starting-pistol slot (mirrors reconcile()'s same guard).
    prims = self GetWeaponsListPrimaries();
    have_w = false;
    for ( i = 0; i < prims.size; i++ ) { if ( prims[ i ] == w ) have_w = true; }
    if ( !have_w ) prims[ prims.size ] = w;

    saved_w = [];
    saved_clip = [];
    saved_stock = [];
    for ( i = 0; i < prims.size; i++ )
    {
        p = prims[ i ];
        if ( !isdefined( p ) || p == level.weaponNone ) continue;
        n = saved_w.size;
        saved_w[ n ] = p;
        saved_clip[ n ] = self GetWeaponAmmoClip( p );
        saved_stock[ n ] = self GetWeaponAmmoStock( p );
    }

    self zm_utility::increment_is_drinking();
    self zm_utility::disable_player_move_states( true );

    acc_utility::levbug( self, "draw IN w=" + acc_utility::levbug_wname( w ) + " taking " + saved_w.size + " prims" );   // [LEVBUG-TEMP]

    // Take EVERY primary - now the held gun has nothing to auto-switch onto when removed.
    for ( i = 0; i < saved_w.size; i++ )
        self TakeWeapon( saved_w[ i ] );

    // Brief empty-handed dwell so the takes process and the packed gun re-gives FRESH (a
    // same-frame take+give collapses to a no-op = no draw).
    EMPTY_FRAMES = 2;
    for ( i = 0; i < EMPTY_FRAMES; i++ ) WAIT_SERVER_FRAME;
    if ( !isdefined( self ) ) return;

    // Packed gun back FIRST + raise it -> the first-raise/re-cock plays (fresh give). No camo
    // option (gold PaP camo removed 2026-06-27) - the base / "_up" gun is re-given as-is.
    self GiveWeapon( w );
    self SwitchToWeaponImmediate( w );
    acc_utility::levbug( self, "draw regave+switched " + acc_utility::levbug_wname( w ) );   // [LEVBUG-TEMP]

    // (LEVIATHAN melee-slot sync REMOVED 2026-07-15 - see _acc_weapon_variants::swap_weapon removal
    // note: the axe never legitimately occupies current_melee_weapon; syncing it there broke Widow's
    // Wine + the Berzerker knife.)

    // Restore the rest (ammo for all), WITHOUT switching, so the packed gun stays in hand.
    for ( i = 0; i < saved_w.size; i++ )
    {
        p = saved_w[ i ];
        if ( !isdefined( p ) || p == level.weaponNone ) continue;
        if ( p != w )
            self GiveWeapon( p );
        self SetWeaponAmmoStock( p, saved_stock[ i ] );
        self SetWeaponAmmoClip( p, saved_clip[ i ] );
    }

    self zm_utility::enable_player_move_states();
    self zm_utility::decrement_is_drinking();
    acc_utility::levbug( self, "draw OUT" );   // [LEVBUG-TEMP]
}

function pap_tier_machine_watcher()
{
    level endon( "end_game" );
    level flag::wait_till( "initial_blackscreen_passed" );

    // All machine use routes through our validation (first pack via stock, tier-ups in
    // place). NO parallel trigger -> no take-back theft. We do NOT touch the stock
    // visibility loop, so the machine's own hint shows normally and there is no flicker
    // (no second trigger to fight). Bind on EVERY pack_a_punch machine, not just the singular
    // level.pack_a_punch (user 2026-06-25: a 2nd PaP in Paradise) - else the 2nd machine falls
    // through to the stock float-pack. Poll like the cost keeper (machines spawn during stock PaP init).
    machines = [];
    for ( i = 0; i < 60; i++ )
    {
        machines = GetEntArray( "pack_a_punch", "script_noteworthy" );
        if ( machines.size > 0 ) break;
        wait 0.5;
    }
    n = 0;
    foreach ( m in machines )
    {
        if ( isdefined( m ) ) { m.custom_validation = &acc_pap_validate; n++; }
    }
    // CRITICAL BUGFIX (user 2026-06-25): stock reads the validation hook from the SINGULAR
    // level.pack_a_punch.custom_validation (_zm_pack_a_punch.gsc:399-401), NOT the per-trigger
    // m.custom_validation set above. Binding ONLY per-trigger (the 2026-06-25 "bind on every
    // machine" change) left level.pack_a_punch.custom_validation undefined whenever any machine was
    // found, so stock SKIPPED our validate and ran the stock float-pack ("place gun inside") for
    // EVERY gun - the custom in-place tier system was fully bypassed. Bind the singular handle stock
    // actually reads; stock calls it with self = whichever trigger was used, so it routes EVERY
    // machine (incl. the 2nd Paradise PaP) through acc_pap_validate. The per-trigger field is kept
    // (harmless) but it is the singular bind that makes PaP work.
    if ( isdefined( level.pack_a_punch ) )
    {
        level.pack_a_punch.custom_validation = &acc_pap_validate;
        if ( n == 0 ) n = 1;
    }
    acc_utility::log( "pap_levels: tier-up custom_validation bound (singular level.pack_a_punch + " + n + " per-trigger)" );

    make_actionfigure_packable();   // let the stock machine SHOW for the no-_up Action Figure (user 2026-06-24 fix)
    make_firebow_packable();        // same fix for the no-_up Fire Bow (upgrade=self + is_weapon_upgraded) (user 2026-07-07)
    make_cyberjack_packable();      // same fix for THE CYBERJACK (apex_lstar / L-STAR chassis, same no-_up shape) (docs/43, 2026-07-17)
    make_mahem_pap_visible_to_tier3();   // un-exempt the launcher from AAT so its machine stays visible past pack 2 (user 2026-06-26)
    make_war_machine_pap_visible_to_tier3();   // same un-exempt for the War Machine drum GL (user 2026-07-09; its CSV row also ships is_aat_exempt TRUE)
    make_havoc_pap_visible_to_tier3();   // Havoc (Apex energy special, replaces China Lake): always-safe un-exempt (no-op if not aat-exempt), same gate as the Mahem (user 2026-07-06)
    make_thundergun_pap_visible_to_tier3();   // same bug, same fix, for the wonder weapon (user 2026-07-02: "can only PaP twice")
    make_blasto_pap_visible_to_tier3();       // Blast-O-Matic ships is_aat_exempt TRUE - same gate, same fix (user 2026-07-03)
}

// Thundergun tier-3 fix (user 2026-07-02) - the EXACT Mahem bug: stock hides the PaP machine
// for an _up gun unless weapon_supports_aat = is_weapon_upgraded && !is_exempt, and the wonder
// weapon's upgraded form ("thundergun_upgraded", _zm_weap_thundergun.gsc:32) is AAT-EXEMPT ->
// after pack 2 (tier-1 record + the _up transform) the machine never shows again, capping the
// ladder at 2 interactions. Un-exempting it makes the machine show for tier 3 (the in-place
// bump). NOTE: our packs never aat::acquire (see acc_do_first_pack), so un-exempting cannot
// hand the thundergun an alt-ammo type - it only fixes the visibility gate, exactly like the
// Mahem. (Tier damage mults apply via _acc_damage's weapon-carried hits; the thundergun's
// one-shot FLING is a weaponless DoDamage the ladder never touched - docs/04 - so tier 3 buys
// the ladder slot/HUD + any weapon-carried damage, not a bigger fling.)
function make_thundergun_pap_visible_to_tier3()
{
    if ( !isdefined( level.aat_exemptions ) ) return;
    up = GetWeapon( "thundergun_upgraded" );
    if ( !isdefined( up ) || up == level.weaponNone ) up = GetWeapon( "thundergun_upgraded_zm" );
    if ( !isdefined( up ) || up == level.weaponNone ) return;
    up = zm_weapons::get_nonalternate_weapon( up );

    was_exempt = isdefined( level.aat_exemptions[ up ] );
    level.aat_exemptions[ up ] = undefined;
    acc_utility::log( "pap_levels: Thundergun PaP-to-tier3 fix - was_aat_exempt=" + was_exempt + " (machine now stays visible past pack 2)" );
}

// THE Action Figure PaP-visibility fix (user 2026-06-24). The AF has NO "_up" asset, so stock's
// can_upgrade_weapon() returns false for it (it checks IsDefined( level.zombie_weapons[root].upgrade )),
// and player_use_can_pack_now() therefore HIDES the PaP machine while you hold the AF - you could never
// trigger a pack (the reason "i cant even pap"). Fix: point the AF's .upgrade at ITSELF so the visibility
// gate passes. Stock never actually swaps to it - acc_pap_validate intercepts the AF and returns false
// BEFORE the stock pack/swap runs, doing the in-place tier bump (acc_pap_actionfigure) instead.
function make_actionfigure_packable()
{
    if ( !isdefined( level.zombie_weapons ) ) return;
    w = GetWeapon( "t8_melee_figure" );   // the HELD/inventory form (what GetCurrentWeapon returns at the PaP)
    if ( !isdefined( w ) || w == level.weaponNone ) return;
    if ( isdefined( level.zombie_weapons[ w ] ) && !isdefined( level.zombie_weapons[ w ].upgrade ) )
        level.zombie_weapons[ w ].upgrade = w;   // self-upgrade: satisfies the gate only; real pack is in-place

    // The per-tier SPEED TWINS must ALSO keep the PaP machine VISIBLE while held, so you can pack to the next
    // tier. Mark each is_weapon_upgraded (level.zombie_weapons_upgraded) so weapon_supports_aat() shows the
    // machine - the Mahem-visibility pattern (see make_mahem_pap_visible_to_tier3). Our acc_pap_validate
    // intercepts the pack FIRST + does the swap (returns false), so stock never runs a real upgrade. AAT is
    // globally off, so this grants NO alternate ammo - it is purely the machine-visibility gate. user 2026-06-27.
    if ( isdefined( level.zombie_weapons_upgraded ) )
    {
        for ( i = 1; i <= ACC_PAP_MAX_TIER; i++ )
        {
            tw = GetWeapon( "t8_melee_figure_fast" + i );
            if ( isdefined( tw ) && tw != level.weaponNone )
                level.zombie_weapons_upgraded[ tw ] = w;
            // Berzerker (_brz) tier twins (boss item 11, 2026-07-11): same visibility net.
            tw = GetWeapon( "t8_melee_figure_fast" + i + "_brz" );
            if ( isdefined( tw ) && tw != level.weaponNone )
                level.zombie_weapons_upgraded[ tw ] = w;
        }
        // The tier-0 berzerker form must ALSO keep the machine visible (it is not upgraded and,
        // unlike the base figure, has no level.zombie_weapons entry to point .upgrade at).
        tw = GetWeapon( "t8_melee_figure_brz" );
        if ( isdefined( tw ) && tw != level.weaponNone )
            level.zombie_weapons_upgraded[ tw ] = w;
    }
    acc_utility::log( "pap_levels: Action Figure + speed twins (+brz forms) marked packable" );
}

// THE Fire Bow PaP-visibility fix (user 2026-07-07). Same root cause as the Action Figure: the demon-gate bow
// has NO "_up" asset (CSV upgrade=self), so stock's can_upgrade_weapon() is false and player_use_can_pack_now()
// HIDES the PaP machine while you hold it - "i cant pap the bow". It ALSO ships is_weapon_upgraded=true and may
// be AAT-EXEMPT (HB21 pack), so the weapon_supports_aat fallback can't save it either. Fix = BOTH nets: point
// the bow's .upgrade at ITSELF (satisfies the can_pack gate) AND un-exempt it from AAT (satisfies the aat gate).
// Stock never swaps - acc_pap_validate intercepts the bow (is_firebow) and returns false BEFORE the stock pack,
// doing the in-place tier bump (acc_pap_firebow). AAT is globally off, so un-exempting grants NO alternate ammo.
function make_firebow_packable()
{
    w = GetWeapon( "elemental_bow_demongate" );   // the HELD form GetCurrentWeapon returns at the PaP
    if ( !isdefined( w ) || w == level.weaponNone ) return;

    if ( isdefined( level.zombie_weapons ) && isdefined( level.zombie_weapons[ w ] ) && !isdefined( level.zombie_weapons[ w ].upgrade ) )
        level.zombie_weapons[ w ].upgrade = w;    // self-upgrade: satisfies the visibility gate only; real pack is in-place

    if ( isdefined( level.aat_exemptions ) && isdefined( level.aat_exemptions[ w ] ) )
        level.aat_exemptions[ w ] = undefined;    // un-exempt so weapon_supports_aat also keeps the machine visible

    acc_utility::log( "pap_levels: Fire Bow marked packable (self-upgrade + un-exempt)" );
}

// THE CYBERJACK PaP-visibility fix - the Fire Bow's exact fix on the L-STAR chassis (docs/43;
// chassis swap 2026-07-17): no "_up" asset (CSV upgrade=self) so can_upgrade_weapon() is false and the
// machine HIDES, plus a possible pack AAT exemption. Both nets: .upgrade at ITSELF + un-exempt.
// Stock never swaps - acc_pap_validate intercepts (is_cyberjack) and does the in-place bump.
function make_cyberjack_packable()
{
    w = GetWeapon( "apex_lstar" );   // the HELD form GetCurrentWeapon returns at the PaP
    if ( !isdefined( w ) || w == level.weaponNone ) return;

    if ( isdefined( level.zombie_weapons ) && isdefined( level.zombie_weapons[ w ] ) && !isdefined( level.zombie_weapons[ w ].upgrade ) )
        level.zombie_weapons[ w ].upgrade = w;    // self-upgrade: satisfies the visibility gate only; real pack is in-place

    if ( isdefined( level.aat_exemptions ) && isdefined( level.aat_exemptions[ w ] ) )
        level.aat_exemptions[ w ] = undefined;    // un-exempt so weapon_supports_aat also keeps the machine visible

    acc_utility::log( "pap_levels: CYBERJACK marked packable (self-upgrade + un-exempt)" );
}

// THE Mahem "only packs TWICE" fix (user 2026-06-26 - after MANY failed attempts that all chased the
// wrong table). FULL trace through stock _zm_pack_a_punch.gsc + aat_shared.gsc + _zm_weapons.gsc:
//   - Packs 1+2 work: you HOLD the base s1_mahem at tier 0/1, then acc_do_transform swaps you to the
//     packed s1_mahem_up at tier 2. For pack 3 the machine must stay VISIBLE while you hold s1_mahem_up.
//   - Stock's player_use_can_pack_now() shows the machine only if  can_pack_weapon(held) ||
//     weapon_supports_aat(held).  For ANY "_up" gun can_pack_weapon() is FALSE - is_weapon_included(_up)
//     fails because stock add_zombie_weapon registers ONLY the BASE in level.zombie_weapons, never the
//     _up. So EVERY gun depends on weapon_supports_aat(_up) for the tier-2->3 visibility.
//     weapon_supports_aat() = is_weapon_upgraded(root) && !aat::is_exempt_weapon(weapon).
//   - is_weapon_upgraded(s1_mahem_up) is ALREADY true (stock add_zombie_weapon line 554 maps EVERY CSV
//     upgrade into level.zombie_weapons_upgraded) - so the upgrade table was NEVER the bug, and the old
//     register_special_upgrades patch is a no-op for the Mahem. THE actual blocker: the Mahem's CSV row
//     sets AAT_EXEMPT (col 17) = TRUE because it is a launcher, so load_weapon_spec_from_table calls
//     aat::register_aat_exemption(s1_mahem_up) -> level.aat_exemptions flags it -> is_exempt_weapon()
//     returns true -> weapon_supports_aat() returns FALSE -> the machine HIDES the instant you finish
//     pack 2. Conventional guns leave that column blank, so their machine stays up = they pack 3x.
// FIX: drop s1_mahem_up from level.aat_exemptions. AAT is GLOBALLY OFF in this map
// (zm_abandoned_cyber_city.gsc sets level.aat_in_use = false right after zm_usermap::main), so this hands
// out NO alternate ammo - it ONLY restores the machine's visibility so our acc_pap_validate
// custom_validation runs the in-place tier-3 pack (vending_weapon_upgrade calls custom_validation FIRST,
// before any AAT/upgrade branch; it returns false -> stock does nothing), exactly like every conventional
// _up gun. The exemption is set during zm_usermap::main (before blackscreen); this runs at
// initial_blackscreen_passed, long before any player can finish a 2nd pack. Keyed via
// get_nonalternate_weapon to match how is_exempt_weapon reads the table.
function make_mahem_pap_visible_to_tier3()
{
    if ( !isdefined( level.aat_exemptions ) ) return;
    up = GetWeapon( "s1_mahem_up" );
    if ( !isdefined( up ) || up == level.weaponNone ) return;
    up = zm_weapons::get_nonalternate_weapon( up );   // is_exempt_weapon() normalizes the held weapon this way

    was_exempt = isdefined( level.aat_exemptions[ up ] );
    level.aat_exemptions[ up ] = undefined;   // un-exempt -> weapon_supports_aat(s1_mahem_up) true -> machine stays visible past pack 2

    // Proof-of-fix log (kept, since this bug ate many sessions): the two conditions weapon_supports_aat
    // needs. Expect "was_aat_exempt=1 is_weapon_upgraded=1" -> after this, the machine shows at tier 2 and
    // the dev print "[dev] PaP s1_mahem_up -> tier 3/3" fires on the third pack (in a dev build).
    upgraded = zm_weapons::is_weapon_upgraded( up );
    acc_utility::log( "pap_levels: Mahem PaP-to-tier3 fix - was_aat_exempt=" + was_exempt + " is_weapon_upgraded=" + upgraded + " (machine now stays visible past pack 2)" );
}

// War Machine clone of make_mahem_pap_visible_to_tier3 (user 2026-07-09): its CSV row also carries
// is_aat_exempt TRUE (launcher), so the identical un-exempt keeps the PaP machine visible for pack 3.
// Full mechanism trace: the Mahem comment block above.
function make_war_machine_pap_visible_to_tier3()
{
    if ( !isdefined( level.aat_exemptions ) ) return;
    up = GetWeapon( "t6_war_machine_up" );
    if ( !isdefined( up ) || up == level.weaponNone ) return;
    up = zm_weapons::get_nonalternate_weapon( up );

    was_exempt = isdefined( level.aat_exemptions[ up ] );
    level.aat_exemptions[ up ] = undefined;
    acc_utility::log( "pap_levels: War Machine PaP-to-tier3 fix - was_aat_exempt=" + was_exempt + " (machine stays visible past pack 2)" );
}

// Blast-O-Matic tier-3 fix (user 2026-07-03) - its CSV row ships is_aat_exempt TRUE (wonder-class
// special), so like the Thundergun/Mahem the machine would hide after pack 2. Same un-exempt fix;
// our packs never aat::acquire, so no alt-ammo can leak in (visibility gate only).
function make_blasto_pap_visible_to_tier3()
{
    if ( !isdefined( level.aat_exemptions ) ) return;
    up = GetWeapon( "t9_semiauto_cosplay_up" );
    if ( !isdefined( up ) || up == level.weaponNone ) return;
    up = zm_weapons::get_nonalternate_weapon( up );

    was_exempt = isdefined( level.aat_exemptions[ up ] );
    level.aat_exemptions[ up ] = undefined;
    acc_utility::log( "pap_levels: Blast-O-Matic PaP-to-tier3 fix - was_aat_exempt=" + was_exempt + " (machine now stays visible past pack 2)" );
}

// China Lake tier-3 fix (user 2026-07-05) - its CSV row carries the launcher is_aat_exempt flag (like the
// Mahem), so without this the PaP machine would hide after pack 2. Same un-exempt fix; our packs never
// aat::acquire, so no alt-ammo can leak in (visibility gate only). ALWAYS-SAFE: if the weapon isn't exempt
// this is a no-op (was_exempt=0). register_special_upgrades() (in _acc_weapon_variants) handles the tier-key
// mapping generically - no per-gun edit needed there.
function make_havoc_pap_visible_to_tier3()
{
    if ( !isdefined( level.aat_exemptions ) ) return;
    up = GetWeapon( "apex_beam_rifle_up" );
    if ( !isdefined( up ) || up == level.weaponNone ) return;
    up = zm_weapons::get_nonalternate_weapon( up );

    was_exempt = isdefined( level.aat_exemptions[ up ] );
    level.aat_exemptions[ up ] = undefined;
    acc_utility::log( "pap_levels: Havoc PaP-to-tier3 fix - was_aat_exempt=" + was_exempt + " (machine now stays visible past pack 2)" );
}

function player_setup_loop()
{
    level endon( "end_game" );
    level flag::wait_till( "initial_blackscreen_passed" );

    for ( ;; )
    {
        players = GetPlayers();
        for ( i = 0; i < players.size; i++ )
        {
            p = players[ i ];
            if ( !isdefined( p ) || !isplayer( p ) ) continue;
            if ( IS_TRUE( p.acc_pap_setup_done ) ) continue;

            p.acc_pap_setup_done = true;
            if ( !isdefined( p.acc_pap_tier ) ) p.acc_pap_tier = [];
            p thread pap_taken_watcher();
            p thread box_grab_clear_watcher();   // box guns must come out stock (3-tier revamp)
            p thread pap_hud_loop();
        }
        wait 1;
    }
}

// ---------------------------------------------------------------------------
// Tier-tracking SAFETY NET (self = player). acc_do_first_pack now records tier 1 itself
// (we block the stock float pack), so the stock "pap_taken" notify never fires in normal
// play - this watcher is a defensive fallback that still records a tier if any stock pack
// path ever runs. Harmless if it never fires.
// ---------------------------------------------------------------------------

function pap_taken_watcher()
{
    self endon( "disconnect" );

    for ( ;; )
    {
        self waittill( "pap_taken" );
        wait 0.2; // let the weapon swap settle so GetCurrentWeapon is the packed gun

        w = self GetCurrentWeapon();
        if ( !isdefined( w ) ) continue;
        base = acc_weapon_variants::true_base( w );   // strips _acc twin suffix so the tier follows recoil swaps

        if ( !isdefined( self.acc_pap_tier ) ) self.acc_pap_tier = [];
        cur = ( isdefined( self.acc_pap_tier[ base ] ) ? self.acc_pap_tier[ base ] : 0 );
        if ( cur >= ACC_PAP_MAX_TIER )
            continue;   // maxed - no PaP display (user 2026-06-22)

        cur++;
        self.acc_pap_tier[ base ] = cur;
        // PaP tier TOAST removed (user 2026-06-22): no display/indication - only the machine price.
    }
}

// self = player. The Mystery Box must hand over a STOCK gun (user 2026-06-15). Tier 1 is now a
// BASE form (damage only), so is_weapon_upgraded() can no longer keep a re-boxed copy stock - this
// watcher resets the tier of whatever base the box just gave. Stock fires "user_grabbed_weapon"
// on the player when they take a box weapon (_zm_magicbox.gsc:809); after the give settles the
// box weapon is the current weapon, so clearing that base's tier makes the copy stock again.
function box_grab_clear_watcher()
{
    self endon( "disconnect" );

    for ( ;; )
    {
        // The AW driver passes the granted weapon OBJECT on the notify (2026-07-12 mule-kick fix):
        // that IS the box gun, definitively - no settle wait needed, and immune to the at-limit
        // take churn that could park GetCurrentWeapon() on ANOTHER owned gun (with Mule Kick the
        // legacy settle then cleared the WRONG base's tier). Bare stock-shape notify (arg
        // undefined) falls back to the settle poll.
        self waittill( "user_grabbed_weapon", w );
        if ( !isdefined( w ) )
        {
            // Robust settle (2026-07-11): the old "one weapon_change_complete / 1.0s cap" could fire
            // MID-RAISE (early _complete from the at-limit take churn, or a slow-raise gun blowing
            // the cap), making this read the OLD gun and miss the tier clear -> the re-boxed copy
            // kept a stale PaP tier. wait_box_give_settled polls until the current weapon actually
            // changed + held stable, and returns it.
            w = self acc_weapon_variants::wait_box_give_settled();
        }
        if ( !isdefined( self ) ) return;

        if ( !isdefined( w ) || w == level.weaponNone ) continue;
        // A box gun is always a BASE form (the box never rolls our "_up" twins). Only clear base
        // forms so a rare BGB crate-power box upgrade isn't wrongly zeroed.
        if ( zm_weapons::is_weapon_upgraded( w ) ) continue;

        base = acc_weapon_variants::true_base( w );
        if ( isdefined( self.acc_pap_tier ) && isdefined( self.acc_pap_tier[ base ] ) )
            self.acc_pap_tier[ base ] = 0;
    }
}

// self = player. Clear acc_pap_tier[ base ] for any base the player no longer carries ANY form
// of (covers wallbuy-over / slot swaps that leave a stale tier so a future stock copy of that
// base would falsely read PaP'd). The box-grab clear above handles re-boxing the SAME base; this
// catches everything else. Gated so it never fires during a pack / perk drink / laststand -
// windows where the primaries list is transiently incomplete and a legit tier would be dropped.
function prune_lost_tiers()
{
    if ( !isdefined( self.acc_pap_tier ) ) return;
    if ( IS_TRUE( self.laststand ) || IS_TRUE( self.acc_pap_busy ) ) return;
    if ( isdefined( self.is_drinking ) && self.is_drinking > 0 ) return;

    held = [];
    guns = self GetWeaponsListPrimaries();
    eq = self GetCurrentWeapon();
    if ( isdefined( eq ) && eq != level.weaponNone ) guns[ guns.size ] = eq;
    for ( i = 0; i < guns.size; i++ )
    {
        g = guns[ i ];
        if ( !isdefined( g ) || g == level.weaponNone ) continue;
        b = acc_weapon_variants::true_base( g );
        if ( isdefined( b ) && b != level.weaponNone ) held[ b ] = true;
    }

    keys = getarraykeys( self.acc_pap_tier );
    for ( i = 0; i < keys.size; i++ )
    {
        k = keys[ i ];
        if ( self.acc_pap_tier[ k ] <= 0 ) continue;
        if ( !IS_TRUE( held[ k ] ) ) self.acc_pap_tier[ k ] = 0;
    }
}

// PaP tier for `weapon` on `player` (0..3). Twin-aware (keyed by acc_weapon_variants::true_base
// so the tier follows recoil/fire swaps). 3-tier revamp: a BASE gun reads its stored tier
// directly (0 = stock / box-fresh, 1 = damage-only first pack) - the box-grab clear + possession prune
// keep a box copy at 0, so a base gun never shows phantom PaP. An engine-"_up" gun is the tier-2
// transform form or higher; clamp up defensively if our record ever lagged behind the asset.
function get_tier( player, weapon )
{
    if ( !isdefined( weapon ) || weapon == level.weaponNone ) return 0;
    // Action Figure: tier IS the held speed-twin form - bypass the counter + the is_weapon_upgraded bump below
    // (the twins are marked upgraded ONLY for PaP-machine visibility, which would otherwise misread as tier 2).
    if ( is_actionfigure( weapon ) ) return actionfigure_tier_of( weapon );
    // Fire Bow: dedicated in-place tier counter (its demon-gate form is statically "upgraded", which would
    // otherwise trip the is_weapon_upgraded bump below and read tier 2 at base). user 2026-07-07.
    if ( is_firebow( weapon ) ) return firebow_tier( player );
    // THE CYBERJACK (L-STAR chassis): in-place PaP, no _up form - its tier is the dedicated counter. docs/43.
    if ( is_cyberjack( weapon ) ) return cyberjack_tier( player );
    if ( !isdefined( player.acc_pap_tier ) ) return 0;
    base = acc_weapon_variants::true_base( weapon );   // twin-aware: tier follows recoil/fire swaps
    stored = ( isdefined( player.acc_pap_tier[ base ] ) ? player.acc_pap_tier[ base ] : 0 );
    if ( zm_weapons::is_weapon_upgraded( weapon ) && stored < 2 ) return 2;
    return stored;
}

// Tier for the INFO CARD. get_tier already clamps an "_up" gun to >= 2, so this is now a thin
// pass-through (kept for callers / future divergence).
function get_card_tier( player, weapon )
{
    return get_tier( player, weapon );
}

// PaP damage ladder (LINEAR): each pack adds +33.33% of base (a flat +1/3 each tier), so the
// body-shot multiplier is 1.3333 / 1.66666 / 1.999999 = +33.33% / +66.66% / ~+100% over base - T3
// MAX = DOUBLE damage (user 2026-06-24). Returned as a layer for _acc_damage's ADDITIVE bonus_sum
// (a "+33%" = a 1.3333 layer; bonus_factor is the literal sum of layers, _acc_damage.gsc:427-430).
// The "% is the only damage lever" model (user 2026-06-16): acc_weapon_balance_mult normalizes every
// form (base/_up/twin) per gun, so the "_up" transform's own raw damage doesn't double-count - this
// ladder IS the PaP damage progression.
function pap_tier_mult( tier )
{
    switch ( tier )
    {
    case 1: return 1.3333;     // +33.33% over base
    case 2: return 1.66666;    // +66.66% (another +33.33% of base)
    case 3: return 1.999999;   // ~+100% MAX (double damage)
    }
    return 1.0; // tier 0 (not packed)
}

function tier_benefit( tier )
{
    switch ( tier )
    {
    // Vague by design (docs/31): the "PaP TIER N/3" prefix shows progress; the benefit hides the % (exact in docs/04).
    case 1: return "more damage. Pack again to TRANSFORM the gun (tier 2).";
    case 2: return "much more damage + upgraded form (explosive / akimbo / etc.)";
    case 3: return "greatly increased damage (MAX)";
    }
    return "";
}

// NOTE: the PaP tier damage multiplier formerly lived here as pap_damage_cb (a
// modifying actor-damage callback). It was consolidated into _acc_damage's
// multiplier chain on 2026-06-14 - see the init() comment and the PaP layer in
// _acc_damage::on_ai_damage. get_tier + pap_tier_mult above remain the source of
// truth that chain reads.

// ---------------------------------------------------------------------------
// HUD: held weapon's tier -> accPapTier clientuimodel (roman-numeral icon, bottom-right)
// ---------------------------------------------------------------------------

function pap_hud_loop()
{
    self endon( "disconnect" );
    level endon( "end_game" );

    // The held weapon's PaP tier is shown as a roman-numeral cyber-shield icon (I/II/III)
    // by acc_hud.lua's CoD.AccPapTierIcon, centered over the gadget HUD circle (bottom-right).
    // It's driven by the accPapTier clientuimodel, which we push here every 0.25s on change
    // (icon hidden at tier 0). This REPLACED the old bottom-right "PaP TIER x/3" font string
    // (user 2026-06-16) - the same get_tier value perk_info pushes for the PaP card, so the
    // two writers never disagree. set_pap_tier clamps; prune keeps box-fresh bases at 0.
    last_pushed = -1;

    for ( ;; )
    {
        wait 0.25;
        if ( !isdefined( self ) ) return;

        self prune_lost_tiers();   // keep box-fresh / dropped bases at tier 0

        tier = get_tier( self, self GetCurrentWeapon() );
        if ( tier != last_pushed )
        {
            acc_lui::set_pap_tier( self, tier );
            last_pushed = tier;
        }
    }
}
