# =============================================================================
# run_game.ps1 - launch the already-built map straight into the game.
#
# Why this exists: the Mod Tools Launcher's "Run" launches BlackOps3.exe
# DIRECTLY, which trips BO3's Steam DRM ("Steam must be running to play this
# game" popup, then exits) even with Steam running + steam_appid.txt present.
# Launching THROUGH Steam (steam://run/311210) gives the proper DRM context,
# so the game opens and loads the dev map. VERIFIED working 2026-06-12.
#
# Usage:  .\tools\run_game.ps1
# Build first (.\tools\build_map.ps1, or -GscOnly). Steam must be running and logged in.
#
# DEV / GOD ARE NOT LAUNCH FLAGS (user 2026-07-15 "this is the way we test in this repo... we don't
# use launch flags"): they are HARDCODED in the build - zm_abandoned_cyber_city.gsc::
# acc_resolve_dev_flags() sets level.acc_dev / level.acc_god (flip to "= true;" for a test session,
# restore the hardcoded "= false;" ship lines before publish - prep_release Gate 0 enforces it, and
# FAILS if a dvar read reappears) + rebuild. This script passes ENGINE ARGS ONLY; whatever the
# current build hardcodes is what launches. Doctrine: CLAUDE.md "HOW TEST SESSIONS ARE ARMED" + docs/22.
# =============================================================================

# Legacy params kept ONLY so old call sites don't error - ALL of them (incl. -NoDev) are NO-OPS and no
# longer affect the launch (dev/god ride the BUILD since 2026-07-15; gameplay knobs run on in-code
# defaults since 2026-07-07).
param([switch]$NoBoss, [switch]$NoDev, [switch]$NoVarDebug, [switch]$ClosedMap, [switch]$NoAmbient, [switch]$NoLockdown)

# THE GAMETYPE FIX (verified 2026-06-13): you MUST pass the engine command
# `+set_gametype zclassic`, NOT `+set g_gametype zclassic`. The g_gametype dvar
# is immediately reset to the session default by the engine
# (callbacks_shared.gsc), so a plain +set never survives -> the launch falls
# back to the MP default "tdm" -> scripts/zm/gametypes/tdm.gsc is missing ->
# fatal Com_ERROR -> black screen. `set_gametype` is the command the Mod Tools
# Launcher itself uses, and it sticks.
# Also keep BO3's Steam LAUNCH OPTIONS EMPTY (Steam appends them -> doubled
# command line -> the same tdm corruption).
#
# NOTE: custom LUI (ui/uieditor/menus/hud/acc_hud.lua) runs on Steam BO3 with NO
# special flag - verified 2026-06-13 (our menu executed in-game; a Lua bug in it
# threw "UI Error 43408", which proves it was NOT sandbox-blocked). The community
# "-unsafe-lua" arg is a BOIII-client flag, not a Steam BO3 one - on Steam it logs
# "Unknown command" and does nothing, so it is intentionally NOT passed here.
# (L3akMod is still required in the MOD TOOLS bin to BUILD the .lua. docs/28.)
# ENGINE ARGS ONLY - no acc_dev/acc_god (they're hardcoded in the build, see header).
# g_log/g_logSync: enable the engine GAME log (games_mp.log) - the [ACCDIAG] diagnostics heartbeat
# (_acc_diag.gsc, LogPrint census every 30s) lands there. logfile 1 covers console_mp.log separately.
# ---- [acc] BUILD-IN-PROGRESS GUARD (2026-07-25) -------------------------------------------------
# Launching while the linker is writing the .ff makes the game load a HALF-WRITTEN fastfile ->
# torn Lua chunks -> an on-screen "UI Error <code>" box at load (live-hit 3:31 AM 2026-07-25:
# game launched at 3:31:44, linker finished the .ff at 3:34:07 -> UI Error 44429). Same family
# as the concurrent-linker collisions (memory concurrent-linker-collision-0xc0000005). Refuse to
# launch until the build tools are done - a fresh launch 60s later costs nothing; debugging a
# phantom UI error costs an hour.
$buildProcs = Get-Process linker_modtools, cod2map64, radiant_modtools -ErrorAction SilentlyContinue
if ($buildProcs) {
    Write-Host ""
    Write-Host "[run_game] BUILD IN PROGRESS - NOT launching:" -ForegroundColor Red
    $buildProcs | ForEach-Object { Write-Host ("    {0} (pid {1})" -f $_.ProcessName, $_.Id) -ForegroundColor Red }
    Write-Host "[run_game] The game would load a HALF-WRITTEN .ff (= 'UI Error' box / corrupt load)." -ForegroundColor Red
    Write-Host "[run_game] Wait for the build to finish, then run this again." -ForegroundColor Yellow
    exit 1
}
# -------------------------------------------------------------------------------------------------

$gameArgs = "+set fs_game zm_abandoned_cyber_city +set_gametype zclassic +devmap zm_abandoned_cyber_city +set developer 1 +set logfile 1 +set g_log games_mp.log +set g_logSync 1"

# ---- [acc] LEADERBOARD AGENT PRE-SPAWN (docs/40, user 2026-07-12 "do it silently") --------------
# Spawn the hidden network agent BEFORE the game (tools/spawn_lb_agent.ps1, GENERATED by
# build_lb_lui.js - PowerShell -WindowStyle Hidden = no window ever) and pass +set acc_lb_agent 1
# (appended to $gameArgs below) so the game skips its own os.execute spawn - the one that opened a
# terminal window at match start. Helper missing/failing never blocks the launch (the game falls
# back to its own minimized spawn).
$lbHelper = Join-Path $PSScriptRoot 'spawn_lb_agent.ps1'
if (Test-Path $lbHelper) { & $lbHelper }
$gameArgs = "$gameArgs +set acc_lb_agent 1"
# -------------------------------------------------------------------------------------------------

Write-Host "launching BO3 through Steam (DRM-safe): steam://run/311210"
Write-Host "args: $gameArgs"
Start-Process "steam://run/311210//$gameArgs"

# Wait for the game to come up (asset load takes ~30-60s; RAM climbs to ~5 GB).
for ($i = 0; $i -lt 18; $i++) {
    Start-Sleep -Seconds 5
    $p = Get-Process BlackOps3 -ErrorAction SilentlyContinue
    if ($p) {
        $gb = [math]::Round($p.WorkingSet64 / 1GB, 1)
        Write-Host ("  +{0,3}s  PID {1}  {2} GB  responding={3}" -f (($i + 1) * 5), $p.Id, $gb, $p.Responding)
        if ($gb -ge 4) { Write-Host "loaded - you should be in zm_abandoned_cyber_city. Press ~ for the [acc] console."; break }
    } else {
        Write-Host ("  +{0,3}s  not up yet" -f (($i + 1) * 5))
    }
}
