# spawn_lb_agent.ps1 - GENERATED by tools/build_lb_lui.js - DO NOT EDIT BY HAND.
# Source of truth: tools/lui_chunks/spawn_lb_agent.tpl.ps1 (this template; URL/key
# spliced at generation, same source as the game's acc_lb_boot_chunk.lua).
#
# LEADERBOARD AGENT PRE-SPAWN (docs/40, user 2026-07-12: "it just starts up my
# terminal every time... do it silently"): the game-side agent spawn (os.execute)
# unavoidably shows a console window. This helper spawns the SAME agent BEFORE the
# game starts, with -WindowStyle Hidden = NO window, ever. The play scripts call it
# and pass `+set acc_lb_agent 1`, which makes _acc_leaderboard.gsc skip the in-game
# spawn entirely -> zero terminals on this box. Liveness handshake (ping/pong files,
# same protocol as the agent) skips a duplicate if an agent from a previous session
# still runs. Never blocks or fails the launch: any error = silent no-op (the game
# falls back gracefully; worst case the board is offline for the session).
#
# Agent protocol (keep in LOCKSTEP with acc_lb_boot_chunk.lua):
#   players\acc_lb_ping.txt    -> del + echo pong>acc_lb_pong.txt   (liveness)
#   players\acc_lb_do_post.txt -> curl POST acc_lb_post.json -> acc_lb_post_result.txt
#   players\acc_lb_do_get.txt  -> curl GET top10 -> acc_lb_top10.txt + ACCEOF marker
# Launcher agents live ~4h (vs the in-game 2h) so long sessions stay covered.

$ErrorActionPreference = 'SilentlyContinue'
try {
    $u = 'https://acc-leaderboard.jordana-urbaez.workers.dev'
    $k = 'ffa2186adc30e3d03766e5ec3499667a'
    if (-not $u) { exit 0 }   # local-only generation: nothing to spawn

    $roots = @("${env:ProgramFiles(x86)}\Steam\steamapps\common\Call of Duty Black Ops III",
               "$env:ProgramFiles\Steam\steamapps\common\Call of Duty Black Ops III")
    $gameRoot = $null
    foreach ($r in $roots) { if ($r -and (Test-Path (Join-Path $r 'BlackOps3.exe'))) { $gameRoot = $r; break } }
    if (-not $gameRoot) { exit 0 }
    $players = Join-Path $gameRoot 'players'

    # liveness handshake: an agent from a previous session answers within ~1s
    try { Remove-Item (Join-Path $players 'acc_lb_pong.txt') -Force -ErrorAction Stop } catch {}
    Set-Content -Path (Join-Path $players 'acc_lb_ping.txt') -Value 'ping' -Encoding ascii
    Start-Sleep -Milliseconds 1800
    if (Test-Path (Join-Path $players 'acc_lb_pong.txt')) {
        Write-Host "[lb] leaderboard agent already alive - reusing it"
        exit 0
    }

    # unique filename: NEVER overwrite a possibly-running .bat (cmd re-reads from disk)
    $tok = -join (1..6 | ForEach-Object { [char](Get-Random -InputObject (48..57 + 97..122)) })
    $bat = Join-Path $players "acc_lb_agent_ps_$tok.bat"
    $lines = @(
        '@echo off',
        'rem ACC leaderboard agent - pre-spawned HIDDEN by spawn_lb_agent.ps1 (docs/40).',
        'cd /d "%~dp0"',
        'for /l %%i in (1,1,14400) do (',
        '  if exist acc_lb_ping.txt (',
        '    del acc_lb_ping.txt >nul 2>&1',
        '    echo pong>acc_lb_pong.txt',
        '  )',
        '  if exist acc_lb_do_post.txt (',
        '    del acc_lb_do_post.txt >nul 2>&1',
        "    curl.exe -s -m 6 -X POST -H `"content-type: application/json`" -H `"x-acc-key: $k`" --data @acc_lb_post.json -o acc_lb_post_result.txt $u/games",
        '  )',
        '  if exist acc_lb_do_get.txt (',
        '    del acc_lb_do_get.txt >nul 2>&1',
        "    curl.exe -s -m 5 -o acc_lb_top10.txt $u/top10.txt && echo ACCEOF_OK>>acc_lb_top10.txt || echo ACCEOF_ERR>>acc_lb_top10.txt",
        '  )',
        '  ping -n 2 127.0.0.1 >nul',
        ')',
        'del "%~f0"'
    )
    Set-Content -Path $bat -Value ($lines -join "`r`n") -Encoding ascii
    Start-Process -FilePath "$env:ComSpec" -ArgumentList '/c', "`"$bat`"" -WindowStyle Hidden
    Write-Host "[lb] hidden leaderboard agent pre-spawned ($(Split-Path $bat -Leaf))"
} catch { }
exit 0
